export const germanGlossary: Readonly<Record<string, string>> = {
  "1920": "1920 (año)",
  "ab": "desde; a partir de; partícula de verbo separable",
  "abend": "tarde; noche (der Abend)",
  "aber": "pero; sin embargo",
  "abfahrt": "salida (die Abfahrt)",
  "abgeben": "entregar",
  "abgegeben": "entregado (abgeben: entregar)",
  "abgeholt": "recogido (abholen: recoger)",
  "abgeordnete": "diputado/a (der/die Abgeordnete)",
  "abgeschlossen": "concluido; cerrado (abschließen: finalizar)",
  "abkommens": "del acuerdo (das Abkommen)",
  "ablauf": "proceso; desarrollo (der Ablauf)",
  "abläufe": "procesos; secuencias (die Abläufe)",
  "abläuft": "transcurre; vence (ablaufen: transcurrir)",
  "abrufbar": "consultable; disponible",
  "abschicken": "enviar",
  "abschluss": "finalización; título (der Abschluss)",
  "acht": "ocho",
  "achtzehn": "dieciocho",
  "adresse": "dirección (die Adresse)",
  "akte": "expediente (die Akte)",
  "aktualisieren": "actualizar",
  "alle": "todos; todas",
  "allen": "a todos; a todas",
  "aller": "de todos; de todas",
  "alles": "todo",
  "als": "como; cuando; que (comparación)",
  "alt": "viejo; antiguo",
  "alte": "viejo; antigua",
  "altes": "antiguo (neutro)",
  "am": "en el; al (contracción de an dem)",
  "ambulant": "ambulatorio; de atención externa",
  "an": "en, junto a; partícula de verbo separable",
  "analysieren": "analizar",
  "andere": "otro; otra",
  "ändern": "cambiar",
  "anders": "de otro modo; distinto",
  "änderten": "cambiaron (ändern: cambiar)",
  "anfechten": "impugnar; recurrir",
  "anfing": "empezó (anfangen: empezar)",
  "angebot": "oferta (das Angebot)",
  "angebote": "ofertas (die Angebote)",
  "angekommen": "llegado (ankommen: llegar)",
  "angekündigt": "anunciado (ankündigen: anunciar)",
  "angekündigte": "anunciado; anunciada",
  "angelegten": "establecidos; creados",
  "angespannt": "tenso; estresado",
  "anhörung": "audiencia (die Anhörung)",
  "ankamen": "llegaron (ankommen: llegar)",
  "ankunft": "llegada (die Ankunft)",
  "anlass": "motivo; ocasión (der Anlass)",
  "anmeldung": "inscripción (die Anmeldung)",
  "anna": "Anna (nombre propio)",
  "annahme": "suposición; aceptación (die Annahme)",
  "annehmen": "aceptar; suponer",
  "anonym": "anónimo; anónima",
  "anpassung": "adaptación (die Anpassung)",
  "anprobieren": "probarse (una prenda)",
  "anriefen": "llamaron (anrufen: llamar)",
  "anruft": "llama por teléfono (anrufen: llamar)",
  "ans": "al; hacia el (contracción de an das)",
  "anspruchsvoll": "exigente",
  "anstrengend": "agotador",
  "antrag": "solicitud (der Antrag)",
  "anträge": "solicitudes (die Anträge)",
  "antrags": "de la solicitud (der Antrag)",
  "antwort": "respuesta (die Antwort)",
  "antworten": "responder; respuestas (die Antwort)",
  "anwendung": "aplicación; uso (die Anwendung)",
  "anzupassen": "adaptar; ajustarse",
  "apfel": "manzana (der Apfel)",
  "äpfel": "manzanas (plural de der Apfel)",
  "arbeit": "trabajo (die Arbeit)",
  "arbeite": "trabajo (arbeiten: trabajar)",
  "arbeiten": "trabajar; trabajos (die Arbeit)",
  "arbeitet": "trabaja (arbeiten: trabajar)",
  "arbeitete": "trabajó; trabajaba (arbeiten: trabajar)",
  "arbeitsalltag": "rutina laboral (der Arbeitsalltag)",
  "arktis": "Ártico; región polar (die Arktis)",
  "artikels": "del artículo (der Artikel)",
  "arzt": "médico (der Arzt)",
  "ärztin": "médica (die Ärztin)",
  "auch": "también; incluso",
  "auf": "sobre; en; a; partícula de verbo separable",
  "aufführung": "representación (die Aufführung)",
  "aufgabe": "tarea; ejercicio (die Aufgabe)",
  "aufgaben": "tareas; ejercicios (die Aufgaben)",
  "aufgehört": "dejado; parado (aufhören: dejar)",
  "aufgestanden": "levantado (aufstehen: levantarse)",
  "aufgrund": "debido",
  "aufnahme": "grabación; admisión (die Aufnahme)",
  "aufsatz": "redacción; ensayo (der Aufsatz)",
  "auftrag": "encargo; pedido (der Auftrag)",
  "aufwand": "esfuerzo (der Aufwand)",
  "aufzug": "ascensor (der Aufzug)",
  "aus": "de; desde; hecho de; partícula de verbo separable",
  "ausfiel": "falló; se canceló (ausfallen: fallar)",
  "ausfielen": "fallaron; se cancelaron (ausfallen)",
  "ausgelöst": "provocado; desencadenado (auslösen)",
  "ausgestrahlt": "emitido (ausstrahlen: emitir)",
  "ausgewählten": "seleccionados (auswählen: seleccionar)",
  "ausgewerteten": "analizados; evaluados",
  "ausland": "extranjero; exterior (das Ausland)",
  "ausruhen": "descansar",
  "ausschuss": "comité; comisión (der Ausschuss)",
  "ausstellung": "exposición (die Ausstellung)",
  "ausverkauft": "agotado; sin existencias",
  "ausweis": "documento de identidad (der Ausweis)",
  "ausweitung": "ampliación (die Ausweitung)",
  "automatisch": "automáticamente",
  "autor": "autor (der Autor)",
  "autorin": "autora (die Autorin)",
  "bad": "baño (das Bad)",
  "bahn": "tren; ferrocarril (die Bahn)",
  "bahnhof": "estación de tren (der Bahnhof)",
  "bald": "pronto",
  "ball": "pelota; balón (der Ball)",
  "batterien": "baterías (die Batterien)",
  "bauen": "construir",
  "baustelle": "obra; zona de obras (die Baustelle)",
  "beachtet": "tenido en cuenta (beachten: tener en cuenta)",
  "beantragen": "solicitar",
  "beantragt": "solicitado (beantragen: solicitar)",
  "beantwortet": "respondido (beantworten: responder)",
  "beantwortete": "respondió (beantworten: responder)",
  "bearbeitet": "tramitado; editado (bearbeiten: tramitar)",
  "bedarf": "necesidad (der Bedarf)",
  "bedingungen": "condiciones (die Bedingungen)",
  "beendet": "terminado (beenden: terminar)",
  "beendeten": "terminaron (beenden: terminar)",
  "befund": "informe; resultado (der Befund)",
  "begann": "empezó (beginnen: empezar)",
  "beginne": "empiezo; empieza (beginnen: empezar)",
  "beginnen": "empezar",
  "beginnt": "empieza (beginnen: empezar)",
  "begonnen": "empezado (beginnen: empezar)",
  "begründeten": "justificaron; fundamentaron",
  "begrünen": "reverdecer; ajardinar",
  "behandlung": "tratamiento (die Behandlung)",
  "behörde": "autoridad; organismo público (die Behörde)",
  "bei": "en casa de; junto a; en; al",
  "beim": "en el; junto al (contracción de bei dem)",
  "beitrag": "contribución; artículo (der Beitrag)",
  "beiträge": "contribuciones; artículos (die Beiträge)",
  "bekommen": "recibir; conseguir",
  "belasten": "cargar; perjudicar",
  "belege": "justificantes; recibos (die Belege)",
  "beleuchtung": "iluminación (die Beleuchtung)",
  "benötigter": "necesario; requerido",
  "bequem": "cómodo",
  "beratung": "asesoramiento (die Beratung)",
  "bereits": "ya",
  "bericht": "informe (der Bericht)",
  "berichten": "informar",
  "berichtet": "informa; informado (berichten: informar)",
  "beriet": "asesoró (beraten: asesorar)",
  "berlin": "Berlín (ciudad)",
  "beruhen": "basarse; deberse",
  "beschädigte": "dañó; dañado",
  "beschädigten": "dañaron; dañados",
  "beschäftigt": "ocupado; empleado",
  "beschäftigten": "empleados; ocuparon",
  "bescheid": "notificación; resolución (der Bescheid)",
  "bescheinigung": "certificado (die Bescheinigung)",
  "beschleunigen": "acelerar",
  "beschlossen": "decidido (beschließen: decidir)",
  "beschrieben": "descrito (beschreiben: describir)",
  "beschwerde": "queja; reclamación (die Beschwerde)",
  "beschwerden": "molestias; quejas (die Beschwerden)",
  "besichtigen": "visitar; inspeccionar",
  "besonderer": "especial (masculino)",
  "besonders": "especialmente",
  "besprechung": "reunión (die Besprechung)",
  "besser": "mejor",
  "bessere": "mejor; mejores",
  "bestanden": "aprobado; existido (bestehen: aprobar/existir)",
  "bestätigen": "confirmar",
  "bestätigt": "confirmado (bestätigen: confirmar)",
  "bestätigte": "confirmó (bestätigen: confirmar)",
  "bestätigter": "confirmado (masculino)",
  "bestellen": "pedir; encargar",
  "bestellt": "pedido; encargado (bestellen: pedir)",
  "bestellten": "pidieron; encargaron (bestellen)",
  "besuch": "visita (der Besuch)",
  "besuchen": "visitar",
  "besucher": "visitante (der Besucher)",
  "besucht": "visita; visitado (besuchen: visitar)",
  "betreuen": "atender; cuidar",
  "betrieb": "empresa; funcionamiento (der Betrieb)",
  "betriebe": "empresas (die Betriebe)",
  "betriebsrat": "comité de empresa (der Betriebsrat)",
  "betroffenen": "afectados; afectados/as",
  "bett": "cama (das Bett)",
  "bevor": "antes de que",
  "bewarb": "presentó su candidatura (sich bewerben)",
  "beweise": "pruebas (die Beweise)",
  "bewerberin": "candidata (die Bewerberin)",
  "bewerteter": "evaluado; valorado",
  "bewertung": "evaluación; valoración (die Bewertung)",
  "bewohnern": "a los residentes (der Bewohner)",
  "bezahlen": "pagar",
  "bezahlt": "pagado; paga (bezahlen: pagar)",
  "beziehungen": "relaciones (die Beziehungen)",
  "bibliothek": "biblioteca (die Bibliothek)",
  "bild": "imagen; cuadro (das Bild)",
  "bin": "soy/estoy (sein: ser/estar)",
  "bis": "hasta",
  "bitte": "por favor; petición",
  "bitten": "pedir; rogar",
  "blaue": "azul (femenino)",
  "bleibe": "me quedo; quédate (bleiben: quedarse)",
  "bleiben": "quedarse; permanecer",
  "bleibt": "se queda; permanece (bleiben: quedarse)",
  "blieb": "se quedó; permaneció (bleiben: quedarse)",
  "blieben": "se quedaron; permanecieron (bleiben: quedarse)",
  "blutdruck": "presión arterial (der Blutdruck)",
  "brauchen": "necesitar",
  "brauchst": "necesitas (brauchen: necesitar)",
  "braucht": "necesita (brauchen: necesitar)",
  "briefe": "cartas (die Briefe)",
  "brot": "pan (das Brot)",
  "bruder": "hermano (der Bruder)",
  "buch": "libro (das Buch)",
  "bücher": "libros (plural de das Buch)",
  "bürger": "ciudadanos (die Bürger)",
  "bürgeramt": "oficina de atención ciudadana (das Bürgeramt)",
  "bürgermeisterin": "alcaldesa (die Bürgermeisterin)",
  "büro": "oficina (das Büro)",
  "bus": "autobús (der Bus)",
  "chef": "jefe (der Chef)",
  "dachte": "pensó; pensaba (denken: pensar)",
  "dämmung": "aislamiento (die Dämmung)",
  "daran": "en ello; a eso",
  "darüber": "sobre eso; por encima de",
  "das": "el; lo; eso (artículo/pronombre); que (relativo)",
  "dass": "que (conjunción)",
  "datei": "archivo (die Datei)",
  "daten": "datos (die Daten)",
  "datenbank": "base de datos (die Datenbank)",
  "datensatz": "registro; conjunto de datos (der Datensatz)",
  "dauert": "dura (dauern: durar)",
  "dauerte": "duró; duraba (dauern: durar)",
  "dauerten": "duraron; duraban (dauern: durar)",
  "debatten": "debates (die Debatten)",
  "decke": "techo; manta (die Decke)",
  "deinem": "a tu; de tu (dativo)",
  "deiner": "tu; de tu (femenino)",
  "dem": "al; del (artículo dativo)",
  "den": "al; a los (artículo acusativo)",
  "denen": "a quienes; a los que",
  "der": "el; la; de la; que (relativo)",
  "des": "del; de un (genitivo)",
  "dessen": "cuyo; del cual",
  "desto": "más (en je … desto)",
  "deutlich": "claro; claramente",
  "deutsch": "alemán; alemana",
  "dich": "te; a ti",
  "die": "la/los/las (artículo); que (relativo)",
  "diese": "esta; estas; estos",
  "dieser": "este; esta; de esta",
  "dieses": "de este; este",
  "digital": "digital",
  "digitale": "digital (femenino)",
  "digitalen": "digital; digitales",
  "digitaler": "digital (masculino)",
  "diplomatischer": "diplomático (masculino)",
  "dir": "te; a ti",
  "direkt": "directo; directamente",
  "direktorin": "directora (die Direktorin)",
  "diskutieren": "debatir; discutir",
  "dokumente": "documentos (die Dokumente)",
  "dokumentiert": "documentado (dokumentieren: documentar)",
  "dozentin": "docente; profesora universitaria (die Dozentin)",
  "draußen": "fuera; en el exterior",
  "drei": "tres",
  "drinnen": "dentro; en el interior",
  "du": "tú",
  "durch": "por; a través de",
  "durchgeführter": "llevado a cabo; realizado",
  "dürfen": "poder; tener permiso (dürfen)",
  "dürfte": "probablemente; podría (dürfen: poder)",
  "dürften": "probablemente; podrían (dürfen: poder)",
  "e-mail": "correo electrónico (die E-Mail)",
  "eigentümergemeinschaft": "comunidad de propietarios (die Eigentümergemeinschaft)",
  "ein": "un; uno",
  "eindeutig": "claro; inequívoco",
  "eindeutigen": "inequívoco; claro",
  "eine": "una",
  "einem": "a un; a una; con un",
  "einen": "un; a un",
  "einer": "una; de una; a una",
  "eines": "de un; de una",
  "einfache": "sencillo; sencilla",
  "einführung": "introducción; implantación (die Einführung)",
  "eingang": "entrada (der Eingang)",
  "eingecheckt": "facturado; registrado (einchecken)",
  "eingehen": "abordar; atender; recibirse",
  "eingeholt": "obtenido; recabado (einholen)",
  "eingelöst": "canjeado; retirado (einlösen)",
  "eingereichter": "presentado; entregado",
  "eingestellt": "contratado; configurado (einstellen)",
  "eingetroffen": "llegado; recibido (eintreffen)",
  "einigung": "acuerdo (die Einigung)",
  "einkaufen": "hacer la compra",
  "einladung": "invitación (die Einladung)",
  "einreichen": "presentar; entregar",
  "einsehbar": "consultable; visible",
  "einsetzt": "utiliza; aplica (einsetzen)",
  "einstellungen": "ajustes; configuración (die Einstellungen)",
  "einwilligung": "consentimiento (die Einwilligung)",
  "einzuschlafen": "quedarse dormido; dormirse",
  "eltern": "padres (die Eltern)",
  "emissionen": "emisiones (die Emissionen)",
  "empfehlen": "recomendar",
  "empfohlene": "recomendado; recomendada",
  "ende": "final; fin (das Ende)",
  "endet": "termina (enden: terminar)",
  "endlich": "por fin; finalmente",
  "energie": "energía (die Energie)",
  "energieverbrauch": "consumo energético (der Energieverbrauch)",
  "entdeckten": "descubrieron; descubierto (entdecken)",
  "entdeckter": "descubierto; detectado",
  "entlang": "a lo largo de; junto a",
  "entscheidung": "decisión (die Entscheidung)",
  "entschuldigten": "se disculparon (sich entschuldigen)",
  "entwickelte": "desarrolló; desarrollaba (entwickeln)",
  "entwicklung": "desarrollo (die Entwicklung)",
  "entworfener": "diseñado; proyectado",
  "er": "él",
  "erdbeeren": "fresas (die Erdbeeren)",
  "erfahrung": "experiencia (die Erfahrung)",
  "erfassten": "registraron; recopilaron (erfassen)",
  "erfolgen": "tener lugar; realizarse",
  "erfolgt": "tiene lugar; se realiza (erfolgen)",
  "erfolgte": "tuvo lugar; se realizó (erfolgen)",
  "ergebnis": "resultado (das Ergebnis)",
  "ergebnisse": "resultados (die Ergebnisse)",
  "erhobene": "recopilado; recogido (erheben)",
  "erholung": "descanso; recuperación (die Erholung)",
  "erkennen": "reconocer",
  "erkennt": "reconoce (erkennen: reconocer)",
  "erklären": "explicar",
  "erklärt": "explica; explicado (erklären: explicar)",
  "erklärte": "explicó (erklären: explicar)",
  "erklärung": "explicación; declaración (die Erklärung)",
  "erledigen": "hacer; resolver; despachar",
  "erleichtert": "aliviado; facilitado",
  "erneut": "de nuevo; nuevamente",
  "ernst": "serio",
  "eröffnet": "inaugura; abierto (eröffnen)",
  "eröffnete": "inauguró (eröffnen: inaugurar)",
  "erprobtes": "probado; ensayado",
  "erreichbar": "accesible; localizable",
  "erreichen": "alcanzar",
  "erreicht": "alcanza; alcanzado (erreichen: alcanzar)",
  "erreichte": "alcanzó (erreichen: alcanzar)",
  "erreichten": "alcanzaron (erreichen: alcanzar)",
  "errichteten": "construyeron; construidos (errichten)",
  "erscheint": "aparece; se publica (erscheinen)",
  "erschöpft": "agotado; exhausto",
  "ersetzen": "sustituir; reemplazar",
  "erwartete": "esperaba (erwarten: esperar)",
  "erweiterung": "ampliación (die Erweiterung)",
  "es": "ello; lo; hay",
  "esse": "como (essen: comer)",
  "essen": "comer; comida (das Essen)",
  "eure": "vuestro; vuestra; vuestros; vuestras",
  "euro": "euro (der Euro)",
  "experiment": "experimento (das Experiment)",
  "experten": "expertos (die Experten)",
  "fachleuten": "especialistas; expertos (dativo plural)",
  "fähigkeiten": "capacidades; habilidades (die Fähigkeiten)",
  "fahre": "voy; conduzco (fahren: ir/conducir)",
  "fahren": "ir; conducir",
  "fahrrad": "bicicleta (das Fahrrad)",
  "fahrräder": "bicicletas (die Fahrräder)",
  "fährt": "va; conduce (fahren: ir/conducir)",
  "falle": "caigo; caso (fallen: caer)",
  "fälle": "casos (der Fall)",
  "fällen": "talar; dictar (fällen)",
  "fand": "encontró (finden: encontrar)",
  "fehler": "error (der Fehler)",
  "festival": "festival (das Festival)",
  "fieber": "fiebre (das Fieber)",
  "fiel": "cayó (fallen: caer)",
  "film": "película (der Film)",
  "finanzierung": "financiación (die Finanzierung)",
  "finden": "encontrar",
  "findet": "encuentra (finden: encontrar)",
  "firma": "empresa (die Firma)",
  "firmen": "empresas (die Firmen)",
  "fläche": "superficie; zona (die Fläche)",
  "fluggesellschaft": "aerolínea (die Fluggesellschaft)",
  "flughafen": "aeropuerto (der Flughafen)",
  "flusses": "del río (der Fluss)",
  "fonds": "fondo (der Fonds)",
  "förderanträge": "solicitudes de ayudas (die Förderanträge)",
  "fördern": "fomentar; financiar",
  "förderung": "fomento; financiación (die Förderung)",
  "formular": "formulario (das Formular)",
  "forschenden": "investigadores; personal investigador",
  "forscher": "investigador (der Forscher)",
  "forscherin": "investigadora (die Forscherin)",
  "forschung": "investigación (die Forschung)",
  "forschungsteam": "equipo de investigación (das Forschungsteam)",
  "fortbildung": "formación continua (die Fortbildung)",
  "fortschritte": "avances; progresos (die Fortschritte)",
  "fotografie": "fotografía (die Fotografie)",
  "frage": "pregunta (die Frage)",
  "fragen": "preguntar; preguntas (die Frage)",
  "fragt": "pregunta (fragen: preguntar)",
  "französisch": "francés; francesa",
  "frau": "mujer; señora (die Frau)",
  "frei": "libre",
  "freiwillig": "voluntariamente; voluntario",
  "freiwillige": "voluntario; voluntaria (der/die Freiwillige)",
  "freuen": "alegrarse; alegrar",
  "freund": "amigo (der Freund)",
  "freundin": "amiga (die Freundin)",
  "freundlich": "amable; simpático",
  "freut": "se alegra (sich freuen)",
  "frisch": "fresco",
  "frische": "fresco; fresca",
  "frist": "plazo (die Frist)",
  "früh": "temprano",
  "früher": "antes; anteriormente",
  "früheste": "más temprano; más temprana",
  "frühjahr": "primavera (das Frühjahr)",
  "fühlt": "siente (fühlen: sentir)",
  "führt": "dirige; lleva (führen)",
  "führte": "dirigió; llevó (führen)",
  "fünf": "cinco",
  "fünfzig": "cincuenta",
  "funktioniert": "funciona (funktionieren: funcionar)",
  "für": "para; por",
  "fuß": "pie (der Fuß)",
  "fußball": "fútbol (der Fußball)",
  "gang": "pasillo; marcha (der Gang)",
  "gästen": "a los invitados (der Gast)",
  "gearbeitet": "trabajado (arbeiten: trabajar)",
  "gebacken": "horneado (backen: hornear)",
  "gebäude": "edificios (die Gebäude)",
  "gebaute": "construido; construida (bauen: construir)",
  "geben": "dar",
  "geblieben": "quedado (bleiben: quedarse)",
  "gebucht": "reservado; contratado (buchen)",
  "gebühren": "tasas; tarifas (die Gebühren)",
  "geduld": "paciencia (die Geduld)",
  "gefahren": "ido; conducido (fahren: ir/conducir)",
  "gefallen": "caído; gustado (fallen/gefallen)",
  "gefällt": "gusta; agrada (gefallen: gustar)",
  "geführt": "dirigido; llevado (führen)",
  "gefunden": "encontrado (finden: encontrar)",
  "gegessen": "comido (essen: comer)",
  "gegründete": "fundado; fundada (gründen: fundar)",
  "gehen": "ir",
  "geholfen": "ayudado (helfen: ayudar)",
  "gehört": "oído; pertenece (hören/gehören)",
  "geht": "va; funciona (gehen: ir)",
  "gekommen": "venido; llegado (kommen: venir)",
  "gelang": "consiguió; logró (gelingen: lograr)",
  "geld": "dinero (das Geld)",
  "gelernt": "aprendido (lernen: aprender)",
  "gelesen": "leído (lesen: leer)",
  "gelöscht": "borrado; eliminado (löschen: borrar)",
  "gelöst": "resuelto; solucionado (lösen: resolver)",
  "gemälde": "cuadros; pinturas (die Gemälde)",
  "gemeinsam": "juntos; conjuntamente",
  "gemeinsame": "común; conjunta",
  "gemeldet": "comunicado; registrado (melden: comunicar)",
  "gemessen": "medido (messen: medir)",
  "gemessenen": "medidos (messen: medir)",
  "genauen": "exactos; precisos",
  "genauso": "igual de; exactamente así",
  "genehmigung": "autorización (die Genehmigung)",
  "genesung": "recuperación (die Genesung)",
  "geöffnet": "abierto (öffnen: abrir)",
  "gepäck": "equipaje (das Gepäck)",
  "gepackt": "empaquetado; preparado (packen: empaquetar)",
  "geprüft": "revisado; comprobado (prüfen: comprobar)",
  "geprüfte": "revisado; comprobado",
  "geradeaus": "todo recto",
  "gerät": "aparato; dispositivo (das Gerät)",
  "geräte": "aparatos; dispositivos (die Geräte)",
  "geräumt": "despejado; desalojado (räumen: despejar)",
  "gereinigt": "limpiado (reinigen: limpiar)",
  "gern": "con gusto; gustosamente",
  "geschenk": "regalo (das Geschenk)",
  "geschichte": "historia; relato (die Geschichte)",
  "geschlossen": "cerrado (schließen: cerrar)",
  "geschrieben": "escrito (schreiben: escribir)",
  "geschwommen": "nadado (schwimmen: nadar)",
  "gesehen": "visto (sehen: ver)",
  "gesendet": "enviado; emitido (senden: enviar)",
  "gesondert": "por separado; aparte",
  "gespeichert": "guardado (speichern: guardar)",
  "gespeicherte": "guardado; guardada",
  "gespeicherten": "guardados; guardadas",
  "gesperrt": "bloqueado; cerrado (sperren: bloquear)",
  "gespräch": "conversación (das Gespräch)",
  "gespräche": "conversaciones (die Gespräche)",
  "gesprächen": "en las conversaciones (das Gespräch)",
  "gesprächs": "de la conversación (das Gespräch)",
  "gestartet": "iniciado; empezado (starten: iniciar)",
  "gestellt": "puesto; planteado (stellen: poner)",
  "gestern": "ayer",
  "gestiegen": "subido; aumentado (steigen: subir)",
  "gestiegenen": "aumentado; subido",
  "gestrichen": "cancelado; tachado (streichen: cancelar)",
  "gesunken": "bajado; disminuido (sinken: bajar)",
  "getestete": "probado; examinado (testen: probar)",
  "getragen": "llevado; vestido (tragen: llevar)",
  "getroffen": "encontrado; tomado (treffen: encontrar)",
  "gewählter": "elegido; electo",
  "gewann": "ganó (gewinnen: ganar)",
  "gewesen": "sido; estado (sein: ser/estar)",
  "gewinnt": "gana (gewinnen: ganar)",
  "gewonnen": "ganado (gewinnen: ganar)",
  "gezeigt": "mostrado (zeigen: mostrar)",
  "gibt": "da (geben: dar); hay",
  "gilt": "vale; se aplica (gelten: valer)",
  "ging": "fue (gehen: ir)",
  "gingen": "fueron; iban (gehen: ir)",
  "glaube": "creo (glauben: creer)",
  "glaubt": "cree (glauben: creer)",
  "gleis": "vía; andén (das Gleis)",
  "gletscher": "glaciar (der Gletscher)",
  "grammatik": "gramática (die Grammatik)",
  "gremium": "órgano; comité (das Gremium)",
  "grenzen": "fronteras; límites (die Grenzen)",
  "größer": "más grande",
  "größeres": "más grande (neutro)",
  "großmutter": "abuela (die Großmutter)",
  "gruppe": "grupo (die Gruppe)",
  "gut": "bien; bueno",
  "guten": "buenos; buen",
  "gutes": "bueno (neutro)",
  "habe": "tengo/he (haben: tener)",
  "haben": "tener; tenemos/han",
  "hals": "cuello; garganta (der Hals)",
  "hält": "sujeta; mantiene (halten: sujetar/mantener)",
  "halten": "sujetar; mantener; parar",
  "hamburg": "Hamburgo (ciudad)",
  "hände": "manos (die Hände)",
  "handels": "del comercio (der Handel)",
  "händlern": "a los comerciantes (der Händler)",
  "handwerker": "artesano; profesional (der Handwerker)",
  "hängen": "colgar; depender",
  "hängt": "cuelga; depende (hängen)",
  "hast": "tienes (haben: tener)",
  "hat": "tiene/ha (haben: tener)",
  "hatte": "tenía/había (haben)",
  "hätte": "tendría/habría (haben: tener)",
  "hatten": "teníamos/tenían (haben: tener)",
  "hätten": "tendríamos/tendrían (haben: tener)",
  "hättest": "tendrías; habrías (haben: tener)",
  "haus": "casa (das Haus)",
  "hause": "en casa; de la casa (das Haus)",
  "haushalte": "hogares (der Haushalt)",
  "hausordnung": "normas de convivencia (die Hausordnung)",
  "heiße": "me llamo (heißen: llamarse)",
  "heißt": "te llamas; se llama (heißen: llamarse)",
  "helfe": "ayudo (helfen: ayudar)",
  "helfen": "ayudar",
  "helle": "claro; luminosa",
  "herbst": "otoño (der Herbst)",
  "herunterladbar": "descargable",
  "heute": "hoy",
  "hier": "aquí",
  "hilfe": "ayuda (die Hilfe)",
  "hintergrundinformationen": "información de contexto (die Hintergrundinformationen)",
  "historischen": "históricos; históricas",
  "hochschule": "universidad; centro universitario (die Hochschule)",
  "hoffe": "espero (hoffen: esperar)",
  "hofft": "espera (hoffen: esperar)",
  "hofften": "esperaban (hoffen: esperar)",
  "hohen": "alto; elevados",
  "hören": "oír; escuchar",
  "hört": "oye; escucha (hören: escuchar)",
  "hotel": "hotel (das Hotel)",
  "ich": "yo",
  "identität": "identidad (die Identität)",
  "identitätsprüfung": "verificación de identidad (die Identitätsprüfung)",
  "ihn": "lo; a él",
  "ihr": "vosotros/vosotras; su; a ella",
  "ihre": "su; sus; de ella; de ustedes",
  "ihrer": "su",
  "im": "en el (contracción de in dem)",
  "impfstoff": "vacuna (der Impfstoff)",
  "impfungen": "vacunaciones; vacunas (die Impfungen)",
  "in": "en; dentro de; a",
  "informieren": "informar",
  "informiert": "informa; informado (informieren: informar)",
  "initiative": "iniciativa (die Initiative)",
  "innerhalb": "dentro de; en el plazo de",
  "ins": "al interior de; al (contracción de in das)",
  "installiert": "instalado (installieren: instalar)",
  "institut": "instituto; centro (das Institut)",
  "instituten": "a los institutos (das Institut)",
  "interessant": "interesante",
  "interessantes": "interesante (neutro)",
  "interessiere": "me interesa; me intereso (sich interessieren)",
  "interessieren": "interesar; interesarse",
  "interessiert": "interesado; le interesa (interessieren)",
  "internationalen": "internacionales",
  "interne": "interno; interna",
  "ist": "es/está (sein: ser/estar)",
  "jacke": "chaqueta (die Jacke)",
  "jahre": "años (das Jahr)",
  "jahresende": "final de año (das Jahresende)",
  "januar": "enero (der Januar)",
  "je": "cada; cuanto (en je … desto)",
  "jeden": "cada; a cada",
  "jederzeit": "en cualquier momento; siempre",
  "journalistin": "periodista (die Journalistin)",
  "jugendliche": "joven; adolescente (der/die Jugendliche)",
  "jury": "jurado (die Jury)",
  "kaffee": "café (der Kaffee)",
  "kalt": "frío; fría",
  "kam": "vino; llegó (kommen: venir)",
  "kamen": "vinieron; llegaron (kommen: venir)",
  "kandidat": "candidato (der Kandidat)",
  "kann": "puede; sabe (können: poder; saber)",
  "kannst": "puedes; sabes (können: poder/saber)",
  "kannten": "conocían (kennen: conocer)",
  "karte": "mapa; tarjeta (die Karte)",
  "karten": "mapas; tarjetas (die Karten)",
  "käse": "queso (der Käse)",
  "kasse": "caja; taquilla (die Kasse)",
  "katalogisiert": "catalogado (katalogisieren: catalogar)",
  "kaufe": "compro (kaufen: comprar)",
  "kaum": "apenas; casi no",
  "kehrten": "volvieron (kehren: volver)",
  "keine": "ningún; ninguna",
  "keller": "sótano (der Keller)",
  "kenne": "conozco (kennen: conocer)",
  "kennenzulernen": "conocer; llegar a conocer",
  "kenntnisse": "conocimientos (die Kenntnisse)",
  "kind": "niño; hijo (das Kind)",
  "kinder": "niños; hijos (die Kinder)",
  "kino": "cine (das Kino)",
  "kiste": "caja (die Kiste)",
  "klage": "demanda; queja (die Klage)",
  "klang": "sonó; sonido (klingen: sonar)",
  "klare": "claro; clara",
  "klaren": "claros; claras",
  "klarer": "más claro; más claramente",
  "kleine": "pequeño; pequeña",
  "kleinen": "pequeños; pequeñas",
  "klinik": "clínica (die Klinik)",
  "kochen": "cocinar",
  "koffer": "maleta (der Koffer)",
  "kollegin": "compañera de trabajo (die Kollegin)",
  "komme": "vengo (kommen: venir)",
  "kommission": "comisión (die Kommission)",
  "kommt": "viene; llega (kommen: venir)",
  "kompetenzen": "competencias (die Kompetenzen)",
  "kompliziert": "complicado",
  "könne": "pueda (können: poder)",
  "können": "poder; saber",
  "könnten": "podrían (können: poder)",
  "könntest": "podrías (können: poder)",
  "konsequenzen": "consecuencias (die Konsequenzen)",
  "kontrollieren": "controlar; comprobar",
  "kontrolliert": "controla; controlado (kontrollieren)",
  "kontrollierten": "controlaron; controlados",
  "konzert": "concierto (das Konzert)",
  "kopfschmerzen": "dolor de cabeza (die Kopfschmerzen)",
  "korrektur": "corrección (die Korrektur)",
  "kosten": "costar; costes (die Kosten)",
  "kostenlos": "gratis; gratuito",
  "kostet": "cuesta (kosten: costar)",
  "kraft": "fuerza (die Kraft)",
  "krank": "enfermo; enferma",
  "krieg": "guerra (der Krieg)",
  "kriterien": "criterios (die Kriterien)",
  "küche": "cocina (die Küche)",
  "kuchen": "pastel; tarta (der Kuchen)",
  "kümmere": "me ocupo (sich kümmern)",
  "kunde": "cliente (der Kunde)",
  "kunden": "clientes (die Kunden)",
  "kündigen": "cancelar; rescindir; dimitir",
  "kündigt": "cancela; rescinde (kündigen)",
  "kurs": "curso (der Kurs)",
  "kurze": "corto; breve",
  "kürzer": "más corto; más breve",
  "kurzfristig": "a corto plazo; con poca antelación",
  "kürzlich": "recientemente; hace poco",
  "küstennähe": "proximidad a la costa (die Küstennähe)",
  "labor": "laboratorio (das Labor)",
  "laden": "tienda (der Laden); cargar",
  "lage": "situación; ubicación (die Lage)",
  "lampe": "lámpara (die Lampe)",
  "lampen": "lámparas (die Lampen)",
  "land": "país; tierra (das Land)",
  "ländern": "en los países (das Land)",
  "lange": "largo; durante mucho tiempo",
  "langen": "alcanzar; largos",
  "langer": "largo (masculino)",
  "länger": "más largo; más tiempo",
  "langfristig": "a largo plazo",
  "lärm": "ruido (der Lärm)",
  "las": "leyó (lesen: leer)",
  "lassen": "dejar; permitir",
  "lässt": "deja; permite (lassen)",
  "lauf": "carrera; curso (der Lauf)",
  "laut": "ruidoso; según",
  "leben": "vivir; vida (das Leben)",
  "lebt": "vive (leben: vivir)",
  "legen": "poner; colocar",
  "lehrmethoden": "métodos de enseñanza (die Lehrmethoden)",
  "lehrplan": "plan de estudios (der Lehrplan)",
  "leicht": "fácil; ligero",
  "leichter": "más fácil; más ligero",
  "leistete": "prestó; realizó (leisten)",
  "leitete": "dirigió (leiten: dirigir)",
  "leitung": "dirección; gestión (die Leitung)",
  "lerne": "aprendo (lernen: aprender)",
  "lernen": "aprender; estudiar",
  "lernplätze": "plazas de estudio (die Lernplätze)",
  "lernt": "aprende (lernen: aprender)",
  "lernte": "aprendió; aprendía (lernen: aprender)",
  "lernzeit": "tiempo de estudio (die Lernzeit)",
  "lese": "leo (lesen: leer)",
  "lesen": "leer",
  "lesung": "lectura pública; conferencia (die Lesung)",
  "lieferte": "entregó; suministró (liefern)",
  "lieferung": "entrega; envío (die Lieferung)",
  "liegt": "está; se encuentra (liegen)",
  "liest": "lee (lesen: leer)",
  "lokale": "local; locales",
  "lópez": "López (apellido)",
  "losfahren": "ponerse en marcha; salir",
  "lösung": "solución (die Lösung)",
  "luftqualität": "calidad del aire (die Luftqualität)",
  "luis": "Luis (nombre propio)",
  "mache": "hago (machen: hacer)",
  "machen": "hacer",
  "machst": "haces (machen: hacer)",
  "macht": "hace; hacéis (machen: hacer)",
  "mag": "le gusta; puede que (mögen: gustar)",
  "magst": "te gusta (mögen: gustar)",
  "mai": "mayo (der Mai)",
  "mann": "hombre; marido (der Mann)",
  "mantel": "abrigo (der Mantel)",
  "maría": "María (nombre propio)",
  "markt": "mercado (der Markt)",
  "masse": "masa; cantidad (die Masse)",
  "meer": "mar (das Meer)",
  "mehr": "más",
  "mehrere": "varios; varias",
  "mehreren": "varios; varias (declinado)",
  "mein": "mi; mío",
  "meine": "mi; mis",
  "meinem": "a mi; de mi (dativo)",
  "meinen": "mi; mis",
  "meiner": "mi; mía; de mi",
  "meinung": "opinión (die Meinung)",
  "meldet": "comunica; informa (melden: comunicar)",
  "meldung": "noticia; aviso (die Meldung)",
  "menschen": "personas; seres humanos (die Menschen)",
  "messe": "feria; exposición (die Messe)",
  "messstationen": "estaciones de medición (die Messstationen)",
  "messwerte": "valores medidos (die Messwerte)",
  "methode": "método (die Methode)",
  "mich": "me; a mí",
  "miete": "alquiler (die Miete)",
  "milder": "más suave; más templado",
  "minister": "ministro (der Minister)",
  "ministerin": "ministra (die Ministerin)",
  "mir": "me; a mí",
  "mit": "con; mediante",
  "mitarbeitenden": "personal; empleados (die Mitarbeitenden)",
  "mitkommen": "venir con alguien; acompañar",
  "mittel": "medio; remedio (das Mittel)",
  "möchte": "quisiera; me gustaría (mögen: gustar)",
  "möchten": "querríamos; nos gustaría (mögen)",
  "möchtet": "os gustaría; queréis (mögen)",
  "moderatorin": "presentadora (die Moderatorin)",
  "möglich": "posible",
  "monatlich": "mensual; cada mes",
  "monatsende": "final de mes (das Monatsende)",
  "montag": "lunes (der Montag)",
  "morgen": "mañana; mañana por la mañana (der Morgen)",
  "müll": "basura (der Müll)",
  "museum": "museo (das Museum)",
  "musik": "música (die Musik)",
  "muss": "tiene que (müssen: tener que)",
  "müssen": "tener que (müssen)",
  "musst": "tener que (müssen: tener que)",
  "musste": "tuvo que (müssen: tener que)",
  "müsste": "tendría que (müssen: tener que)",
  "muster": "modelo; muestra; estampado (das Muster)",
  "mutter": "madre (die Mutter)",
  "nach": "después de; hacia; según",
  "nachbar": "vecino (der Nachbar)",
  "nachdem": "después de que",
  "nachdenken": "reflexionar; pensar",
  "nachfragt": "pregunta; pide aclaraciones (nachfragen)",
  "nachricht": "mensaje; noticia (die Nachricht)",
  "nächste": "siguiente; próximo",
  "nächsten": "siguiente; próximo",
  "nächster": "siguiente; próximo (masculino)",
  "nachweisbar": "demostrable; verificable",
  "nahm": "tomó; cogió (nehmen: tomar)",
  "nahmen": "tomaron; cogieron (nehmen: tomar)",
  "nähmen": "tomarían; cogerían (nehmen: tomar)",
  "naturschutz": "protección de la naturaleza (der Naturschutz)",
  "neben": "junto a; además de",
  "nebenkosten": "gastos adicionales (die Nebenkosten)",
  "nehme": "tomo; cojo (nehmen: tomar)",
  "nehmen": "tomar; coger",
  "nennt": "llama; menciona (nennen)",
  "neu": "nuevo; de nuevo",
  "neue": "nuevo; nueva",
  "neuen": "nuevos; nuevas",
  "neuer": "nuevo (masculino)",
  "neun": "nueve",
  "nicht": "no",
  "nichteinhaltung": "incumplimiento (die Nichteinhaltung)",
  "nie": "nunca",
  "noch": "todavía; aún; además",
  "nominierten": "nominados; nominadas (die Nominierten)",
  "normalbereich": "rango normal (der Normalbereich)",
  "notdienst": "servicio de urgencias (der Notdienst)",
  "notwendig": "necesario",
  "nun": "ahora; pues",
  "nur": "solo; solamente",
  "nutzen": "usar; aprovechar",
  "nutzerfeedback": "comentarios de usuarios (das Nutzerfeedback)",
  "nutzten": "usaron; utilizaron (nutzen)",
  "nutzung": "uso; utilización (die Nutzung)",
  "ob": "si; si acaso",
  "obwohl": "aunque",
  "offen": "abierto; abierto al público",
  "offene": "abierto; abierta",
  "öffentlich": "público; públicamente",
  "öffentlicher": "público (masculino)",
  "öffnen": "abrir",
  "öffnet": "abre (öffnen: abrir)",
  "öfter": "más a menudo",
  "ohne": "sin",
  "onkel": "tío (der Onkel)",
  "online": "en línea; por internet",
  "onlineformular": "formulario en línea (das Onlineformular)",
  "österreich": "Austria",
  "pablo": "Pablo (nombre propio)",
  "paket": "paquete (das Paket)",
  "paris": "París (ciudad)",
  "park": "parque (der Park)",
  "parteien": "partidos; partes (die Parteien)",
  "passt": "encaja; queda bien (passen)",
  "patient": "paciente (der Patient)",
  "pause": "pausa; descanso (die Pause)",
  "per": "por; mediante",
  "personalengpass": "falta de personal (der Personalengpass)",
  "personen": "personas (die Personen)",
  "personenbezogener": "personal; relativo a personas",
  "persönliche": "personal; propia",
  "pfleger": "cuidador; enfermero (der Pfleger)",
  "pizza": "pizza (die Pizza)",
  "plan": "plan (der Plan)",
  "pläne": "planes (die Pläne)",
  "planmäßig": "según lo previsto; programado",
  "plätze": "plazas; sitios (die Plätze)",
  "plötzlich": "de repente",
  "podcast": "pódcast (der Podcast)",
  "politische": "político; política",
  "polizei": "policía (die Polizei)",
  "portals": "del portal (das Portal)",
  "praktikum": "prácticas; período de prácticas (das Praktikum)",
  "praktischer": "más práctico; práctico (masculino)",
  "präparat": "preparado; medicamento (das Präparat)",
  "präsentation": "presentación (die Präsentation)",
  "präsentieren": "presentar",
  "praxen": "consultas; clínicas (die Praxen)",
  "praxis": "consulta; práctica (die Praxis)",
  "präzise": "preciso; exactamente",
  "preis": "precio (der Preis)",
  "preise": "precios (die Preise)",
  "preiserhöhung": "subida de precios (die Preiserhöhung)",
  "problemlos": "sin problemas; fácilmente",
  "produkt": "producto (das Produkt)",
  "produzierte": "produjo (produzieren: producir)",
  "produzierten": "produjeron; producidos (produzieren)",
  "prognose": "pronóstico; previsión (die Prognose)",
  "programm": "programa (das Programm)",
  "programms": "del programa (das Programm)",
  "projekt": "proyecto (das Projekt)",
  "prüfung": "examen; prueba (die Prüfung)",
  "pullover": "jersey (der Pullover)",
  "pünktlich": "puntual; a tiempo",
  "quellen": "fuentes (die Quellen)",
  "radio": "radio (das Radio)",
  "radwegenetz": "red de carriles bici (das Radwegenetz)",
  "rahmenbedingungen": "condiciones marco (die Rahmenbedingungen)",
  "rasch": "rápido; rápidamente",
  "rat": "consejo (der Rat)",
  "raum": "habitación; espacio (der Raum)",
  "reagiert": "reacciona (reagieren: reaccionar)",
  "recherche": "investigación; búsqueda (die Recherche)",
  "rechnung": "cuenta; factura (die Rechnung)",
  "rechtzeitig": "a tiempo; con antelación",
  "redaktion": "redacción (die Redaktion)",
  "rede": "discurso (die Rede)",
  "reform": "reforma (die Reform)",
  "regeln": "reglas; normas (die Regeln)",
  "regen": "lluvia (der Regen)",
  "regenwasser": "agua de lluvia (das Regenwasser)",
  "regierung": "gobierno (die Regierung)",
  "registrierung": "registro; inscripción (die Registrierung)",
  "regnet": "llueve (regnen: llover)",
  "regulieren": "regular",
  "reise": "viaje (die Reise)",
  "rekord": "récord (der Rekord)",
  "renaturierung": "renaturalización (die Renaturierung)",
  "repariert": "reparado; repara (reparieren)",
  "ressourcen": "recursos (die Ressourcen)",
  "restaurierten": "restauraron; restaurado (restaurieren)",
  "richtig": "correcto; correctamente",
  "rock": "falda (der Rock)",
  "rohre": "tuberías (die Rohre)",
  "rot": "rojo",
  "rote": "rojo; roja",
  "roten": "rojos; rojas",
  "rücken": "espalda (der Rücken)",
  "rückgang": "descenso; disminución (der Rückgang)",
  "rückmeldung": "respuesta; comentarios (die Rückmeldung)",
  "rucksack": "mochila (der Rucksack)",
  "rücktritt": "dimisión; renuncia (der Rücktritt)",
  "ruf": "llamada; reputación (der Ruf)",
  "ruhe": "tranquilidad; descanso (die Ruhe)",
  "ruhig": "tranquilo; tranquilamente",
  "sagen": "decir",
  "sagt": "dice (sagen: decir)",
  "salat": "ensalada (der Salat)",
  "sammeln": "recopilar; coleccionar",
  "samstag": "sábado (der Samstag)",
  "saniert": "rehabilitado; renovado (sanieren)",
  "schaden": "daño (der Schaden); perjudicar",
  "schadens": "del daño (der Schaden)",
  "schadstoffe": "contaminantes (die Schadstoffe)",
  "schaffe": "consigo; hago (schaffen: conseguir)",
  "schafft": "consigue; logra (schaffen: conseguir)",
  "schalter": "mostrador; ventanilla (der Schalter)",
  "schauspielerin": "actriz (die Schauspielerin)",
  "scheint": "parece; brilla (scheinen)",
  "schläft": "duerme (schlafen: dormir)",
  "schlafzimmer": "dormitorio (das Schlafzimmer)",
  "schlecht": "malo; mal",
  "schluss": "final; conclusión (der Schluss)",
  "schlüssel": "llave (der Schlüssel)",
  "schnell": "rápido; rápidamente",
  "schnelle": "rápido; rápida",
  "schneller": "más rápido; más rápidamente",
  "schokolade": "chocolate (die Schokolade)",
  "schon": "ya",
  "schön": "bonito; bonito/a",
  "schreiben": "escribir",
  "schreibtisch": "escritorio (der Schreibtisch)",
  "schritten": "pasos (der Schritt)",
  "schuhe": "zapatos (die Schuhe)",
  "schutz": "protección (der Schutz)",
  "schützen": "proteger",
  "schutzstreifen": "carril de protección (der Schutzstreifen)",
  "schützt": "protege (schützen: proteger)",
  "schwarze": "negro; negra",
  "schwester": "hermana (die Schwester)",
  "schwestern": "hermanas (die Schwestern)",
  "see": "lago (der See); mar (die See)",
  "sehr": "muy",
  "sei": "sea (sein: ser/estar)",
  "seien": "sean (sein: ser/estar)",
  "sein": "ser; estar; su (posesivo)",
  "seine": "su; sus (de él)",
  "seiner": "su; de él",
  "seit": "desde; desde hace",
  "selbst": "mismo; por sí mismo",
  "selbstständig": "autónomo; por cuenta propia",
  "seltene": "raro; poco frecuente",
  "seltener": "más raro; con menor frecuencia",
  "sender": "emisora; canal (der Sender)",
  "sendung": "programa; emisión (die Sendung)",
  "senkt": "reduce; baja (senken: reducir)",
  "senkte": "redujo; bajó (senken: reducir)",
  "sensible": "sensible; delicado",
  "setzen": "poner; sentar",
  "setzt": "pone; sienta (setzen)",
  "setzte": "puso; sentó (setzen)",
  "sevilla": "Sevilla (ciudad)",
  "sich": "se; a sí mismo/a",
  "sicher": "seguro; seguramente",
  "sicherung": "seguridad; fusible (die Sicherung)",
  "sichtbar": "visible",
  "sie": "ella; ellos/ellas; usted",
  "sieben": "siete",
  "sind": "somos/son/estamos (sein: ser/estar)",
  "sinke": "bajo; disminuyo (sinken: bajar)",
  "sinnvoll": "sensato; útil",
  "sitzung": "reunión; sesión (die Sitzung)",
  "sofort": "inmediatamente; enseguida",
  "software": "software (die Software)",
  "solaranlage": "instalación solar (die Solaranlage)",
  "soll": "debe; se dice que (sollen: deber)",
  "sollen": "deber; se dice que (sollen)",
  "sollte": "debería; debía (sollen: deber)",
  "sommer": "verano (der Sommer)",
  "sondern": "sino",
  "sonne": "sol (die Sonne)",
  "sorgfältig": "cuidadosamente; minucioso",
  "sowohl": "tanto (en sowohl … als auch)",
  "spanien": "España",
  "spannender": "más emocionante",
  "spannendes": "emocionante (neutro)",
  "sparen": "ahorrar",
  "spart": "ahorra (sparen: ahorrar)",
  "spät": "tarde",
  "später": "más tarde; posterior",
  "spazieren": "pasear",
  "speichern": "guardar; almacenar",
  "spiel": "juego (das Spiel)",
  "spiele": "juegos (die Spiele); juego (spielen)",
  "spielt": "juega (spielen: jugar)",
  "sprachen": "hablaron (sprechen: hablar)",
  "sprechen": "hablar",
  "sprecher": "portavoz (der Sprecher)",
  "sprecherin": "portavoz (die Sprecherin)",
  "spricht": "habla (sprechen: hablar)",
  "stadt": "ciudad (die Stadt)",
  "stadtarchiv": "archivo municipal (das Stadtarchiv)",
  "stadtrand": "afueras; periferia (der Stadtrand)",
  "stand": "estaba; se puso de pie (stehen: estar de pie)",
  "standard": "norma; estándar (der Standard)",
  "standen": "estaban; se pusieron de pie (stehen)",
  "standort": "ubicación; sede (der Standort)",
  "starke": "fuerte; intenso (femenino)",
  "statt": "en vez de; en lugar de",
  "stattfindet": "tiene lugar (stattfinden: celebrarse)",
  "stehe": "estoy de pie (stehen)",
  "stehen": "estar de pie; estar situado",
  "steht": "está; se encuentra (stehen)",
  "steigen": "subir; aumentar",
  "steigende": "creciente; en aumento",
  "stelle": "puesto; lugar (die Stelle)",
  "stellen": "poner; colocar; plantear",
  "stellt": "pone; plantea (stellen)",
  "stellte": "puso; planteó (stellen)",
  "steuerreform": "reforma fiscal (die Steuerreform)",
  "stimmt": "es correcto; vota (stimmen)",
  "stimmte": "era correcto; votó (stimmen)",
  "stoppte": "paró; detuvo (stoppen)",
  "straße": "calle (die Straße)",
  "strom": "electricidad; corriente (der Strom)",
  "studentin": "estudiante (die Studentin)",
  "studie": "estudio; investigación (die Studie)",
  "studierenden": "estudiantes (die Studierenden)",
  "studiert": "estudia; estudió (studieren: estudiar)",
  "stunde": "hora (die Stunde)",
  "stunden": "horas (die Stunden)",
  "sturms": "de la tormenta (der Sturm)",
  "stürmt": "hay tormenta; sopla con fuerza (stürmen)",
  "suche": "busco (suchen: buscar)",
  "suchen": "buscar",
  "sucht": "busca (suchen: buscar)",
  "supermarkt": "supermercado (der Supermarkt)",
  "suppe": "sopa (die Suppe)",
  "system": "sistema (das System)",
  "systems": "del sistema (das System)",
  "tag": "día (der Tag)",
  "tagen": "días (die Tage); reunirse (tagen)",
  "täglich": "a diario; diario",
  "tante": "tía (die Tante)",
  "tasche": "bolso; bolsa (die Tasche)",
  "team": "equipo (das Team)",
  "techniker": "técnico (der Techniker)",
  "tee": "té (der Tee)",
  "teil": "parte; pieza (der Teil)",
  "teilnahme": "participación (die Teilnahme)",
  "teilnehme": "participo (teilnehmen: participar)",
  "teilnehmenden": "participantes (die Teilnehmenden)",
  "teilt": "comparte; divide (teilen)",
  "temperaturdaten": "datos de temperatura (die Temperaturdaten)",
  "temperaturen": "temperaturas (die Temperaturen)",
  "termin": "cita; fecha (der Termin)",
  "tests": "pruebas (die Tests)",
  "text": "texto (der Text)",
  "thema": "tema (das Thema)",
  "therapie": "terapia (die Therapie)",
  "therapien": "terapias (die Therapien)",
  "tickets": "billetes; entradas (die Tickets)",
  "tisch": "mesa (der Tisch)",
  "tochter": "hija (die Tochter)",
  "trage": "llevo; transporto (tragen: llevar)",
  "tragen": "llevar; transportar",
  "trägt": "lleva; viste (tragen)",
  "treffen": "encontrar; quedar",
  "trend": "tendencia (der Trend)",
  "trennen": "separar",
  "treppenhaus": "escalera; hueco de escalera (das Treppenhaus)",
  "trinken": "beber",
  "trotz": "a pesar de",
  "tür": "puerta (die Tür)",
  "tut": "hace (tun: hacer)",
  "über": "sobre; por encima de; más de; acerca de",
  "überflutet": "inundado (überfluten: inundar)",
  "übergeben": "entregar; transmitir",
  "übermittlung": "transmisión; envío (die Übermittlung)",
  "übernahm": "asumió; se hizo cargo (übernehmen)",
  "übernimmt": "asume; se hace cargo (übernehmen)",
  "überraschte": "sorprendió (überraschen: sorprender)",
  "übertragen": "transmitir; transferir",
  "übst": "practicas (üben: practicar)",
  "übung": "ejercicio; práctica (die Übung)",
  "uhr": "reloj; hora (die Uhr)",
  "um": "a; alrededor de; para",
  "umbau": "reforma; remodelación (der Umbau)",
  "umfrage": "encuesta (die Umfrage)",
  "umgeleitet": "desviado; redirigido (umleiten)",
  "umsätze": "volumen de ventas; ventas (die Umsätze)",
  "umsetzung": "aplicación; puesta en práctica (die Umsetzung)",
  "umzieht": "se muda (umziehen)",
  "umzugehen": "gestionar; tratar con",
  "unabhängigen": "independientes",
  "und": "y",
  "universität": "universidad (die Universität)",
  "uns": "nos; a nosotros/as",
  "unter": "debajo de; entre",
  "unterlagen": "documentos; documentación (die Unterlagen)",
  "unternehmen": "empresa (das Unternehmen); emprender",
  "unterschiede": "diferencias (die Unterschiede)",
  "unterschreiben": "firmar",
  "unterschrift": "firma (die Unterschrift)",
  "unterstützen": "apoyar",
  "untersucht": "examina; investigado (untersuchen)",
  "untersuchte": "examinó; investigó (untersuchen)",
  "untersuchung": "examen; investigación (die Untersuchung)",
  "unterzeichnung": "firma; suscripción (die Unterzeichnung)",
  "unverträglichkeit": "intolerancia (die Unverträglichkeit)",
  "urlaub": "vacaciones (der Urlaub)",
  "ursache": "causa (die Ursache)",
  "variante": "variante; opción (die Variante)",
  "veränderbar": "modificable; alterable",
  "veränderte": "cambió; modificado (verändern: cambiar)",
  "veränderter": "modificado; alterado",
  "veränderungen": "cambios; modificaciones (die Veränderungen)",
  "verantwortliche": "responsable; persona responsable",
  "verantwortung": "responsabilidad (die Verantwortung)",
  "verarbeitet": "procesa; procesado (verarbeiten)",
  "verband": "asociación; federación (der Verband)",
  "verbessert": "mejora; mejorado (verbessern)",
  "verbesserte": "mejoró; mejorado (verbessern)",
  "verbessertes": "mejorado (neutro)",
  "verbrauchen": "consumir",
  "verbreitete": "difundió; extendido (verbreiten)",
  "verfahren": "procedimiento (das Verfahren); proceder",
  "verfügt": "dispone (verfügen: disponer)",
  "verfügung": "disposición (die Verfügung)",
  "vergessen": "olvidar; olvidado",
  "vergleich": "comparación (der Vergleich)",
  "verkauft": "vende; vendido (verkaufen: vender)",
  "verkehr": "tráfico; circulación (der Verkehr)",
  "verlag": "editorial (der Verlag)",
  "verlängern": "alargar; prorrogar",
  "verlängert": "prolonga; prorrogado (verlängern)",
  "verlängerung": "prórroga; prolongación (die Verlängerung)",
  "verlassen": "dejar; abandonar",
  "verlässliche": "fiable; fiable (femenino)",
  "verlaufe": "transcurro; transcurra (verlaufen)",
  "verliert": "pierde (verlieren: perder)",
  "verließen": "abandonaron (verlassen: abandonar)",
  "vermeiden": "evitar",
  "vermeidung": "prevención; evitación (die Vermeidung)",
  "vermieter": "arrendador; casero (der Vermieter)",
  "vermittlung": "mediación; gestión (die Vermittlung)",
  "veröffentlichen": "publicar",
  "veröffentlicht": "publica; publicado (veröffentlichen)",
  "veröffentlichte": "publicó (veröffentlichen: publicar)",
  "verringert": "reduce; reducido (verringern)",
  "verringerung": "reducción (die Verringerung)",
  "verschickt": "envía; enviado (verschicken)",
  "verschieben": "aplazar; posponer",
  "verschoben": "aplazado; pospuesto (verschieben)",
  "versichert": "asegurado; afirma (versichern)",
  "versicherung": "seguro (die Versicherung)",
  "versiegelten": "sellado; precintado (versiegeln)",
  "versorgung": "suministro; atención (die Versorgung)",
  "verspäteten": "retrasado; tardío",
  "verspätung": "retraso (die Verspätung)",
  "verständigt": "avisa; informado (verständigen)",
  "versuch": "intento (der Versuch)",
  "versuche": "intento (der Versuch); intento (versuchen)",
  "vertrag": "contrato (der Vertrag)",
  "vertragen": "tolerar; soportar",
  "vertrags": "del contrato (der Vertrag)",
  "vertraue": "confío (vertrauen: confiar)",
  "vertraulich": "confidencial",
  "vertraulicher": "más confidencial",
  "vertritt": "representa (vertreten: representar)",
  "verwaltung": "administración (die Verwaltung)",
  "verwaltungskosten": "gastos administrativos (die Verwaltungskosten)",
  "verwechslung": "confusión; equivocación (die Verwechslung)",
  "verzögerung": "retraso; demora (die Verzögerung)",
  "viel": "mucho; mucha",
  "viele": "muchos; muchas",
  "vierzig": "cuarenta",
  "vögel": "pájaros; aves (die Vögel)",
  "vom": "del; de la (contracción de von dem)",
  "von": "de; por",
  "vor": "delante de; antes de; partícula separable",
  "voraus": "por adelantado; delante",
  "voraussetzungen": "requisitos; condiciones previas (die Voraussetzungen)",
  "vorbei": "pasado; de largo",
  "vorbildern": "modelos de referencia (die Vorbilder)",
  "vorfall": "incidente (der Vorfall)",
  "vorgelegt": "presentado (vorlegen: presentar)",
  "vorgeschrieben": "prescrito; obligatorio (vorschreiben)",
  "vorgesehen": "previsto; contemplado (vorsehen)",
  "vorjahr": "año anterior (das Vorjahr)",
  "vormittag": "mañana (antes del mediodía) (der Vormittag)",
  "vorschlag": "propuesta (der Vorschlag)",
  "vorzeitig": "prematuro; antes de tiempo",
  "vorzulegen": "presentar; entregar",
  "wahlbeteiligung": "participación electoral (die Wahlbeteiligung)",
  "während": "durante; mientras",
  "wand": "pared (die Wand)",
  "war": "era/estaba/fue (sein: ser/estar)",
  "wäre": "sería/estaría (sein: ser/estar)",
  "waren": "éramos/eran/estábamos (sein: ser/estar)",
  "wären": "seríamos/serían (sein: ser/estar)",
  "warm": "caliente; cálido",
  "warnung": "aviso; advertencia (die Warnung)",
  "warten": "esperar",
  "wartet": "espera (warten: esperar)",
  "wartete": "esperó; esperaba (warten: esperar)",
  "warteten": "esperaron; esperaban (warten: esperar)",
  "warum": "por qué",
  "wasche": "lavo (waschen: lavar)",
  "wäscht": "lava (waschen: lavar)",
  "wasser": "agua (das Wasser)",
  "wasserschaden": "daños por agua (der Wasserschaden)",
  "wasserverbrauch": "consumo de agua (der Wasserverbrauch)",
  "wechseln": "cambiar",
  "weder": "ni (en weder … noch)",
  "weg": "camino; vía (der Weg)",
  "wegen": "a causa de; debido a",
  "weh": "dolor; doler",
  "weil": "porque",
  "weiß": "blanco; sabe (wissen: saber)",
  "weit": "lejos; amplio",
  "weiter": "más; adelante; continuar",
  "weiterbildung": "formación continua (die Weiterbildung)",
  "weitere": "adicional; otros; otras",
  "weiterer": "adicional; otro más",
  "weitergegeben": "transmitido; compartido (weitergeben)",
  "wenig": "poco; poca",
  "weniger": "menos",
  "wenn": "si; cuando",
  "werde": "me convierto; seré (werden)",
  "werden": "convertirse; ser (auxiliar)",
  "werdet": "os convertís; seréis (werden)",
  "werkstatt": "taller (die Werkstatt)",
  "werte": "valores (die Werte)",
  "wetter": "tiempo; clima (das Wetter)",
  "wetters": "del tiempo; del clima (das Wetter)",
  "wichtige": "importante",
  "wichtigen": "importantes",
  "wichtigste": "más importante",
  "widersprechen": "contradecir",
  "wie": "cómo; qué; como",
  "wieder": "de nuevo; otra vez",
  "wiederherstellen": "restablecer; restaurar",
  "wiederholen": "repetir",
  "wiederholt": "repite; repetido (wiederholen)",
  "will": "quiere; afirma que (wollen: querer)",
  "wir": "nosotros; nosotras",
  "wird": "se vuelve; será (werden: convertirse)",
  "wirke": "parezco; actúo (wirken)",
  "wirken": "parecer; actuar; surtir efecto",
  "wirkt": "parece; surte efecto (wirken)",
  "wirst": "te conviertes; serás (werden)",
  "wissen": "saber",
  "wo": "dónde",
  "woche": "semana (die Woche)",
  "wochen": "semanas (die Wochen)",
  "wochenende": "fin de semana (das Wochenende)",
  "wohne": "vivo (wohnen: vivir)",
  "wohnen": "vivir; residir",
  "wohnt": "vive (wohnen: vivir)",
  "wohnung": "piso; apartamento (die Wohnung)",
  "wohnungen": "pisos; apartamentos (die Wohnungen)",
  "wollt": "queréis (wollen: querer)",
  "worden": "sido; convertido (werden; auxiliar pasivo)",
  "wurde": "se convirtió; fue (werden: convertirse)",
  "würde": "haría; sería (werden: convertirse)",
  "würden": "harían; serían (werden: convertirse)",
  "wussten": "sabían; sabíamos (wissen: saber)",
  "zahl": "número (die Zahl)",
  "zahlen": "pagar; números (die Zahlen)",
  "zahlt": "paga (zahlen: pagar)",
  "zahlungsfristen": "plazos de pago (die Zahlungsfristen)",
  "zehn": "diez",
  "zeigen": "mostrar; enseñar",
  "zeigt": "muestra; enseña (zeigen: mostrar)",
  "zeit": "tiempo (die Zeit)",
  "zeitplan": "horario; calendario (der Zeitplan)",
  "zeitung": "periódico (die Zeitung)",
  "zentral": "central",
  "zertifikat": "certificado (das Zertifikat)",
  "zeuge": "testigo (der Zeuge)",
  "zeugin": "testigo (die Zeugin)",
  "zeugnisse": "certificados; expedientes (die Zeugnisse)",
  "ziehen": "tirar; mudarse",
  "ziel": "objetivo; meta (das Ziel)",
  "zimmer": "habitación (das Zimmer)",
  "zog": "tiró; se mudó (ziehen)",
  "zu": "a; hacia; demasiado; partícula de infinitivo",
  "zubereitet": "preparado; cocinado (zubereiten)",
  "zucker": "azúcar (der Zucker)",
  "zuerst": "primero; al principio",
  "zug": "tren; corriente (der Zug)",
  "zum": "al; para el (contracción de zu dem)",
  "zunächst": "primero; en primer lugar",
  "zur": "a la; para la (contracción de zu der)",
  "zurück": "de vuelta; atrás; partícula separable",
  "zurückgehen": "volver; disminuir",
  "zurückkam": "volvió (zurückkommen: volver)",
  "zurückweisung": "rechazo; denegación (die Zurückweisung)",
  "zusammenarbeit": "colaboración (die Zusammenarbeit)",
  "zusammengefasst": "resumido (zusammenfassen: resumir)",
  "zusatzkosten": "costes adicionales (die Zusatzkosten)",
  "zusätzliche": "adicional; adicionalmente",
  "zustellung": "entrega; reparto (die Zustellung)",
  "zuverlässig": "fiable; de confianza",
  "zwar": "ciertamente; si bien",
  "zwei": "dos",
  "zweite": "segundo; segunda",
};
