import type { LessonDraft, Phrase, UnitDraft } from "./units";

const phrase = (
  german: string,
  spanish: string,
  blankWord: string,
  explanation: string,
  spanishAlt?: string[],
  germanAlt?: string[],
): Phrase => ({
  german,
  spanish,
  blankWord,
  explanation,
  ...(spanishAlt ? { spanishAlt } : {}),
  ...(germanAlt ? { germanAlt } : {}),
});

const lesson = (
  id: string,
  order: number,
  title: string,
  description: string,
  phrases: Phrase[],
): LessonDraft => ({
  id,
  order,
  title,
  description,
  xpReward: 10,
  phrases,
});

const unit = (
  id: string,
  order: number,
  title: string,
  description: string,
  lessons: LessonDraft[],
): UnitDraft => ({
  id,
  order,
  title,
  description,
  color: "#A560E8",
  cefrLevel: "B1.1",
  lessons,
});

export const b1_1UnitDrafts: UnitDraft[] = [
  unit("u25", 25, "Trabajo y proyectos", "Cuenta experiencias laborales y explica decisiones.", [
    lesson("u25-l1", 1, "Historias del trabajo", "Usa el Präteritum para hablar de situaciones pasadas.", [
      phrase("Früher arbeitete ich in einer kleinen Firma.", "Antes trabajaba en una empresa pequeña.", "Früher", "El Präteritum de arbeiten es arbeitete.", ["Antes trabajé en una empresa pequeña."]),
      phrase("Der Chef war gestern im Büro.", "Ayer el jefe estaba en la oficina.", "Chef", "war es el Präteritum de sein.", ["El jefe estuvo ayer en la oficina."]),
      phrase("Wir hatten am Montag eine wichtige Sitzung.", "El lunes tuvimos una reunión importante.", "Sitzung", "hatten es el Präteritum de haben.", ["El lunes teníamos una reunión importante."]),
      phrase("Sie schrieb den Bericht am Abend.", "Ella escribió el informe por la tarde.", "schrieb", "schreiben tiene el Präteritum irregular schrieb.", ["Por la tarde redactó el informe."]),
      phrase("Die Kollegen kamen zu spät.", "Los compañeros llegaron tarde.", "Kollegen", "kamen es el Präteritum de kommen.", ["Los compañeros vinieron demasiado tarde."]),
      phrase("Ich musste den Termin verschieben.", "Tuve que aplazar la cita.", "musste", "musste es el Präteritum de müssen y el infinitivo va al final.", ["Tenía que aplazar la cita."]),
    ]),
    lesson("u25-l2", 2, "Explicar lo ocurrido", "Combina subordinadas de causa, tiempo y condición.", [
      phrase("Obwohl es spät war, beendeten wir die Präsentation.", "Aunque era tarde, terminamos la presentación.", "spät", "obwohl introduce una subordinada y el verbo war va al final.", ["Aunque era tarde, acabamos la presentación."]),
      phrase("Ich blieb zu Hause, weil ich krank war.", "Me quedé en casa porque estaba enfermo.", "blieb", "blieb es el Präteritum de bleiben y weil coloca war al final.", ["Me quedé en casa porque estaba enferma."]),
      phrase("Wenn der Kunde anruft, erklärt sie den Ablauf.", "Si llama el cliente, ella explica el proceso.", "Kunde", "En la subordinada con wenn, anruft va al final y la principal empieza con erklärt.", ["Cuando llama el cliente, ella explica el proceso."]),
      phrase("Er sagte, dass die Lieferung morgen eintrifft.", "Dijo que el pedido llega mañana.", "sagte", "sagte es el Präteritum de sagen y eintrifft cierra la subordinada con dass.", ["Dijo que el envío llegará mañana."]),
      phrase("Wir wissen nicht, ob der Raum frei ist.", "No sabemos si la sala está libre.", "Raum", "ob introduce una pregunta indirecta y ist va al final.", ["No sabemos si la habitación está disponible."]),
      phrase("Nachdem die Sitzung endete, gingen alle nach Hause.", "Después de que terminara la reunión, todos se fueron a casa.", "endete", "Nachdem introduce una subordinada temporal con el verbo al final.", ["Cuando terminó la reunión, todos se marcharon."]),
    ]),
    lesson("u25-l3", 3, "Opiniones sobre un proyecto", "Expresa opiniones y condiciones en una conversación laboral.", [
      phrase("Ich dachte, dass der Vorschlag sinnvoll ist.", "Pensaba que la propuesta era razonable.", "dachte", "dachte es el Präteritum irregular de denken y la subordinada termina en ist.", ["Creía que la propuesta tenía sentido."]),
      phrase("Sie meinte, dass die Aufgabe zu schwierig ist.", "Ella opinaba que la tarea era demasiado difícil.", "meinte", "meinen forma el Präteritum meinte y dass introduce la opinión.", ["Pensaba que el ejercicio era demasiado difícil."]),
      phrase("Obwohl der Plan gut klang, änderten wir ihn.", "Aunque el plan sonaba bien, lo cambiamos.", "klang", "klang es el Präteritum de klingen y obwohl coloca el verbo al final.", ["Aunque el plan parecía bueno, lo modificamos."]),
      phrase("Wenn du möchtest, besprechen wir die Details.", "Si quieres, comentamos los detalles.", "möchtest", "La subordinada con wenn termina en möchtest y la principal empieza con besprechen.", ["Si te apetece, hablamos de los detalles."]),
      phrase("Der Leiter erklärte, warum die Frist abläuft.", "El responsable explicó por qué vence el plazo.", "Leiter", "warum introduce una pregunta indirecta y abläuft cierra la subordinada.", ["El encargado explicó por qué termina el plazo."]),
      phrase("Wir hofften, dass das Team pünktlich ankommt.", "Esperábamos que el equipo llegara puntual.", "hofften", "hofften es el Präteritum de hoffen; la subordinada con dass acaba en ankommt.", ["Esperábamos que el equipo llegase a tiempo."]),
    ]),
  ]),
  unit("u26", 26, "Viajes y turismo", "Describe lugares, recorridos y servicios para viajeros.", [
    lesson("u26-l1", 1, "Lugares que conocemos", "Usa oraciones de relativo para describir destinos.", [
      phrase("Das ist das Hotel, das am See liegt.", "Este es el hotel que está junto al lago.", "Hotel", "El relativo das concuerda con Hotel y liegt cierra la oración relativa.", ["Este es el hotel situado junto al lago."]),
      phrase("Ich kenne eine Stadt, in der viele Museen sind.", "Conozco una ciudad en la que hay muchos museos.", "Stadt", "in der expresa dativo porque Stadt es el lugar de la acción.", ["Conozco una ciudad donde hay muchos museos."], ["Ich kenne eine Stadt, in der es viele Museen gibt."]),
      phrase("Wir besuchen den Markt, den du beschrieben hast.", "Visitamos el mercado que has descrito.", "Markt", "den es el acusativo masculino de Markt y hast queda al final.", ["Visitamos el mercado que describiste."]),
      phrase("Die Reiseleiterin, mit der wir sprechen, kommt aus Wien.", "La guía con la que hablamos es de Viena.", "Reiseleiterin", "mit der rige dativo y la relativa termina con sprechen.", ["La guía turística con la que hablamos viene de Viena."]),
      phrase("Der Zug, auf den wir warten, hat Verspätung.", "El tren que esperamos lleva retraso.", "Zug", "warten auf rige acusativo: auf den; la principal continúa con hat.", ["El tren al que esperamos tiene retraso."]),
      phrase("Ich mag das Dorf, in dem meine Großeltern leben.", "Me gusta el pueblo en el que viven mis abuelos.", "Dorf", "in dem introduce una relativa de lugar y leben va al final.", ["Me gusta el pueblo donde viven mis abuelos."]),
    ]),
    lesson("u26-l2", 2, "Reservas y expectativas", "Practica verbos con preposición al organizar unas vacaciones.", [
      phrase("Wir freuen uns auf den Urlaub.", "Estamos deseando las vacaciones.", "Urlaub", "sich freuen auf se usa para algo esperado en el futuro.", ["Tenemos ganas de las vacaciones."]),
      phrase("Er erinnert sich an den Weg.", "Él recuerda el camino.", "erinnert", "sich erinnern an rige acusativo: an den Weg.", ["Se acuerda del camino."]),
      phrase("Sie interessiert sich für lokale Geschichte.", "A ella le interesa la historia local.", "Geschichte", "sich interessieren für introduce el tema que interesa.", ["Está interesada en la historia local."]),
      phrase("Ich warte auf eine Antwort vom Hotel.", "Espero una respuesta del hotel.", "warte", "warten auf rige acusativo y el verbo se conjuga warte con ich.", ["Estoy esperando una respuesta del hotel."]),
      phrase("Wir sprechen über die Route.", "Hablamos sobre la ruta.", "Route", "sprechen über rige acusativo: über die Route.", ["Comentamos el recorrido."]),
      phrase("Der Reisende bittet um Hilfe.", "El viajero pide ayuda.", "Reisende", "bitten um se usa para solicitar algo y um rige acusativo.", ["El viajero solicita ayuda."]),
    ]),
    lesson("u26-l3", 3, "Servicios para viajeros", "Reconoce la pasiva en avisos y servicios turísticos.", [
      phrase("Die Koffer werden am Schalter kontrolliert.", "Las maletas se controlan en el mostrador.", "Koffer", "La pasiva en presente se forma con werden y el participio kontrolliert.", ["En el mostrador se revisan las maletas."]),
      phrase("Das Zimmer wurde gestern gereinigt.", "La habitación se limpió ayer.", "Zimmer", "La pasiva en Präteritum usa wurde y el participio gereinigt.", ["Ayer fue limpiada la habitación."]),
      phrase("Die Tickets werden per E-Mail verschickt.", "Los billetes se envían por correo electrónico.", "Tickets", "Con sujeto plural, la pasiva en presente usa werden.", ["Los billetes se mandan por correo electrónico."]),
      phrase("Der Bus wird von einer Fahrerin gelenkt.", "El autobús lo conduce una conductora.", "Fahrerin", "von introduce a quien realiza la acción en una pasiva.", ["Una conductora conduce el autobús."]),
      phrase("Die Brücke wurde wegen des Wetters gesperrt.", "El puente se cerró por el tiempo.", "Brücke", "wurde marca la pasiva en pasado y wegen expresa la causa.", ["El puente fue cerrado debido al tiempo."]),
      phrase("Das Museum wird im Sommer renoviert.", "El museo se reforma en verano.", "Museum", "La pasiva en presente usa wird y el participio renoviert.", ["El museo será reformado en verano."]),
    ]),
  ]),
  unit("u27", 27, "Salud y consejos", "Pide ayuda, da consejos y habla de hábitos saludables.", [
    lesson("u27-l1", 1, "Pedir con cortesía", "Usa el Konjunktiv II para hacer peticiones educadas.", [
      phrase("Könnten Sie mir bitte einen Termin geben?", "¿Podría darme una cita, por favor?", "Könnten", "Könnten Sie es una petición cortés en Konjunktiv II.", ["¿Me podría dar una cita, por favor?"]),
      phrase("Ich hätte gern ein Rezept für dieses Medikament.", "Querría una receta para este medicamento.", "hätte", "hätte gern expresa un deseo cortés con el Konjunktiv II de haben.", ["Me gustaría una receta para este medicamento."]),
      phrase("Würden Sie die Frage wiederholen?", "¿Podría repetir la pregunta?", "Würden", "Würden Sie + infinitivo formula una petición muy cortés.", ["¿Sería tan amable de repetir la pregunta?"]),
      phrase("Du solltest mehr Wasser trinken.", "Deberías beber más agua.", "solltest", "solltest sirve para dar un consejo y el infinitivo va al final.", ["Tendrías que beber más agua."]),
      phrase("An deiner Stelle würde ich mich ausruhen.", "En tu lugar, yo descansaría.", "Stelle", "An deiner Stelle introduce un consejo hipotético con würde.", ["Yo, en tu lugar, descansaría."]),
      phrase("Es wäre sinnvoller, heute zu Hause zu bleiben.", "Sería más sensato quedarse hoy en casa.", "sinnvoller", "sinnvoller expresa una recomendación comparativa en Konjunktiv II.", ["Sería más prudente quedarse hoy en casa."]),
    ]),
    lesson("u27-l2", 2, "Objetivos saludables", "Usa infinitivo con zu para hablar de hábitos y objetivos.", [
      phrase("Ich versuche, jeden Abend früher einzuschlafen.", "Intento dormirme antes todas las noches.", "versuche", "versuchen se combina con un infinitivo con zu: einzuschlafen.", ["Procuro dormirme más temprano cada noche."]),
      phrase("Es ist wichtig, regelmäßig Pausen zu machen.", "Es importante hacer pausas con regularidad.", "wichtig", "Después de Es ist wichtig aparece un infinitivo con zu.", ["Es importante descansar a menudo."]),
      phrase("Sie hat vergessen, den Verband zu wechseln.", "Ella se ha olvidado de cambiar el vendaje.", "vergessen", "vergessen puede introducir una acción pendiente con zu wechseln.", ["Se olvidó de cambiar el vendaje."]),
      phrase("Wir planen, gemeinsam zu kochen.", "Planeamos cocinar juntos.", "planen", "planen rige un infinitivo con zu.", ["Tenemos pensado cocinar juntos."]),
      phrase("Er lernt, mit Stress umzugehen.", "Él aprende a gestionar el estrés.", "Stress", "umgehen con zu se usa para expresar cómo se aprende a hacer algo.", ["Está aprendiendo a manejar el estrés."]),
      phrase("Um gesund zu bleiben, geht sie oft spazieren.", "Para mantenerse sana, ella sale a pasear a menudo.", "gesund", "um ... zu expresa finalidad y el infinitivo principal es zu bleiben.", ["Para conservar la salud, sale a caminar a menudo."]),
    ]),
    lesson("u27-l3", 3, "Tratamientos y preocupaciones", "Usa verbos con preposición para hablar de la salud.", [
      phrase("Ich beschwere mich über starke Kopfschmerzen.", "Me quejo de un dolor de cabeza fuerte.", "beschwere", "sich beschweren über rige acusativo: über starke Kopfschmerzen.", ["Me quejo de que me duele mucho la cabeza."]),
      phrase("Sie wartet auf die Untersuchung.", "Ella espera la exploración.", "Untersuchung", "warten auf introduce aquello que se espera.", ["Está esperando la revisión."]),
      phrase("Wir interessieren uns für neue Therapien.", "Nos interesan las terapias nuevas.", "interessieren", "sich interessieren für se usa para expresar interés.", ["Estamos interesados en nuevos tratamientos."]),
      phrase("Er denkt an seine Gesundheit.", "Él piensa en su salud.", "denkt", "denken an rige acusativo: an seine Gesundheit.", ["Se preocupa por su salud."]),
      phrase("Nach dem Training fühlt sie sich erschöpft.", "Después del entrenamiento ella se siente agotada.", "Training", "sich fühlen es reflexivo y erschöpft describe el estado.", ["Después de entrenar se encuentra cansada."]),
      phrase("Ich freue mich darauf, bald wieder zu laufen.", "Estoy deseando volver a correr pronto.", "freue", "sich freuen auf algo se sustituye por darauf cuando sigue un infinitivo con zu.", ["Tengo ganas de volver a correr pronto."]),
    ]),
  ]),
  unit("u28", 28, "Vivienda y vecinos", "Describe edificios, reparaciones y acuerdos con los vecinos.", [
    lesson("u28-l1", 1, "Obras en el edificio", "Entiende avisos escritos en voz pasiva.", [
      phrase("Die neuen Wohnungen werden im Mai übergeben.", "Las viviendas nuevas se entregan en mayo.", "Wohnungen", "La pasiva en presente usa werden y el participio übergeben.", ["Las nuevas viviendas serán entregadas en mayo."]),
      phrase("Der Aufzug wird gerade repariert.", "El ascensor se está reparando ahora mismo.", "Aufzug", "wird ... repariert forma la pasiva en presente.", ["Ahora están reparando el ascensor."]),
      phrase("Die Hausordnung wird von allen Bewohnern gelesen.", "Todos los residentes leen las normas de la casa.", "Hausordnung", "von introduce el agente de una oración pasiva.", ["Las normas del edificio son leídas por todos los vecinos."]),
      phrase("Die Fenster wurden letzte Woche ausgetauscht.", "Las ventanas se cambiaron la semana pasada.", "Fenster", "wurden marca la pasiva en Präteritum para un sujeto plural.", ["La semana pasada fueron sustituidas las ventanas."]),
      phrase("Der Hof wird jeden Morgen gereinigt.", "El patio se limpia cada mañana.", "Hof", "wird ... gereinigt es una pasiva habitual en presente.", ["Cada mañana limpian el patio."]),
      phrase("Die Heizung wurde im Winter eingeschaltet.", "La calefacción se encendió en invierno.", "Heizung", "La pasiva en pasado combina wurde con eingeschaltet.", ["En invierno encendieron la calefacción."]),
    ]),
    lesson("u28-l2", 2, "Describir una vivienda", "Usa relativas para explicar qué vivienda buscas.", [
      phrase("Das ist die Wohnung, die wir besichtigen möchten.", "Este es el piso que queremos visitar.", "Wohnung", "die es el pronombre relativo acusativo femenino y möchten queda al final.", ["Este es el piso que nos gustaría ver."]),
      phrase("Der Nachbar, der über uns wohnt, ist freundlich.", "El vecino que vive encima de nosotros es amable.", "Nachbar", "der es el sujeto de la relativa y wohnt cierra la descripción.", ["El vecino de arriba es simpático."]),
      phrase("Ich kenne einen Handwerker, dem ich vertraue.", "Conozco a un técnico en quien confío.", "Handwerker", "vertrauen rige dativo, por eso la relativa usa dem.", ["Conozco a un profesional de confianza."]),
      phrase("Wir suchen ein Haus, in dem Haustiere erlaubt sind.", "Buscamos una casa en la que se permitan mascotas.", "Haustiere", "in dem introduce el lugar y sind cierra la relativa.", ["Buscamos una casa donde se admitan animales."]),
      phrase("Die Straße, an der wir wohnen, ist ruhig.", "La calle en la que vivimos es tranquila.", "Straße", "an der expresa ubicación y wohnen va al final de la relativa.", ["La calle donde vivimos es tranquila."]),
      phrase("Die Reparatur, auf die wir warten, beginnt morgen.", "La reparación que esperamos empieza mañana.", "Reparatur", "warten auf rige acusativo: auf die Reparatur.", ["La reparación que estamos esperando empieza mañana."]),
    ]),
    lesson("u28-l3", 3, "Hablar con el casero", "Formula peticiones y deseos sobre la vivienda.", [
      phrase("Könnten Sie die Miete bitte erklären?", "¿Podría explicarme el alquiler, por favor?", "Miete", "Könnten Sie formula una petición cortés en Konjunktiv II.", ["¿Me podría explicar el alquiler, por favor?"]),
      phrase("Ich würde gern den Balkon sehen.", "Me gustaría ver el balcón.", "Balkon", "würde gern expresa un deseo y el infinitivo sehen va al final.", ["Quisiera ver el balcón."]),
      phrase("Wäre es möglich, den Termin zu verschieben?", "¿Sería posible aplazar la cita?", "möglich", "Wäre es möglich formula una petición hipotética y zu verschieben expresa la acción.", ["¿Se podría cambiar la cita?"]),
      phrase("An Ihrer Stelle würde ich den Vertrag prüfen.", "En su lugar, revisaría el contrato.", "Stelle", "An Ihrer Stelle introduce un consejo formal con würde.", ["Yo, en su lugar, comprobaría el contrato."]),
      phrase("Wir hätten gern eine schriftliche Antwort.", "Querríamos una respuesta por escrito.", "schriftliche", "hätten gern expresa un deseo cortés y el adjetivo acompaña a Antwort.", ["Nos gustaría recibir una respuesta escrita."]),
      phrase("Es wäre schön, wenn die Nachbarn leiser wären.", "Sería estupendo que los vecinos fueran más silenciosos.", "Nachbarn", "wären es el Konjunktiv II de sein en una condición irreal o deseada.", ["Estaría bien que los vecinos hicieran menos ruido."]),
    ]),
  ]),
  unit("u29", 29, "Medio ambiente y energía", "Habla de hábitos sostenibles, recursos y soluciones.", [
    lesson("u29-l1", 1, "Reducir el consumo", "Usa infinitivos con zu para explicar objetivos ambientales.", [
      phrase("Es ist notwendig, weniger Strom zu verbrauchen.", "Es necesario consumir menos electricidad.", "notwendig", "Es ist notwendig se completa con un infinitivo con zu.", ["Hay que consumir menos electricidad."]),
      phrase("Wir versuchen, den Abfall zu reduzieren.", "Intentamos reducir los residuos.", "reduzieren", "versuchen rige un infinitivo con zu: zu reduzieren.", ["Procuramos reducir la basura."]),
      phrase("Sie hat begonnen, mit dem Fahrrad zu fahren.", "Ella ha empezado a ir en bicicleta.", "begonnen", "beginnen introduce una acción con zu fahren.", ["Ha empezado a desplazarse en bici."]),
      phrase("Um Energie zu sparen, schalten wir das Licht aus.", "Para ahorrar energía, apagamos la luz.", "Energie", "um ... zu expresa finalidad y ausschalten se separa en la principal.", ["Apagamos la luz para ahorrar energía."]),
      phrase("Er hofft, eine nachhaltige Lösung zu finden.", "Espera encontrar una solución sostenible.", "nachhaltige", "hoffen se combina con el infinitivo zu finden.", ["Espera hallar una solución respetuosa con el medio ambiente."]),
      phrase("Es lohnt sich, regionale Produkte zu kaufen.", "Merece la pena comprar productos regionales.", "lohnt", "sich lohnen introduce una acción valorada con zu kaufen.", ["Vale la pena comprar productos de la zona."]),
    ]),
    lesson("u29-l2", 2, "Condiciones del clima", "Combina subordinadas para explicar problemas y consecuencias.", [
      phrase("Obwohl der Weg weit ist, fahren wir mit dem Zug.", "Aunque el camino es largo, vamos en tren.", "weit", "obwohl introduce una concesión y ist va al final.", ["Aunque queda lejos, vamos en tren."]),
      phrase("Wir bleiben draußen, solange das Wetter hält.", "Nos quedamos fuera mientras aguante el tiempo.", "hält", "solange introduce una condición temporal y hält cierra la subordinada.", ["Seguimos fuera mientras dure el buen tiempo."]),
      phrase("Wenn die Preise steigen, sparen viele Haushalte Energie.", "Si suben los precios, muchos hogares ahorran energía.", "Preise", "La subordinada con wenn precede a la principal y el verbo principal va en segunda posición.", ["Cuando aumentan los precios, muchos hogares ahorran energía."]),
      phrase("Sie erklärt, dass Recycling wichtig ist.", "Ella explica que reciclar es importante.", "Recycling", "Con dass, ist cierra la subordinada.", ["Explica que el reciclaje es importante."]),
      phrase("Er fragt, ob die Anlage schon funktioniert.", "Pregunta si la instalación ya funciona.", "Anlage", "ob introduce una pregunta indirecta y funktioniert va al final.", ["Pregunta si la planta ya funciona."]),
      phrase("Nachdem der Sturm vorbei war, reparierten wir das Dach.", "Después de que pasara la tormenta, reparamos el tejado.", "Sturm", "Nachdem introduce una acción anterior y war queda al final.", ["Cuando terminó la tormenta, reparamos el tejado."]),
    ]),
    lesson("u29-l3", 3, "Proteger la naturaleza", "Practica verbos con preposición sobre acciones ambientales.", [
      phrase("Viele Menschen setzen sich für den Naturschutz ein.", "Muchas personas defienden la protección de la naturaleza.", "Naturschutz", "sich einsetzen für expresa compromiso y el verbo separable termina en ein.", ["Mucha gente trabaja por la protección ambiental."]),
      phrase("Wir achten auf den Wasserverbrauch.", "Prestamos atención al consumo de agua.", "achten", "achten auf rige acusativo: auf den Wasserverbrauch.", ["Cuidamos el consumo de agua."]),
      phrase("Die Stadt verfügt über ein gutes Radwegenetz.", "La ciudad dispone de una buena red de carriles bici.", "Stadt", "verfügen über rige acusativo y expresa disponibilidad.", ["La ciudad cuenta con una buena red ciclista."]),
      phrase("Sie trägt zur Energiewende bei.", "Ella contribuye a la transición energética.", "trägt", "beitragen zu rige dativo y es separable: trägt ... bei.", ["Contribuye al cambio energético."]),
      phrase("Ich denke über eine Solaranlage nach.", "Estoy pensando en una instalación solar.", "denke", "nachdenken über rige acusativo y es separable: denke ... nach.", ["Reflexiono sobre instalar placas solares."]),
      phrase("Der Bericht weist auf neue Risiken hin.", "El informe señala nuevos riesgos.", "Bericht", "hinweisen auf rige acusativo y el verbo es separable: weist ... hin.", ["El informe advierte de nuevos riesgos."]),
    ]),
  ]),
  unit("u30", 30, "Medios y sociedad", "Describe programas, artículos y cambios en la comunicación.", [
    lesson("u30-l1", 1, "Personas y programas", "Usa oraciones de relativo para describir contenidos de los medios.", [
      phrase("Die Zeitung, die ich lese, erscheint täglich.", "El periódico que leo sale a diario.", "Zeitung", "die es el objeto de lese y la relativa queda entre comas.", ["El diario que leo se publica todos los días."]),
      phrase("Kennst du den Moderator, der die Sendung leitet?", "¿Conoces al presentador que dirige el programa?", "Moderator", "der es el sujeto de la oración relativa.", ["¿Conoces al presentador que lleva el programa?"]),
      phrase("Das ist ein Thema, über das viele diskutieren.", "Este es un tema sobre el que muchos debaten.", "Thema", "über das rige acusativo y el verbo discutieren queda al final.", ["Este es un asunto del que habla mucha gente."]),
      phrase("Wir treffen eine Autorin, deren Buch verfilmt wurde.", "Conocemos a una autora cuyo libro se ha llevado al cine.", "Autorin", "deren expresa posesión en una oración relativa.", ["Conocemos a una escritora cuya obra se adaptó al cine."]),
      phrase("Der Film, in dem sie spielt, gewinnt einen Preis.", "La película en la que actúa gana un premio.", "Film", "in dem introduce el lugar figurado de la acción y spielt cierra la relativa.", ["La película donde actúa recibe un premio."]),
      phrase("Ich höre einen Podcast, der aktuelle Fragen erklärt.", "Escucho un pódcast que explica cuestiones actuales.", "Podcast", "der es el sujeto de la relativa y erklärt va al final.", ["Oigo un pódcast que aclara temas de actualidad."]),
    ]),
    lesson("u30-l2", 2, "Investigar y opinar", "Usa verbos con preposición para hablar de información.", [
      phrase("Die Redaktion wartet auf die Rückmeldung.", "La redacción espera la respuesta.", "Redaktion", "warten auf rige acusativo: auf die Rückmeldung.", ["La redacción está esperando la respuesta."]),
      phrase("Er berichtet über seine Erfahrungen.", "Él informa sobre sus experiencias.", "berichtet", "berichten über introduce el tema del informe.", ["Cuenta sus experiencias."], ["Er erzählt von seinen Erfahrungen."]),
      phrase("Wir sprechen mit der Journalistin über die Recherche.", "Hablamos con la periodista sobre la investigación.", "Journalistin", "mit rige dativo y über introduce el tema.", ["Comentamos la investigación con la periodista."]),
      phrase("Sie zweifelt an der Aussage.", "Ella duda de la afirmación.", "zweifelt", "zweifeln an rige dativo: an der Aussage.", ["Pone en duda la declaración."]),
      phrase("Ich interessiere mich für politische Debatten.", "Me interesan los debates políticos.", "interessiere", "sich interessieren für expresa interés por un tema.", ["Estoy interesado en los debates políticos."]),
      phrase("Der Artikel bezieht sich auf eine neue Studie.", "El artículo se refiere a un estudio nuevo.", "bezieht", "sich beziehen auf rige acusativo y es separable: bezieht ... sich.", ["El artículo hace referencia a una investigación nueva."]),
    ]),
    lesson("u30-l3", 3, "La comunicación del futuro", "Habla de predicciones y cambios con Futur I.", [
      phrase("Wir werden die Ergebnisse morgen veröffentlichen.", "Publicaremos los resultados mañana.", "Ergebnisse", "El Futur I se forma con werden y el infinitivo veröffentlichen al final.", ["Mañana publicaremos los resultados."]),
      phrase("Die Sendung wird um acht Uhr beginnen.", "El programa empezará a las ocho.", "Sendung", "wird ... beginnen forma el Futur I.", ["El programa comenzará a las ocho."]),
      phrase("Ich werde später mit dir sprechen.", "Hablaré contigo más tarde.", "sprechen", "werden expresa una acción futura y sprechen queda en infinitivo.", ["Más tarde hablaré contigo."]),
      phrase("Die Medien werden sich weiter verändern.", "Los medios seguirán cambiando.", "Medien", "El pronombre reflexivo se coloca junto al infinitivo verändern.", ["Los medios de comunicación continuarán cambiando."]),
      phrase("Du wirst bald eine Antwort erhalten.", "Pronto recibirás una respuesta.", "erhalten", "wirst ... erhalten es el Futur I con du.", ["Recibirás una respuesta dentro de poco."]),
      phrase("Es wird schwieriger werden, Falschmeldungen zu erkennen.", "Será más difícil detectar noticias falsas.", "schwieriger", "El primer werden forma el futuro y el segundo queda en el infinitivo de la construcción.", ["Detectar bulos será más complicado."]),
    ]),
  ]),
  unit("u31", 31, "Estudios y futuro", "Planifica tu formación y habla de objetivos académicos.", [
    lesson("u31-l1", 1, "Planes académicos", "Usa Futur I para expresar decisiones y predicciones.", [
      phrase("Nach dem Kurs werde ich ein Praktikum beginnen.", "Después del curso empezaré unas prácticas.", "Praktikum", "werde ... beginnen forma el Futur I y nach dem Kurs indica el momento.", ["Al terminar el curso comenzaré unas prácticas."]),
      phrase("Wir werden nächstes Jahr in Berlin studieren.", "El año que viene estudiaremos en Berlín.", "studieren", "werden acompaña al infinitivo studieren para expresar el futuro.", ["El próximo año estudiaremos en Berlín."], ["Nächstes Jahr studieren wir in Berlin."]),
      phrase("Die Prüfung wird nicht leicht sein.", "El examen no será fácil.", "Prüfung", "wird ... sein es el Futur I de sein.", ["El examen no resultará sencillo."]),
      phrase("Ich werde dir die Aufgabe erklären.", "Te explicaré el ejercicio.", "erklären", "El pronombre dativo dir aparece antes del infinitivo erklären.", ["Te explicaré la tarea."]),
      phrase("Ihr werdet eure Ergebnisse präsentieren.", "Presentaréis vuestros resultados.", "Ergebnisse", "werdet ... präsentieren expresa el futuro con ihr.", ["Vais a presentar vuestros resultados."]),
      phrase("Sie wird sich auf den Abschluss vorbereiten.", "Ella se preparará para la graduación.", "vorbereiten", "sich vorbereiten auf rige acusativo y el infinitivo queda al final.", ["Se preparará para terminar los estudios."]),
    ]),
    lesson("u31-l2", 2, "Aprender de forma autónoma", "Expresa planes y objetivos con infinitivo con zu.", [
      phrase("Ich habe vor, im Sommer einen Kurs zu besuchen.", "Tengo pensado hacer un curso en verano.", "vor", "vorhaben se usa con un infinitivo con zu para expresar un plan.", ["Planeo asistir a un curso en verano."]),
      phrase("Er versucht, die schwierige Regel zu verstehen.", "Intenta entender la regla difícil.", "versucht", "versuchen rige un infinitivo con zu.", ["Procura comprender la regla complicada."]),
      phrase("Wir lernen, selbstständig zu arbeiten.", "Aprendemos a trabajar de forma autónoma.", "lernen", "lernen puede introducir una destreza con infinitivo con zu.", ["Estamos aprendiendo a trabajar por nuestra cuenta."]),
      phrase("Es ist wichtig, Fragen zu stellen.", "Es importante hacer preguntas.", "wichtig", "Es ist wichtig se completa con un infinitivo con zu.", ["Es importante plantear preguntas."]),
      phrase("Sie ging in die Bibliothek, um in Ruhe zu lesen.", "Fue a la biblioteca para leer tranquilamente.", "Bibliothek", "um ... zu expresa finalidad.", ["Se dirigió a la biblioteca para estudiar en calma."]),
      phrase("Anstatt zu warten, rufe ich direkt an.", "En vez de esperar, llamo directamente.", "warten", "Anstatt zu introduce una alternativa y anrufen se separa en la principal.", ["En lugar de esperar, llamo directamente."]),
    ]),
    lesson("u31-l3", 3, "Recuerdos de clase", "Combina Präteritum y subordinadas al contar experiencias.", [
      phrase("Früher lernte ich jeden Abend in der Bibliothek.", "Antes estudiaba cada tarde en la biblioteca.", "Früher", "lernte es el Präteritum regular de lernen.", ["Antes estudié todas las tardes en la biblioteca."]),
      phrase("Der Lehrer erklärte, warum die Lösung falsch war.", "El profesor explicó por qué la solución era incorrecta.", "Lehrer", "war queda al final de la pregunta indirecta introducida por warum.", ["El profesor explicó por qué estaba mal la solución."]),
      phrase("Wir wussten nicht, ob die Prüfung heute stattfand.", "No sabíamos si el examen tenía lugar hoy.", "wussten", "wussten es el Präteritum de wissen y stattfand cierra la subordinada.", ["No sabíamos si el examen era hoy."]),
      phrase("Obwohl ich müde war, las ich das Kapitel.", "Aunque estaba cansado, leí el capítulo.", "müde", "obwohl introduce la concesión y war va al final.", ["Aunque estaba cansada, leí el capítulo."]),
      phrase("Sie hatte keine Zeit, weil sie arbeiten musste.", "Ella no tenía tiempo porque tenía que trabajar.", "hatte", "hatte es el Präteritum de haben y musste cierra la subordinada con modal.", ["No tenía tiempo porque debía trabajar."]),
      phrase("Als der Kurs begann, waren alle Plätze besetzt.", "Cuando empezó el curso, todos los sitios estaban ocupados.", "begann", "als se usa para un acontecimiento pasado y el verbo va al final de la subordinada.", ["Al empezar el curso, todos los asientos estaban ocupados."]),
    ]),
  ]),
  unit("u32", 32, "Relaciones y cultura", "Habla de vínculos, recuerdos y planes culturales.", [
    lesson("u32-l1", 1, "Deseos y posibilidades", "Usa Konjunktiv II para expresar deseos y situaciones hipotéticas.", [
      phrase("Ich würde gern länger in Spanien bleiben.", "Me gustaría quedarme más tiempo en España.", "würde", "würde gern expresa un deseo y bleiben queda en infinitivo.", ["Quisiera quedarme más tiempo en España."]),
      phrase("Wenn ich mehr Zeit hätte, würde ich Italienisch lernen.", "Si tuviera más tiempo, estudiaría italiano.", "hätte", "hätte introduce una condición irreal y würde ... lernen expresa la consecuencia en Konjunktiv II.", ["Si tuviera más tiempo, aprendería italiano."]),
      phrase("An deiner Stelle würde ich offen sprechen.", "En tu lugar, hablaría con sinceridad.", "Stelle", "An deiner Stelle introduce un consejo hipotético.", ["Yo, en tu lugar, hablaría claramente."]),
      phrase("Es wäre schön, wenn wir uns öfter träfen.", "Sería bonito que nos viéramos más a menudo.", "wäre", "wäre y träfen expresan un deseo irreal o difícil de cumplir.", ["Estaría bien que quedáramos más veces."]),
      phrase("Wir könnten gemeinsam ein Konzert besuchen.", "Podríamos ir juntos a un concierto.", "könnten", "könnten expresa una posibilidad en Konjunktiv II.", ["Podríamos asistir juntos a un concierto."]),
      phrase("Ich wünschte, ich könnte besser tanzen.", "Ojalá supiera bailar mejor.", "wünschte", "wünschen en Konjunktiv II expresa un deseo.", ["Me gustaría bailar mejor."]),
    ]),
    lesson("u32-l2", 2, "Personas y recuerdos", "Precisa relaciones con pronombres relativos.", [
      phrase("Das ist die Freundin, mit der ich studiert habe.", "Esta es la amiga con la que estudié.", "Freundin", "mit der rige dativo y habe queda al final de la relativa en Perfekt.", ["Esta es la amiga con la que estudiaba."]),
      phrase("Ich besuche den Ort, an dem wir uns kennengelernt haben.", "Visito el lugar donde nos conocimos.", "Ort", "an dem introduce el lugar y haben cierra el Perfekt de la relativa.", ["Visito el sitio en el que nos conocimos."]),
      phrase("Der Mann, dessen Tochter in Paris lebt, ist mein Nachbar.", "El hombre cuya hija vive en París es mi vecino.", "dessen", "dessen expresa posesión en una oración relativa masculina.", ["Mi vecino es el hombre cuya hija vive en París."]),
      phrase("Wir sehen ein Stück, das eine junge Autorin schrieb.", "Vemos una obra que escribió una autora joven.", "Stück", "das concuerda con Stück y schrieb cierra la relativa.", ["Vemos una obra escrita por una autora joven."]),
      phrase("Die Menschen, denen wir helfen, wohnen hier.", "Las personas a las que ayudamos viven aquí.", "Menschen", "helfen rige dativo, por eso la relativa usa denen.", ["Las personas a quienes ayudamos viven aquí."]),
      phrase("Ich kenne ein Café, in dem man lange sitzen kann.", "Conozco un café en el que uno puede sentarse mucho rato.", "Café", "in dem expresa ubicación y kann queda al final de la relativa.", ["Conozco una cafetería donde se puede estar horas."]),
    ]),
    lesson("u32-l3", 3, "Hablar de vínculos", "Combina verbos con preposición y subordinadas.", [
      phrase("Sie freut sich auf den Besuch ihrer Schwester.", "Ella está deseando la visita de su hermana.", "freut", "sich freuen auf expresa ilusión por algo futuro.", ["Tiene ganas de que venga su hermana."]),
      phrase("Er träumt von einer Reise, die lange dauern soll.", "Él sueña con un viaje que debería durar mucho tiempo.", "träumt", "träumen von rige dativo y la relativa termina en soll.", ["Sueña con un viaje largo."]),
      phrase("Wir sprechen darüber, warum sie umzieht.", "Hablamos de por qué ella se muda.", "sprechen", "darüber retoma un tema y warum introduce una pregunta indirecta.", ["Comentamos el motivo de su mudanza."]),
      phrase("Obwohl sie beschäftigt ist, ruft sie ihre Eltern an.", "Aunque está ocupada, llama a sus padres.", "beschäftigt", "obwohl coloca ist al final y anrufen se separa en la principal.", ["Aunque está ocupada, telefonea a sus padres."]),
      phrase("Ich erinnere mich daran, wie wir uns getroffen haben.", "Recuerdo cómo nos conocimos.", "erinnere", "sich erinnern an se retoma con daran cuando sigue una subordinada.", ["Me acuerdo de cómo nos conocimos."]),
      phrase("Wenn du möchtest, können wir später telefonieren.", "Si quieres, podemos hablar por teléfono más tarde.", "möchtest", "wenn introduce la condición y können ocupa la segunda posición de la principal.", ["Si te apetece, podemos llamarnos después."]),
    ]),
  ]),
  unit("u33", 33, "Trámites y trabajo", "Gestiona documentos, plazos y comunicaciones formales.", [
    lesson("u33-l1", 1, "Documentos oficiales", "Entiende procesos administrativos en voz pasiva.", [
      phrase("Der Antrag wird heute bearbeitet.", "La solicitud se tramita hoy.", "Antrag", "La pasiva en presente usa wird y el participio bearbeitet.", ["Hoy se procesa la solicitud."]),
      phrase("Die Unterlagen werden von der Sachbearbeiterin geprüft.", "La gestora revisa la documentación.", "Unterlagen", "von introduce el agente y werden concuerda con Unterlagen.", ["La documentación es revisada por la funcionaria."]),
      phrase("Der Termin wurde per E-Mail bestätigt.", "La cita se confirmó por correo electrónico.", "Termin", "wurde ... bestätigt forma la pasiva en Präteritum.", ["La cita fue confirmada por correo."]),
      phrase("Die Rechnung wird nächste Woche bezahlt.", "La factura se pagará la semana que viene.", "Rechnung", "La pasiva en presente puede referirse a una acción programada.", ["La factura se abonará la próxima semana."]),
      phrase("Die Daten werden sicher gespeichert.", "Los datos se guardan de forma segura.", "Daten", "Con sujeto plural, la pasiva usa werden.", ["Los datos quedan almacenados de manera segura."]),
      phrase("Das Formular wurde gestern unterschrieben.", "El formulario se firmó ayer.", "Formular", "wurde y unterschrieben forman la pasiva en pasado.", ["Ayer fue firmado el formulario."]),
    ]),
    lesson("u33-l2", 2, "Resolver una gestión", "Expresa necesidades y preguntas con verbos preposicionales.", [
      phrase("Ich kümmere mich um die Anmeldung.", "Me ocupo de la inscripción.", "kümmere", "sich kümmern um rige acusativo: um die Anmeldung.", ["Me encargo del registro."]),
      phrase("Wir warten auf die Genehmigung.", "Esperamos la autorización.", "Genehmigung", "warten auf introduce aquello que se espera.", ["Estamos esperando el permiso."]),
      phrase("Sie informiert sich über die Voraussetzungen.", "Ella se informa sobre los requisitos.", "informiert", "sich informieren über rige acusativo.", ["Consulta cuáles son las condiciones."]),
      phrase("Der Mitarbeiter besteht auf einer schriftlichen Antwort.", "El empleado insiste en una respuesta por escrito.", "besteht", "bestehen auf rige dativo: auf einer Antwort.", ["El trabajador exige una respuesta escrita."]),
      phrase("Er bedankt sich für die schnelle Hilfe.", "Él da las gracias por la ayuda rápida.", "bedankt", "sich bedanken für rige acusativo y expresa agradecimiento.", ["Agradece la ayuda rápida."]),
      phrase("Die Firma sucht nach einer neuen Lösung.", "La empresa busca una solución nueva.", "Firma", "suchen nach rige dativo: nach einer Lösung.", ["La empresa está buscando una nueva solución."]),
    ]),
    lesson("u33-l3", 3, "Plazos y respuestas", "Combina pasado, subordinadas y Futur I en situaciones formales.", [
      phrase("Früher arbeitete sie in einem kleinen Betrieb.", "Antes trabajaba en una empresa pequeña.", "arbeitete", "arbeitete es el Präteritum regular de arbeiten.", ["Antes trabajó en una empresa pequeña."]),
      phrase("Der Antrag blieb lange ohne Antwort.", "La solicitud permaneció mucho tiempo sin respuesta.", "blieb", "blieb es el Präteritum irregular de bleiben.", ["La solicitud estuvo mucho tiempo sin respuesta."]),
      phrase("Wir hofften, dass alles schneller geht.", "Esperábamos que todo fuera más rápido.", "hofften", "hofften es el Präteritum de hoffen y dass coloca geht al final.", ["Esperábamos que todo avanzara más deprisa."]),
      phrase("Obwohl die Frist kurz war, reichten wir alles ein.", "Aunque el plazo era corto, lo presentamos todo.", "Frist", "obwohl introduce la concesión y einreichen se separa en la principal.", ["Aunque quedaba poco plazo, entregamos todo."]),
      phrase("Wenn die Prüfung abgeschlossen ist, wird die Behörde antworten.", "Cuando termine la revisión, responderá la administración.", "Prüfung", "La subordinada con wenn termina en ist y la principal usa Futur I.", ["Cuando se complete la revisión, contestará la administración."]),
      phrase("Ich werde den Bescheid sorgfältig lesen.", "Leeré detenidamente la resolución.", "Bescheid", "werde ... lesen expresa una acción futura.", ["Revisaré con cuidado la resolución."]),
    ]),
  ]),
];
