import type { LessonDraft, Phrase, UnitDraft } from "./units";

const phrase = (
  german: string,
  spanish: string,
  blankWord: string,
  explanation: string,
  spanishAlt?: string[],
  germanAlt?: string[],
): Phrase => ({
  german,
  spanish,
  blankWord,
  explanation,
  ...(spanishAlt ? { spanishAlt } : {}),
  ...(germanAlt ? { germanAlt } : {}),
});

const lesson = (
  id: string,
  order: number,
  title: string,
  description: string,
  phrases: Phrase[],
): LessonDraft => ({
  id,
  order,
  title,
  description,
  xpReward: 10,
  phrases,
});

const unit = (
  id: string,
  order: number,
  title: string,
  description: string,
  lessons: LessonDraft[],
): UnitDraft => ({
  id,
  order,
  title,
  description,
  color: "#1CB0F6",
  cefrLevel: "A2",
  lessons,
});

export const a2UnitDrafts: UnitDraft[] = [
  unit("u16", 16, "Viajes y desplazamientos", "Organiza un viaje y cuenta cómo te has desplazado.", [
    lesson("u16-l1", 1, "Preparar el viaje", "Habla del equipaje y de los preparativos.", [
      phrase("Ich habe meinen Koffer sorgfältig gepackt.", "He preparado la maleta con cuidado.", "Koffer", "El Perfekt de packen se forma con haben y el participio gepackt.", ["He hecho la maleta con cuidado."]),
      phrase("Am Bahnhof habe ich eine Fahrkarte gekauft.", "En la estación he comprado un billete.", "Bahnhof", "Bahnhof es el lugar de la estación y la frase usa el Perfekt de kaufen.", ["En la estación compré un billete."], ["Eine Fahrkarte habe ich am Bahnhof gekauft."]),
      phrase("Wir haben das Gleis rechtzeitig gefunden.", "Hemos encontrado el andén a tiempo.", "Gleis", "finden tiene el participio irregular gefunden.", ["Encontramos el andén a tiempo."]),
      phrase("Morgen fährt unser Zug nach Hamburg ab.", "Mañana sale nuestro tren hacia Hamburgo.", "fährt", "fahren es separable en presente: fährt va en segunda posición y ab al final.", ["Nuestro tren sale mañana hacia Hamburgo."]),
      phrase("Ich habe meinen Reisepass nicht vergessen.", "No me he olvidado del pasaporte.", "Reisepass", "vergessen forma el Perfekt con haben y el participio irregular vergessen.", ["No olvidé el pasaporte."]),
      phrase("Die Reise hat sehr früh begonnen.", "El viaje ha empezado muy temprano.", "Reise", "beginnen forma el Perfekt con haben y el participio begonnen.", ["El viaje empezó muy temprano."]),
    ]),
    lesson("u16-l2", 2, "Llegar y salir", "Cuenta cómo llegaste a tu destino.", [
      phrase("Am Morgen bin ich zum Flughafen gefahren.", "Por la mañana he ido al aeropuerto.", "Flughafen", "fahren expresa desplazamiento y forma el Perfekt con sein.", ["Por la mañana fui al aeropuerto."]),
      phrase("Der Zug ist pünktlich angekommen.", "El tren ha llegado puntual.", "Zug", "ankommen es un verbo de movimiento y usa sein en Perfekt.", ["El tren llegó puntual."]),
      phrase("Wir haben in einem kleinen Hotel eingecheckt.", "Hemos hecho el registro en un hotel pequeño.", "Hotel", "einchecken forma el Perfekt con haben y el participio queda al final.", ["Nos registramos en un hotel pequeño."]),
      phrase("Heute steigt sie am Hauptbahnhof um.", "Hoy ella cambia de tren en la estación central.", "steigt", "umsteigen es separable: steigt ocupa la segunda posición y um queda al final.", ["Hoy cambia de tren en la estación central."]),
      phrase("Ich habe den Fahrplan online gelesen.", "He leído el horario en internet.", "Fahrplan", "lesen tiene el participio irregular gelesen.", ["Leí el horario en internet."]),
      phrase("Die Kinder sind während der Reise eingeschlafen.", "Los niños se han dormido durante el viaje.", "Kinder", "einschlafen expresa un cambio de estado y forma el Perfekt con sein.", ["Los niños se durmieron durante el viaje."]),
    ]),
    lesson("u16-l3", 3, "Pedir ayuda en la estación", "Usa el dativo para pedir información y ayudar a otras personas.", [
      phrase("Können Sie mir den Weg zum Schalter zeigen?", "¿Puede mostrarme el camino hasta el mostrador?", "Schalter", "zeigen puede llevar una persona en dativo: mir; el destino va con zum.", ["¿Me puede indicar cómo llegar al mostrador?"]),
      phrase("Ich helfe dem älteren Herrn mit seinem Koffer.", "Ayudo al señor mayor con su maleta.", "Herrn", "helfen rige dativo y Herr cambia a Herrn en esta forma.", ["Le ayudo al señor mayor con la maleta."]),
      phrase("Wir warten auf den nächsten Bus.", "Esperamos al siguiente autobús.", "nächsten", "warten auf rige acusativo: auf den nächsten Bus.", ["Estamos esperando el próximo autobús."]),
      phrase("Der Mitarbeiter gibt der Familie neue Tickets.", "El empleado da billetes nuevos a la familia.", "Mitarbeiter", "geben lleva el destinatario en dativo: der Familie.", ["El empleado entrega billetes nuevos a la familia."]),
      phrase("Bitte sagen Sie mir die Abfahrtszeit.", "Dígame, por favor, la hora de salida.", "Abfahrtszeit", "sagen puede llevar la persona en dativo mir y la información en acusativo.", ["Por favor, dígame la hora de salida."]),
      phrase("Am Ende findet jeder seinen Sitzplatz.", "Al final, cada persona encuentra su asiento.", "Sitzplatz", "finden lleva el objeto directo seinen Sitzplatz en acusativo.", ["Al final todos encuentran su asiento."]),
    ]),
  ]),
  unit("u17", 17, "Salud y bienestar", "Habla de síntomas, consejos y hábitos saludables.", [
    lesson("u17-l1", 1, "En la consulta", "Explica tus síntomas y entiende las recomendaciones médicas.", [
      phrase("Die Ärztin untersucht meinen Rücken.", "La médica me examina la espalda.", "Ärztin", "Ärztin es la profesional que realiza la exploración.", ["La doctora me examina la espalda."]),
      phrase("Ich muss morgens diese Tablette nehmen.", "Tengo que tomar esta pastilla por la mañana.", "Tablette", "müssen expresa obligación y el infinitivo nehmen va al final.", ["Por la mañana debo tomar esta pastilla."], ["Morgens muss ich diese Tablette nehmen."]),
      phrase("Der Patient soll viel Wasser trinken.", "El paciente debe beber mucha agua.", "Patient", "sollen expresa una recomendación y trinken permanece en infinitivo al final.", ["El paciente tiene que beber mucha agua."]),
      phrase("Kannst du mir den Verband bringen?", "¿Puedes traerme el vendaje?", "Verband", "bringen lleva la persona en dativo mir y el objeto en acusativo.", ["¿Me puedes traer el vendaje?"]),
      phrase("Mir tut seit gestern der Hals weh.", "Me duele la garganta desde ayer.", "gestern", "La persona que siente dolor aparece en dativo: mir.", ["Desde ayer me duele la garganta."]),
      phrase("Die Behandlung hat gut geholfen.", "El tratamiento ha ayudado mucho.", "Behandlung", "helfen forma el Perfekt con haben y expresa que el tratamiento ha sido útil.", ["El tratamiento funcionó bien."]),
    ]),
    lesson("u17-l2", 2, "Rutinas para cuidarse", "Practica verbos reflexivos para hablar de tu salud.", [
      phrase("Ich wasche mir vor dem Essen die Hände.", "Me lavo las manos antes de comer.", "wasche", "waschen usa el pronombre reflexivo en dativo mir cuando se menciona una parte del cuerpo.", ["Antes de comer me lavo las manos."]),
      phrase("Du ziehst dich nach dem Sport schnell um.", "Te cambias rápidamente después de hacer deporte.", "ziehst", "umziehen es separable y el pronombre reflexivo es dich.", ["Después de hacer deporte te cambias rápido."]),
      phrase("Sie freut sich auf den Termin.", "Ella está deseando la cita.", "freut", "sich freuen auf expresa ilusión por algo futuro.", ["Está deseando la cita."]),
      phrase("Wir müssen uns heute ausruhen.", "Hoy tenemos que descansar.", "ausruhen", "Con müssen, el verbo reflexivo permanece unido en infinitivo al final.", ["Hoy debemos descansar."]),
      phrase("Nach dem Lauf fühle ich mich besser.", "Después de correr me siento mejor.", "fühle", "sich fühlen describe el estado de una persona y aquí se combina con besser.", ["Me encuentro mejor después de correr."]),
      phrase("Er interessiert sich für gesunde Ernährung.", "Él se interesa por la alimentación saludable.", "interessiert", "sich interessieren für rige acusativo: für gesunde Ernährung.", ["Le interesa la alimentación sana."]),
    ]),
    lesson("u17-l3", 3, "Comparar síntomas y hábitos", "Compara sensaciones y actividades con adjetivos y adverbios.", [
      phrase("Dieser Tee ist milder als der andere.", "Este té es más suave que el otro.", "milder", "El comparativo de mild es milder y se construye con als.", ["Este té resulta más suave que el otro."]),
      phrase("Meine Schwester schläft heute länger.", "Hoy mi hermana duerme más tiempo.", "Schwester", "länger es el comparativo de lang y modifica la duración del sueño.", ["Hoy duerme más mi hermana."]),
      phrase("Der neue Termin ist am frühesten.", "La nueva cita es la más temprana.", "frühesten", "El superlativo adverbial se forma con am y -sten.", ["La nueva cita es la más temprana de todas."]),
      phrase("Ich fühle mich nach der Pause besser.", "Después del descanso me siento mejor.", "Pause", "besser es el comparativo irregular de gut.", ["Tras la pausa me encuentro mejor."]),
      phrase("Die zweite Übung ist weniger anstrengend.", "El segundo ejercicio es menos agotador.", "zweite", "weniger expresa una comparación de cantidad o intensidad menor.", ["El segundo ejercicio cansa menos."]),
      phrase("Am Wochenende läuft Paul am schnellsten.", "El fin de semana Paul es quien corre más rápido.", "schnellsten", "am schnellsten es el superlativo de schnell.", ["El fin de semana Paul corre más rápido que todos."]),
    ]),
  ]),
  unit("u18", 18, "Casa y vivienda", "Describe habitaciones, muebles y cambios en casa.", [
    lesson("u18-l1", 1, "Mover los muebles", "Distingue movimiento y ubicación con preposiciones de doble caso.", [
      phrase("Ich stelle die Lampe auf den Tisch.", "Coloco la lámpara sobre la mesa.", "stelle", "stellen expresa movimiento hacia un lugar y auf lleva acusativo: auf den Tisch.", ["Pongo la lámpara encima de la mesa."]),
      phrase("Die Lampe steht jetzt auf dem Tisch.", "La lámpara está ahora sobre la mesa.", "Lampe", "stehen expresa ubicación y auf lleva dativo: auf dem Tisch.", ["Ahora la lámpara se encuentra sobre la mesa."], ["Jetzt steht die Lampe auf dem Tisch."]),
      phrase("Wir hängen das Bild an die Wand.", "Colgamos el cuadro en la pared.", "hängen", "Con movimiento hacia la pared, an lleva acusativo: an die Wand.", ["Ponemos el cuadro en la pared."]),
      phrase("Das Bild hängt über dem Sofa.", "El cuadro está colgado sobre el sofá.", "Bild", "La ubicación con über lleva dativo: über dem Sofa.", ["El cuadro cuelga encima del sofá."]),
      phrase("Sie legt die Decke auf das Bett.", "Ella pone la manta sobre la cama.", "legt", "legen expresa movimiento y auf lleva acusativo: auf das Bett.", ["Ella coloca la manta en la cama."]),
      phrase("Die Decke liegt unter dem Kissen.", "La manta está debajo de la almohada.", "Decke", "liegen expresa ubicación y unter lleva dativo: unter dem Kissen.", ["La manta se encuentra bajo la almohada."]),
    ]),
    lesson("u18-l2", 2, "Habitaciones agradables", "Usa terminaciones de adjetivo para describir una vivienda.", [
      phrase("Wir suchen eine helle Wohnung.", "Buscamos un piso luminoso.", "helle", "Con una en acusativo femenino, el adjetivo termina en -e: eine helle Wohnung.", ["Estamos buscando un piso luminoso."]),
      phrase("Das große Wohnzimmer hat zwei Fenster.", "El salón grande tiene dos ventanas.", "große", "Con das en nominativo neutro, el adjetivo termina en -e.", ["El salón amplio tiene dos ventanas."]),
      phrase("Ich kaufe einen neuen Schreibtisch.", "Compro un escritorio nuevo.", "neuen", "En acusativo masculino después de einen, el adjetivo lleva -en.", ["Me compro un escritorio nuevo."]),
      phrase("Die roten Vorhänge passen gut.", "Las cortinas rojas combinan bien.", "roten", "Con die en plural, el adjetivo termina en -en.", ["Las cortinas de color rojo quedan bien."]),
      phrase("Frisches Wasser steht in der Küche.", "Hay agua fresca en la cocina.", "Frisches", "Sin artículo, el adjetivo neutro en nominativo muestra la terminación fuerte -es.", ["En la cocina hay agua fresca."]),
      phrase("Ein ruhiges Zimmer ist mir wichtig.", "Para mí es importante una habitación tranquila.", "ruhiges", "Con ein y un sustantivo neutro, el adjetivo lleva la terminación -es.", ["Una habitación tranquila es importante para mí."]),
    ]),
    lesson("u18-l3", 3, "Cambiar de piso", "Cuenta una mudanza y expresa deseos sobre tu vivienda.", [
      phrase("Wir haben gestern die Küche gestrichen.", "Ayer hemos pintado la cocina.", "gestrichen", "streichen forma el Perfekt con haben y el participio gestrichen.", ["Ayer pintamos la cocina."]),
      phrase("Die Nachbarn helfen uns beim Umzug.", "Los vecinos nos ayudan con la mudanza.", "Nachbarn", "helfen rige dativo; uns es el pronombre de primera persona plural.", ["Los vecinos nos echan una mano con la mudanza."]),
      phrase("Ich möchte in ein größeres Zimmer ziehen.", "Me gustaría mudarme a una habitación más grande.", "größeres", "größer es el comparativo de groß y, con ein neutro, lleva -es.", ["Quiero mudarme a una habitación más grande."]),
      phrase("Der Vermieter zeigt uns den Keller.", "El casero nos enseña el sótano.", "Vermieter", "zeigen lleva el destinatario uns en dativo y den Keller en acusativo.", ["El propietario nos enseña el sótano."]),
      phrase("Kannst du die schwere Kiste tragen?", "¿Puedes llevar la caja pesada?", "schwere", "Con die en acusativo femenino, el adjetivo termina en -e.", ["¿Puedes transportar la caja pesada?"]),
      phrase("Nach dem Umzug ist alles ordentlicher.", "Después de la mudanza todo está más ordenado.", "ordentlicher", "ordentlicher es el comparativo de ordentlich.", ["Después de mudarnos, todo está más ordenado."]),
    ]),
  ]),
  unit("u19", 19, "Trabajo diario", "Habla de tareas, horarios y responsabilidades en el trabajo.", [
    lesson("u19-l1", 1, "Una jornada de trabajo", "Cuenta lo que has hecho durante el día laboral.", [
      phrase("Ich habe gestern lange gearbeitet.", "Ayer he trabajado durante mucho tiempo.", "gearbeitet", "arbeiten forma el Perfekt regular con haben: habe gearbeitet.", ["Ayer trabajé muchas horas."]),
      phrase("Meine Kollegin hat eine Präsentation vorbereitet.", "Mi compañera ha preparado una presentación.", "Kollegin", "vorbereiten es separable en presente, pero su participio preparado es vorbereitet.", ["Mi compañera preparó una presentación."]),
      phrase("Wir sind um acht Uhr angekommen.", "Hemos llegado a las ocho.", "angekommen", "ankommen expresa llegada y forma el Perfekt con sein.", ["Llegamos a las ocho."]),
      phrase("Der Chef hat den Vertrag unterschrieben.", "El jefe ha firmado el contrato.", "unterschrieben", "unterschreiben tiene el participio irregular unterschrieben.", ["El jefe firmó el contrato."]),
      phrase("Am Montag habe ich neue Aufgaben bekommen.", "El lunes he recibido tareas nuevas.", "Montag", "Am Montag ocupa la primera posición y el verbo conjugado sigue en segunda.", ["El lunes recibí tareas nuevas."]),
      phrase("Das Team hat den Kunden freundlich empfangen.", "El equipo ha recibido amablemente al cliente.", "Kunden", "empfangen forma el participio irregular empfangen y el cliente va en acusativo.", ["El equipo recibió al cliente con amabilidad."]),
    ]),
    lesson("u19-l2", 2, "Permisos y obligaciones", "Usa verbos modales para explicar las normas del trabajo.", [
      phrase("Ich muss den Bericht heute abschicken.", "Tengo que enviar hoy el informe.", "Bericht", "müssen expresa obligación y abschicken queda unido en infinitivo al final.", ["Hoy debo enviar el informe."]),
      phrase("Du darfst im Homeoffice arbeiten.", "Puedes trabajar desde casa.", "Homeoffice", "dürfen expresa permiso y arbeiten aparece al final.", ["Tienes permiso para trabajar desde casa."]),
      phrase("Wir sollen die Besprechung verschieben.", "Debemos aplazar la reunión.", "Besprechung", "sollen expresa una instrucción o recomendación.", ["Tenemos que aplazar la reunión."]),
      phrase("Sie kann das Problem schnell lösen.", "Ella puede resolver el problema rápidamente.", "Problem", "können expresa capacidad y lösen queda en infinitivo al final.", ["Puede solucionar el problema rápidamente."]),
      phrase("Ihr wollt morgen früher anfangen.", "Queréis empezar antes mañana.", "anfangen", "wollen expresa intención y el infinitivo anfangen cierra la oración.", ["Mañana queréis empezar más temprano."]),
      phrase("Der Praktikant möchte viel lernen.", "El becario quiere aprender mucho.", "Praktikant", "möchten expresa un deseo cortés y lernen va al final.", ["El becario desea aprender mucho."]),
    ]),
    lesson("u19-l3", 3, "Razones en la oficina", "Explica planes y decisiones con subordinadas sencillas.", [
      phrase("Ich glaube, dass der Plan funktioniert.", "Creo que el plan funciona.", "funktioniert", "Con dass, el verbo conjugado funktioniert va al final de la subordinada.", ["Creo que el plan sale bien."]),
      phrase("Wir bleiben länger, weil die Arbeit noch dauert.", "Nos quedamos más porque el trabajo aún dura.", "dauert", "weil introduce una subordinada y dauert cierra la frase.", ["Nos quedamos más tiempo porque todavía queda trabajo."]),
      phrase("Wenn du Hilfe brauchst, ruf mich an.", "Si necesitas ayuda, llámame.", "brauchst", "En la subordinada con wenn, brauchst va al final; la principal empieza con el imperativo.", ["Si necesitas ayuda, avísame."]),
      phrase("Sie weiß, dass wir morgen kommen.", "Ella sabe que mañana venimos.", "weiß", "wissen se conjuga weiß con sie y la subordinada termina en kommen.", ["Sabe que venimos mañana."]),
      phrase("Er geht früher, weil er einen Termin hat.", "Se va antes porque tiene una cita.", "Termin", "weil introduce la razón y el verbo hat queda al final.", ["Se marcha antes porque tiene una cita."]),
      phrase("Wenn alles fertig ist, feiern wir zusammen.", "Cuando todo esté listo, lo celebramos juntos.", "fertig", "La subordinada con wenn termina en ist y la principal conserva el verbo en segunda posición.", ["Cuando todo esté preparado, lo celebramos juntos."]),
    ]),
  ]),
  unit("u20", 20, "Compras y servicios", "Compra productos, compara precios y gestiona encargos.", [
    lesson("u20-l1", 1, "En la tienda", "Pide productos y usa acusativo y dativo al comprar.", [
      phrase("Ich suche ein Geschenk für meine Tante.", "Busco un regalo para mi tía.", "Geschenk", "suchen lleva el objeto directo en acusativo y für rige acusativo.", ["Estoy buscando un regalo para mi tía."]),
      phrase("Die Verkäuferin zeigt mir eine Jacke.", "La dependienta me enseña una chaqueta.", "Verkäuferin", "zeigen lleva a la persona en dativo mir y el objeto en acusativo.", ["La dependienta me muestra una chaqueta."]),
      phrase("Wir bezahlen die Rechnung an der Kasse.", "Pagamos la cuenta en la caja.", "Rechnung", "bezahlen lleva la factura en acusativo; an der Kasse indica ubicación.", ["Pagamos la factura en la caja."]),
      phrase("Kann ich diese Schuhe anprobieren?", "¿Puedo probarme estos zapatos?", "Schuhe", "anprobieren permanece unido en infinitivo después de kann.", ["¿Me puedo probar estos zapatos?"]),
      phrase("Der Kunde gibt dem Kassierer seine Karte.", "El cliente da su tarjeta al cajero.", "Kassierer", "El destinatario va en dativo: dem Kassierer.", ["El cliente le entrega su tarjeta al cajero."]),
      phrase("Ich nehme eine kleinere Größe.", "Elijo una talla más pequeña.", "kleinere", "kleinere es un comparativo con una en acusativo femenino.", ["Cojo una talla más pequeña."]),
    ]),
    lesson("u20-l2", 2, "Comparar productos", "Compara precios, tamaños y características.", [
      phrase("Dieses Fahrrad ist leichter als mein altes.", "Esta bicicleta es más ligera que la mía antigua.", "leichter", "El comparativo leichter se combina con als para comparar.", ["Esta bici pesa menos que la antigua."]),
      phrase("Die blaue Tasche ist am teuersten.", "El bolso azul es el más caro.", "teuersten", "El superlativo predicativo usa am teuersten.", ["La bolsa azul es la más cara."]),
      phrase("Heute ist das Angebot besser.", "Hoy la oferta es mejor.", "Angebot", "besser es el comparativo irregular de gut.", ["La oferta de hoy es mejor."]),
      phrase("Dieses Modell gefällt mir am besten.", "Este modelo es el que más me gusta.", "Modell", "am besten es el superlativo irregular de gut.", ["Este modelo me gusta más que los demás."]),
      phrase("Der rote Pullover ist genauso warm wie der schwarze.", "El jersey rojo es igual de cálido que el negro.", "rote", "genauso ... wie expresa igualdad; el adjetivo lleva -e con der.", ["El jersey rojo abriga tanto como el negro."]),
      phrase("Ich kaufe die günstigere Variante.", "Compro la opción más barata.", "günstigere", "günstigere es el comparativo de günstig con die en acusativo femenino.", ["Elijo la alternativa más económica."]),
    ]),
    lesson("u20-l3", 3, "Pedidos y devoluciones", "Cuenta compras recientes y resuelve problemas con un pedido.", [
      phrase("Ich habe gestern ein Paket abgeholt.", "Ayer he recogido un paquete.", "Paket", "abholen forma el Perfekt con haben y el participio abgeholt.", ["Ayer recogí un paquete."]),
      phrase("Die Post hat das Formular geschickt.", "Correos ha enviado el formulario.", "Formular", "schicken forma el Perfekt regular geschickt.", ["Correos envió el formulario."]),
      phrase("Wir haben online einen Termin gebucht.", "Hemos reservado una cita por internet.", "gebucht", "buchen forma el participio regular gebucht.", ["Reservamos una cita por internet."]),
      phrase("Sie hat dem Kunden eine E-Mail geschrieben.", "Ella ha escrito un correo al cliente.", "Kunden", "El destinatario aparece en dativo: dem Kunden; schreiben tiene el participio geschrieben.", ["Ha escrito un correo electrónico al cliente."]),
      phrase("Der Laden ist schon geschlossen.", "La tienda ya está cerrada.", "geschlossen", "geschlossen funciona como participio de schließen y describe un estado.", ["La tienda ya ha cerrado."]),
      phrase("Ich habe meine Bestellung bezahlt.", "He pagado mi pedido.", "Bestellung", "bezahlen forma el Perfekt con haben.", ["Pagué mi pedido."]),
    ]),
  ]),
  unit("u21", 21, "Tiempo libre y deporte", "Habla de aficiones, planes y actividades después de clase o trabajo.", [
    lesson("u21-l1", 1, "Aficiones reflexivas", "Explica qué actividades te interesan y cómo te organizas.", [
      phrase("Ich interessiere mich für Fotografie.", "Me intereso por la fotografía.", "interessiere", "sich interessieren für rige acusativo y es un verbo reflexivo.", ["Me interesa la fotografía."]),
      phrase("Wir treffen uns nach dem Kurs.", "Quedamos después del curso.", "treffen", "sich treffen expresa que dos o más personas quedan.", ["Nos vemos después del curso."]),
      phrase("Er wäscht sich jeden Abend die Hände.", "Él se lava las manos todas las noches.", "wäscht", "waschen usa el pronombre reflexivo sich y el objeto en acusativo.", ["Todas las noches se lava las manos."]),
      phrase("Sie freut sich über das Geschenk.", "Ella se alegra del regalo.", "freut", "sich freuen über expresa alegría por algo que ya ocurre.", ["Está contenta por el regalo."]),
      phrase("Du musst dich heute anmelden.", "Hoy tienes que inscribirte.", "anmelden", "Con musst, anmelden permanece unido en infinitivo.", ["Hoy debes apuntarte."]),
      phrase("Nach der Arbeit ruhe ich mich aus.", "Después del trabajo descanso.", "ruhe", "sich ausruhen es separable: ruhe va en segunda posición y aus al final.", ["Después de trabajar me tomo un descanso."]),
    ]),
    lesson("u21-l2", 2, "Deportes y preferencias", "Compara actividades y expresa tus preferencias.", [
      phrase("Der neue Film ist spannender als der alte.", "La película nueva es más emocionante que la antigua.", "spannender", "El comparativo spannender se combina con als.", ["La película nueva tiene más emoción que la antigua."]),
      phrase("Meine Freundin tanzt am liebsten Salsa.", "Mi amiga prefiere bailar salsa.", "liebsten", "am liebsten expresa la preferencia máxima de gern.", ["A mi amiga le gusta bailar salsa sobre todo."]),
      phrase("Dieses Spiel ist weniger kompliziert.", "Este juego es menos complicado.", "kompliziert", "weniger expresa un grado menor del adjetivo.", ["Este juego resulta más sencillo."]),
      phrase("Wir fahren lieber ans Meer.", "Preferimos ir al mar.", "lieber", "lieber es el comparativo irregular de gern.", ["Preferimos viajar a la costa."]),
      phrase("Der rote Ball ist größer als der blaue.", "La pelota roja es más grande que la azul.", "größer", "größer es el comparativo de groß y lleva umlaut.", ["El balón rojo es mayor que el azul."]),
      phrase("Am Sonntag spielt unser Team am besten.", "El domingo nuestro equipo juega mejor que todos.", "besten", "am besten es el superlativo irregular de gut.", ["El domingo nuestro equipo juega de maravilla."]),
    ]),
    lesson("u21-l3", 3, "Un fin de semana activo", "Cuenta actividades que has hecho durante el fin de semana.", [
      phrase("Wir haben gestern im See geschwommen.", "Ayer hemos nadado en el lago.", "geschwommen", "schwimmen forma el Perfekt con haben cuando se habla de la actividad.", ["Ayer nadamos en el lago."]),
      phrase("Ich bin mit Freunden gewandert.", "He hecho senderismo con amigos.", "gewandert", "wandern forma el Perfekt con sein cuando expresa desplazamiento.", ["Hice senderismo con amigos."]),
      phrase("Sie hat ein Konzert besucht.", "Ella ha asistido a un concierto.", "Konzert", "besuchen forma el Perfekt con haben.", ["Ella fue a un concierto."]),
      phrase("Die Kinder haben lange getanzt.", "Los niños han bailado durante mucho tiempo.", "getanzt", "tanzen forma el participio regular getanzt.", ["Los niños bailaron mucho rato."]),
      phrase("Er ist früh nach Hause gegangen.", "Él se ha ido pronto a casa.", "gegangen", "gehen expresa desplazamiento y forma el Perfekt con sein.", ["Se fue temprano a casa."]),
      phrase("Du hast einen spannenden Roman gelesen.", "Has leído una novela emocionante.", "Roman", "lesen tiene el participio irregular gelesen.", ["Leíste una novela apasionante."]),
    ]),
  ]),
  unit("u22", 22, "Medios y comunicación", "Entiende mensajes, programas y opiniones sobre los medios.", [
    lesson("u22-l1", 1, "Mensajes y noticias", "Explica qué sabes y por qué sigues una noticia.", [
      phrase("Ich weiß, dass die Nachricht stimmt.", "Sé que la noticia es cierta.", "Nachricht", "wissen se conjuga weiß y dass coloca stimmt al final de la subordinada.", ["Sé que la noticia es verdad."]),
      phrase("Sie sagt, dass der Film um neun beginnt.", "Ella dice que la película empieza a las nueve.", "beginnt", "Con dass, el verbo beginnt cierra la subordinada.", ["Dice que la película empieza a las nueve."]),
      phrase("Wir bleiben online, weil die Sendung interessant ist.", "Seguimos conectados porque el programa es interesante.", "Sendung", "weil introduce una subordinada y ist queda al final.", ["Seguimos en línea porque el programa resulta interesante."]),
      phrase("Wenn das Internet ausfällt, rufe ich dich an.", "Si falla internet, te llamo.", "ausfällt", "En la subordinada con wenn, ausfällt cierra la frase; anrufen se separa en la principal.", ["Si se cae internet, te llamaré."]),
      phrase("Er glaubt, dass seine Antwort richtig ist.", "Él cree que su respuesta es correcta.", "Antwort", "La subordinada con dass termina en ist.", ["Cree que su respuesta es correcta."]),
      phrase("Ich lese die Zeitung, weil ich informiert sein möchte.", "Leo el periódico porque quiero estar informado.", "Zeitung", "weil introduce la razón y möchte queda al final después del infinitivo sein.", ["Leo el periódico porque quiero mantenerme informado."]),
    ]),
    lesson("u22-l2", 2, "Programas y preferencias", "Compara formatos y expresa qué medio prefieres.", [
      phrase("Dieser Podcast ist kürzer als die Sendung.", "Este pódcast es más corto que el programa.", "kürzer", "kürzer es el comparativo de kurz y se combina con als.", ["Este pódcast dura menos que el programa."]),
      phrase("Die neue App ist am einfachsten.", "La aplicación nueva es la más fácil.", "einfachsten", "am einfachsten es el superlativo de einfach.", ["La nueva aplicación resulta la más sencilla."]),
      phrase("Mein Bruder hört genauso gern Radio wie ich.", "A mi hermano le gusta la radio tanto como a mí.", "Bruder", "genauso gern ... wie expresa igualdad de preferencia.", ["A mi hermano le gusta escuchar la radio tanto como a mí."]),
      phrase("Die zweite Nachricht ist wichtiger.", "El segundo mensaje es más importante.", "zweite", "wichtiger es el comparativo de wichtig y zweite lleva una terminación débil.", ["El segundo mensaje tiene más importancia."]),
      phrase("Dieses Video gefällt mir besser.", "Este vídeo me gusta más.", "Video", "gefallen rige dativo mir y besser es el comparativo de gut.", ["Prefiero este vídeo."]),
      phrase("Am liebsten lese ich lange Interviews.", "Lo que más me gusta es leer entrevistas largas.", "liebsten", "am liebsten expresa la preferencia máxima de gern.", ["Prefiero leer entrevistas extensas."]),
    ]),
    lesson("u22-l3", 3, "Contar lo que has visto", "Habla de programas, entrevistas y textos recientes.", [
      phrase("Ich habe die E-Mail sofort beantwortet.", "He respondido el correo inmediatamente.", "E-Mail", "beantworten forma el Perfekt con haben.", ["Respondí el correo enseguida."]),
      phrase("Wir haben gestern einen Film gestreamt.", "Ayer hemos visto una película en streaming.", "gestreamt", "streamen usa el participio regular gestreamt.", ["Ayer vimos una película en streaming."]),
      phrase("Die Moderatorin hat viele Fragen gestellt.", "La presentadora ha hecho muchas preguntas.", "Moderatorin", "stellen forma el participio irregular gestellt.", ["La presentadora planteó muchas preguntas."]),
      phrase("Er hat den Artikel gründlich gelesen.", "Él ha leído el artículo a fondo.", "Artikel", "lesen tiene el participio irregular gelesen.", ["Leyó el artículo detenidamente."]),
      phrase("Sie ist im Interview ruhig geblieben.", "Ella se ha mantenido tranquila en la entrevista.", "Interview", "bleiben expresa permanencia y forma el Perfekt con sein.", ["Se mantuvo tranquila durante la entrevista."]),
      phrase("Die Redaktion hat die Meldung geprüft.", "La redacción ha comprobado la noticia.", "Redaktion", "prüfen forma el Perfekt regular geprüft.", ["La redacción verificó la información."]),
    ]),
  ]),
  unit("u23", 23, "Naturaleza y ciudad", "Describe el tiempo, los espacios urbanos y hábitos sostenibles.", [
    lesson("u23-l1", 1, "El tiempo cambia", "Relaciona el tiempo atmosférico con tus planes.", [
      phrase("Wenn die Sonne scheint, gehen wir spazieren.", "Si hace sol, salimos a pasear.", "scheint", "En la subordinada con wenn, scheint va al final y la principal empieza con gehen.", ["Cuando hace sol, salimos a pasear."]),
      phrase("Der Wind hat in der Nacht zugenommen.", "El viento ha aumentado durante la noche.", "Wind", "zunehmen forma el Perfekt con haben y el participio zugenommen.", ["El viento aumentó por la noche."]),
      phrase("Wir bleiben drinnen, weil es stürmt.", "Nos quedamos dentro porque hay tormenta.", "stürmt", "weil introduce la causa y stürmt cierra la subordinada.", ["Nos quedamos en casa porque hay tormenta."]),
      phrase("Am Morgen ist dichter Nebel entstanden.", "Por la mañana se ha formado una niebla densa.", "Nebel", "entstehen expresa un cambio y forma el Perfekt con sein.", ["Por la mañana apareció una niebla espesa."]),
      phrase("Die Temperaturen sind plötzlich gefallen.", "Las temperaturas han bajado de repente.", "Temperaturen", "fallen expresa un cambio y forma el Perfekt con sein.", ["Las temperaturas bajaron de repente."]),
      phrase("Ich hoffe, dass das Wetter besser wird.", "Espero que mejore el tiempo.", "Wetter", "Con dass, wird queda al final de la subordinada.", ["Espero que haga mejor tiempo."]),
    ]),
    lesson("u23-l2", 2, "Moverse por la ciudad", "Usa las preposiciones de doble caso para indicar posición y destino.", [
      phrase("Ich stelle das Fahrrad vor das Haus.", "Coloco la bicicleta delante de la casa.", "Fahrrad", "stellen expresa movimiento y vor lleva acusativo: vor das Haus.", ["Pongo la bici delante de la casa."]),
      phrase("Das Fahrrad steht vor dem Haus.", "La bicicleta está delante de la casa.", "Fahrrad", "stehen expresa ubicación y vor lleva dativo: vor dem Haus.", ["La bici se encuentra delante de la casa."]),
      phrase("Wir legen die Karte neben den Rucksack.", "Ponemos el mapa junto a la mochila.", "Karte", "legen expresa movimiento y neben lleva acusativo.", ["Colocamos el mapa al lado de la mochila."]),
      phrase("Die Karte liegt neben dem Rucksack.", "El mapa está junto a la mochila.", "Karte", "liegen expresa ubicación y neben lleva dativo.", ["El mapa se encuentra al lado de la mochila."]),
      phrase("Sie hängt das Schild an die Tür.", "Cuelga el cartel en la puerta.", "Schild", "hängen expresa movimiento hacia la puerta y an lleva acusativo.", ["Pone el cartel en la puerta."]),
      phrase("Das Schild hängt über dem Eingang.", "El cartel cuelga sobre la entrada.", "Schild", "La ubicación con über lleva dativo: über dem Eingang.", ["El cartel está colgado encima de la entrada."]),
    ]),
    lesson("u23-l3", 3, "Una ciudad más verde", "Compara lugares y expresa hábitos respetuosos con el medio ambiente.", [
      phrase("Der neue Park ist größer als der alte.", "El parque nuevo es más grande que el antiguo.", "Park", "größer es el comparativo de groß y se construye con als.", ["El parque nuevo tiene más tamaño que el antiguo."]),
      phrase("Diese Straße ist am saubersten.", "Esta calle es la más limpia.", "saubersten", "am saubersten es el superlativo de sauber.", ["Esta es la calle más limpia."]),
      phrase("Wir trennen den Müll sorgfältig.", "Separamos la basura con cuidado.", "Müll", "trennen lleva el objeto directo den Müll en acusativo.", ["Clasificamos la basura con cuidado."]),
      phrase("Ich benutze lieber den Zug als das Auto.", "Prefiero usar el tren al coche.", "benutze", "lieber expresa preferencia y als introduce la alternativa comparada.", ["Prefiero ir en tren que en coche."]),
      phrase("Die Innenstadt ist weniger ruhig als der Stadtrand.", "El centro es menos tranquilo que las afueras.", "Innenstadt", "weniger ... als expresa una comparación de inferioridad.", ["El centro tiene menos tranquilidad que las afueras."]),
      phrase("Am Wochenende ist der See am schönsten.", "El lago está más bonito el fin de semana.", "schönsten", "am schönsten es el superlativo de schön.", ["El lago está precioso durante el fin de semana."]),
    ]),
  ]),
  unit("u24", 24, "Estudios y aprendizaje", "Habla de clases, tareas y estrategias para aprender.", [
    lesson("u24-l1", 1, "Lo que has estudiado", "Cuenta las tareas que has hecho para una prueba.", [
      phrase("Ich habe gestern für die Prüfung gelernt.", "Ayer he estudiado para el examen.", "Prüfung", "lernen forma el Perfekt con haben.", ["Ayer estudié para el examen."]),
      phrase("Wir haben die Aufgabe gemeinsam gelöst.", "Hemos resuelto el ejercicio juntos.", "gelöst", "lösen forma el participio regular gelöst.", ["Resolvimos el ejercicio entre todos."]),
      phrase("Die Studentin hat den Text zusammengefasst.", "La estudiante ha resumido el texto.", "Studentin", "zusammenfassen forma el Perfekt con haben.", ["La alumna resumió el texto."]),
      phrase("Er ist nach dem Unterricht nach Hause gegangen.", "Después de clase se ha ido a casa.", "Unterricht", "gehen expresa desplazamiento y forma el Perfekt con sein.", ["Después de clase fue a casa."]),
      phrase("Du hast die Vokabeln wiederholt.", "Has repasado el vocabulario.", "Vokabeln", "wiederholen forma el participio regular wiederholt.", ["Repasaste las palabras."]),
      phrase("Unsere Gruppe hat lange diskutiert.", "Nuestro grupo ha debatido durante mucho tiempo.", "Gruppe", "diskutieren forma el Perfekt regular diskutiert.", ["Nuestro grupo debatió durante mucho rato."]),
    ]),
    lesson("u24-l2", 2, "Consejos para la clase", "Usa verbos modales para hablar de tareas y posibilidades.", [
      phrase("Ich muss den Aufsatz bis morgen abgeben.", "Tengo que entregar la redacción antes de mañana.", "Aufsatz", "müssen expresa obligación y abgeben queda en infinitivo al final.", ["Debo entregar la redacción mañana como muy tarde."]),
      phrase("Du kannst die Frage noch einmal erklären.", "Puedes explicar la pregunta otra vez.", "erklären", "können expresa capacidad y erklären va al final.", ["Puedes volver a explicar la pregunta."]),
      phrase("Wir sollen die Grammatik wiederholen.", "Debemos repasar la gramática.", "Grammatik", "sollen expresa una recomendación o tarea indicada.", ["Tenemos que repasar la gramática."]),
      phrase("Sie darf während der Pause telefonieren.", "Ella puede hablar por teléfono durante el recreo.", "Pause", "dürfen expresa permiso y telefonieren va al final.", ["Tiene permiso para llamar durante el descanso."]),
      phrase("Ihr möchtet in Berlin studieren.", "Os gustaría estudiar en Berlín.", "studieren", "möchten expresa un deseo y el infinitivo studieren cierra la oración.", ["Queréis estudiar en Berlín."]),
      phrase("Der Kursleiter will die Prüfung verschieben.", "El profesor quiere aplazar el examen.", "Kursleiter", "wollen expresa intención y verschieben va al final.", ["El coordinador del curso quiere aplazar el examen."]),
    ]),
    lesson("u24-l3", 3, "Planes de aprendizaje", "Combina wenn, dass y weil para explicar cómo estudias.", [
      phrase("Ich hoffe, dass ich die Aufgabe schaffe.", "Espero que consiga hacer el ejercicio.", "schaffe", "Con dass, schaffe queda al final de la subordinada.", ["Espero que pueda resolver el ejercicio."]),
      phrase("Wenn ich Zeit habe, lese ich das Kapitel.", "Si tengo tiempo, leo el capítulo.", "Kapitel", "La subordinada con wenn termina en habe y la principal empieza con lese.", ["Cuando tengo tiempo, leo el capítulo."]),
      phrase("Wir lernen weiter, weil die Prüfung bald stattfindet.", "Seguimos estudiando porque el examen es pronto.", "stattfindet", "stattfinden es separable, pero en la subordinada aparece unido al final.", ["Seguimos estudiando porque el examen se celebra pronto."]),
      phrase("Sie weiß, dass der Kurs morgen endet.", "Ella sabe que el curso termina mañana.", "endet", "Con dass, endet cierra la subordinada.", ["Sabe que el curso acaba mañana."]),
      phrase("Wenn du regelmäßig übst, machst du Fortschritte.", "Si practicas con regularidad, progresas.", "regelmäßig", "regelmäßig describe la frecuencia de übst y la subordinada conserva el verbo al final.", ["Cuando practicas a menudo, avanzas."]),
      phrase("Er bleibt zu Hause, weil er krank ist.", "Se queda en casa porque está enfermo.", "krank", "weil introduce la razón y ist va al final.", ["Él se queda en casa porque está enfermo."]),
    ]),
  ]),
];
