import type { LessonDraft, Phrase, UnitDraft } from "./units";

const phrase = (
  german: string,
  spanish: string,
  blankWord: string,
  explanation: string,
  spanishAlt?: string[],
  germanAlt?: string[],
): Phrase => ({
  german,
  spanish,
  blankWord,
  explanation,
  ...(spanishAlt ? { spanishAlt } : {}),
  ...(germanAlt ? { germanAlt } : {}),
});

const lesson = (
  id: string,
  order: number,
  title: string,
  description: string,
  phrases: Phrase[],
): LessonDraft => ({ id, order, title, description, xpReward: 10, phrases });

const unit = (
  id: string,
  order: number,
  title: string,
  description: string,
  lessons: LessonDraft[],
): UnitDraft => ({
  id,
  order,
  title,
  description,
  color: "#FF4B4B",
  cefrLevel: "B2.1",
  lessons,
});

export const b2_1UnitDrafts: UnitDraft[] = [
  unit("u43", 43, "Noticias y declaraciones", "Transmite información y atribuye opiniones a sus fuentes.", [
    lesson("u43-l1", 1, "Declaraciones oficiales", "Usa el Konjunktiv I en noticias y comunicados.", [
      phrase("Die Sprecherin sagt, die Reform sei bereits beschlossen.", "La portavoz dice que la reforma ya está aprobada.", "Reform", "sei es Konjunktiv I y atribuye a la portavoz la información sobre la reforma.", ["Según la portavoz, la reforma ya está aprobada."]),
      phrase("Der Minister erklärt, man werde die Schulen entlasten.", "El ministro explica que se reducirá la carga de los colegios.", "Minister", "werde es Konjunktiv I de werden en discurso indirecto.", ["El ministro anuncia medidas para aliviar la carga de los centros."], ["Man werde die Schulen entlasten, erklärt der Minister."]),
      phrase("Die Zeitung meldet, die Wahlbeteiligung sei gestiegen.", "El periódico informa de que ha aumentado la participación electoral.", "Wahlbeteiligung", "sei gestiegen reproduce indirectamente el dato comunicado por el periódico.", ["Según el periódico, ha subido la participación en las elecciones."]),
      phrase("Ein Sprecher betont, die Entscheidung gelte für alle Regionen.", "Un portavoz subraya que la decisión se aplica a todas las regiones.", "Entscheidung", "gelte es Konjunktiv I y transmite una declaración atribuida.", ["El portavoz recalca que la medida afecta a todas las regiones."]),
      phrase("Die Behörde teilt mit, der Bericht sei veröffentlicht worden.", "La autoridad comunica que se ha publicado el informe.", "Behörde", "sei veröffentlicht worden forma el Konjunktiv I del perfecto pasivo.", ["Según la autoridad, el informe ya ha sido publicado."]),
      phrase("Der Regierungschef sagt, er plane neue Maßnahmen.", "El jefe del Gobierno dice que prepara nuevas medidas.", "Regierungschef", "plane es Konjunktiv I de planen en una declaración indirecta."),
    ]),
    lesson("u43-l2", 2, "Sucesos y testimonios", "Reproduce lo que declaran testigos y fuentes.", [
      phrase("Die Polizei erklärt, der Verkehr werde umgeleitet.", "La policía explica que se está desviando el tráfico.", "Polizei", "werde umgeleitet es Konjunktiv I pasivo en discurso indirecto.", ["Según la policía, el tráfico se desvía por otra ruta."]),
      phrase("Der Zeuge sagt, er habe das Auto gesehen.", "El testigo dice que vio el coche.", "Zeuge", "habe gesehen transmite en Konjunktiv I lo que afirma el testigo.", ["El testigo asegura haber visto el coche."], ["Er habe das Auto gesehen, sagt der Zeuge."]),
      phrase("Die Redaktion berichtet, die Lage bleibe angespannt.", "La redacción informa de que la situación sigue siendo tensa.", "Redaktion", "bleibe es Konjunktiv I de bleiben y atribuye la valoración a la redacción.", ["Según la redacción, la situación continúa tensa."]),
      phrase("Nach Angaben der Stadt seien alle Schulen geöffnet.", "Según el ayuntamiento, todos los colegios están abiertos.", "Stadt", "seien es Konjunktiv I plural en una declaración indirecta.", ["La ciudad afirma que todos los centros educativos están abiertos."]),
      phrase("Der Leiter erklärt, die Sitzung beginne pünktlich.", "El responsable explica que la reunión empezará puntual.", "Leiter", "beginne reproduce indirectamente la declaración del responsable.", ["El responsable asegura que la reunión empezará a su hora."]),
      phrase("Die Agentur meldet, der Vertrag trete im Juni in Kraft.", "La agencia informa de que el contrato entrará en vigor en junio.", "Agentur", "trete es Konjunktiv I de treten en discurso indirecto.", ["Según la agencia, el contrato empezará a aplicarse en junio."]),
    ]),
    lesson("u43-l3", 3, "Debates y propuestas", "Distingue los hechos de las declaraciones citadas.", [
      phrase("Die Bürgermeisterin sagt, die Stadt werde neue Wohnungen bauen.", "La alcaldesa dice que el ayuntamiento construirá nuevas viviendas.", "Bürgermeisterin", "werde bauen transmite el anuncio de la alcaldesa en Konjunktiv I.", ["La alcaldesa anuncia que se construirán viviendas nuevas."]),
      phrase("Der Ausschuss erklärt, er habe den Plan verändert.", "El comité explica que ha modificado el plan.", "Ausschuss", "habe verändert es Konjunktiv I perfecto y refiere una declaración.", ["El comité afirma que ha introducido cambios en el plan."], ["Er habe den Plan verändert, erklärt der Ausschuss."]),
      phrase("Laut dem Bericht seien die Kosten deutlich gesunken.", "Según el informe, los costes han bajado considerablemente.", "Bericht", "seien gesunken transmite de forma indirecta la información del informe.", ["El informe señala una importante bajada de los costes."]),
      phrase("Die Sprecherin betont, die Maßnahme wirke sofort.", "La portavoz subraya que la medida surte efecto de inmediato.", "Maßnahme", "wirke es Konjunktiv I y atribuye el efecto a la declaración citada.", ["Según la portavoz, la medida tiene efecto inmediato."]),
      phrase("Der Verband teilt mit, die Gespräche dauerten noch an.", "La asociación comunica que las conversaciones siguen en curso.", "Verband", "dauerten es Konjunktiv II sustitutivo porque la forma plural coincide con el indicativo.", ["La asociación indica que las negociaciones todavía continúan."]),
      phrase("Die Zeitung berichtet, der Vorschlag werde erneut geprüft.", "El periódico informa de que volverán a examinar la propuesta.", "Vorschlag", "werde geprüft es Konjunktiv I pasivo y mantiene la fuente explícita.", ["Según el periódico, la propuesta se revisará de nuevo."]),
    ]),
  ]),
  unit("u44", 44, "Educación y formación", "Comprende informes, procesos y cambios educativos.", [
    lesson("u44-l1", 1, "Solicitudes de formación", "Usa sustantivos de acción en contextos formales.", [
      phrase("Die Prüfung des Antrags dauert mehrere Wochen.", "La revisión de la solicitud dura varias semanas.", "Antrags", "Prüfung convierte prüfen en un sustantivo y des Antrags indica qué se revisa.", ["El estudio de la solicitud puede tardar varias semanas."]),
      phrase("Nach der Genehmigung beginnt der Umbau.", "Las obras empiezan tras la autorización.", "Genehmigung", "Nach der Genehmigung presenta el momento mediante un sustantivo.", ["El proyecto empieza una vez concedido el permiso."], ["Der Umbau beginnt nach der Genehmigung."]),
      phrase("Die Einführung des Systems senkte die Verwaltungskosten.", "La implantación del sistema redujo los gastos administrativos.", "Einführung", "Einführung nominaliza einführen y funciona como sujeto de la oración.", ["Implantar el sistema permitió reducir los costes de gestión."]),
      phrase("Zur Verbesserung der Kurse befragte die Schule die Teilnehmenden.", "Para mejorar los cursos, el centro consultó a los participantes.", "Verbesserung", "Verbesserung es el sustantivo de verbessern y depende de zur.", ["El centro pidió opinión a los alumnos para mejorar los cursos."]),
      phrase("Bei der Anmeldung ist ein Ausweis vorzulegen.", "Al inscribirse, hay que presentar un documento de identidad.", "Anmeldung", "Anmeldung es un sustantivo de acción tras la preposición bei.", ["Para la inscripción, es necesario presentar el DNI."]),
      phrase("Die Beschäftigung mit dem Thema erfordert Geduld.", "Trabajar a fondo el tema requiere paciencia.", "Thema", "Beschäftigung nominaliza beschäftigen y funciona como sujeto.", ["El estudio del tema exige paciencia."]),
    ]),
    lesson("u44-l2", 2, "Cambios en los centros", "Describe medidas y resultados con estilo nominal.", [
      phrase("Die Erweiterung der Bibliothek schafft neue Lernplätze.", "La ampliación de la biblioteca crea nuevos espacios de estudio.", "Erweiterung", "Erweiterung es un sustantivo derivado de erweitern.", ["Ampliar la biblioteca permite crear nuevos puestos de estudio."]),
      phrase("Nach Abschluss des Semesters werden die Ergebnisse veröffentlicht.", "Al terminar el semestre, se publicarán los resultados.", "Abschluss", "Nach Abschluss usa un sustantivo para expresar el momento.", ["Los resultados se publicarán una vez acabado el semestre."], ["Die Ergebnisse werden nach Abschluss des Semesters veröffentlicht."]),
      phrase("Die Teilnahme an der Beratung ist freiwillig.", "La participación en la orientación es voluntaria.", "Teilnahme", "Teilnahme nominaliza teilnehmen y rige an más dativo.", ["Asistir a la sesión de orientación es opcional."]),
      phrase("Zur Finanzierung des Projekts beantragte die Hochschule Fördermittel.", "La universidad solicitó ayudas para financiar el proyecto.", "Finanzierung", "Finanzierung es el sustantivo de finanzieren tras zur.", ["La universidad pidió subvenciones para cubrir el proyecto."]),
      phrase("Die Auswertung der Umfrage zeigt klare Unterschiede.", "El análisis de la encuesta muestra diferencias claras.", "Auswertung", "Auswertung nominaliza auswerten y funciona como sujeto.", ["Al analizar la encuesta, se observan diferencias claras."]),
      phrase("Bei der Auswahl der Bewerber gelten transparente Kriterien.", "En la selección de candidatos se aplican criterios transparentes.", "Auswahl", "Auswahl convierte auswählen en un sustantivo femenino.", ["La selección de candidaturas se basa en criterios transparentes."]),
    ]),
    lesson("u44-l3", 3, "Investigación y estudio", "Expresa procesos mediante nominalizaciones precisas.", [
      phrase("Die Entwicklung neuer Lehrmethoden braucht Zeit.", "El desarrollo de nuevos métodos docentes requiere tiempo.", "Entwicklung", "Entwicklung nominaliza entwickeln y funciona como sujeto.", ["Desarrollar métodos de enseñanza nuevos lleva tiempo."]),
      phrase("Nach der Veröffentlichung diskutierten viele Fachleute die Studie.", "Tras la publicación, muchos especialistas debatieron el estudio.", "Veröffentlichung", "Nach der Veröffentlichung sitúa el debate después de un sustantivo de acción.", ["Muchos expertos debatieron el estudio una vez publicado."]),
      phrase("Die Vermittlung praktischer Kenntnisse gehört zum Lehrplan.", "La enseñanza de conocimientos prácticos forma parte del plan de estudios.", "Vermittlung", "Vermittlung es el sustantivo de vermitteln.", ["El programa incluye la transmisión de conocimientos prácticos."]),
      phrase("Zur Vorbereitung auf die Prüfung übt sie täglich.", "Para prepararse para el examen, practica a diario.", "Vorbereitung", "Vorbereitung nominaliza vorbereiten y aparece tras zur.", ["Practica cada día como preparación para el examen."]),
      phrase("Die Bewertung der Arbeiten erfolgt anonym.", "La evaluación de los trabajos se realiza de forma anónima.", "Bewertung", "Bewertung convierte bewerten en un sustantivo de acción.", ["Los trabajos se corrigen de manera anónima."]),
      phrase("Die Zusammenarbeit mit Betrieben erleichtert den Berufseinstieg.", "La colaboración con empresas facilita el acceso al mundo laboral.", "Zusammenarbeit", "Zusammenarbeit es un sustantivo que resume zusammenarbeiten.", ["Colaborar con empresas ayuda a incorporarse al mercado laboral."]),
    ]),
  ]),
  unit("u45", 45, "Ciencia y tecnología", "Lee descripciones técnicas y resultados de investigación.", [
    lesson("u45-l1", 1, "Métodos de investigación", "Comprende atributos participiales ampliados.", [
      phrase("Die von mehreren Instituten untersuchte Methode senkt den Energieverbrauch.", "El método estudiado por varios institutos reduce el consumo energético.", "Methode", "von mehreren Instituten untersuchte es un atributo participial que precisa el método.", ["El método que han estudiado varios institutos consume menos energía."]),
      phrase("Die im letzten Jahr entwickelten Sensoren messen die Luftqualität.", "Los sensores desarrollados el año pasado miden la calidad del aire.", "Sensoren", "im letzten Jahr entwickelten describe con Partizip II los sensores.", ["Los sensores creados el año pasado analizan la calidad del aire."], ["Die Sensoren, die im letzten Jahr entwickelt wurden, messen die Luftqualität."]),
      phrase("Ein in der Arktis entdeckter Gletscher verliert rasch an Masse.", "Un glaciar descubierto en el Ártico pierde masa rápidamente.", "Gletscher", "in der Arktis entdeckter es un atributo participial de Gletscher.", ["Un glaciar que se descubrió en el Ártico está perdiendo masa con rapidez."]),
      phrase("Die von der Universität veröffentlichte Studie bestätigt den Trend.", "El estudio publicado por la universidad confirma la tendencia.", "Universität", "von der Universität veröffentlichte modifica Studie mediante Partizip II.", ["La tendencia queda confirmada por el estudio que publicó la universidad."]),
      phrase("Forscher analysieren im Labor gespeicherte Bodenproben.", "Los investigadores analizan muestras de suelo conservadas en el laboratorio.", "Bodenproben", "im Labor gespeicherte es un atributo participial que describe las muestras.", ["En el laboratorio, los investigadores estudian muestras de suelo almacenadas."]),
      phrase("Die während der Messung aufgezeichneten Daten bleiben verfügbar.", "Los datos registrados durante la medición siguen disponibles.", "Messung", "während der Messung aufgezeichneten precisa cuáles son los datos.", ["Siguen disponibles los datos que se registraron durante la medición."]),
    ]),
    lesson("u45-l2", 2, "Datos y descubrimientos", "Describe experimentos, materiales y conclusiones.", [
      phrase("Das von einem Forschungsteam gebaute Gerät arbeitet besonders präzise.", "El aparato construido por un equipo de investigación funciona con especial precisión.", "Gerät", "von einem Forschungsteam gebaute es un atributo participial de Gerät.", ["El equipo de investigación construyó un aparato que funciona con gran precisión."]),
      phrase("Die aus recyceltem Kunststoff gefertigten Bauteile sind sehr leicht.", "Las piezas fabricadas con plástico reciclado son muy ligeras.", "Bauteile", "aus recyceltem Kunststoff gefertigten describe el material de las piezas.", ["Estas piezas, elaboradas con plástico reciclado, pesan muy poco."], ["Die Bauteile sind aus recyceltem Kunststoff gefertigt und sehr leicht."]),
      phrase("Ein in mehreren Ländern erprobtes Verfahren spart Wasser.", "Un procedimiento probado en varios países ahorra agua.", "Verfahren", "in mehreren Ländern erprobtes modifica el sustantivo neutro Verfahren.", ["El método que se ha ensayado en varios países reduce el consumo de agua."]),
      phrase("Die gestern eingetroffenen Proben werden morgen untersucht.", "Las muestras que llegaron ayer se analizarán mañana.", "Proben", "gestern eingetroffenen es un atributo participial de Proben.", ["Mañana analizarán las muestras recibidas ayer."]),
      phrase("Der von Fachleuten bestätigte Messwert liegt im Normalbereich.", "El valor confirmado por especialistas está dentro de los límites normales.", "Messwert", "von Fachleuten bestätigte precisa el sustantivo Messwert.", ["Los especialistas confirmaron que el valor medido es normal."]),
      phrase("Die im Bericht beschriebenen Risiken werden weiter geprüft.", "Los riesgos descritos en el informe se siguen evaluando.", "Risiken", "im Bericht beschriebenen modifica el sustantivo plural Risiken.", ["Se continúa revisando los riesgos que recoge el informe."]),
    ]),
    lesson("u45-l3", 3, "Innovación responsable", "Explica cómo se evalúan productos y proyectos.", [
      phrase("Die von unabhängigen Experten geprüfte Software schützt sensible Daten.", "El programa evaluado por expertos independientes protege datos sensibles.", "Software", "von unabhängigen Experten geprüfte es un atributo participial de Software.", ["Un software revisado por especialistas externos protege datos confidenciales."]),
      phrase("Die neu entwickelte Batterie speichert mehr erneuerbare Energie.", "La batería recién desarrollada almacena más energía renovable.", "Batterie", "neu entwickelte es un atributo participial que describe la batería.", ["La batería que se ha desarrollado recientemente guarda más energía renovable."]),
      phrase("Ein durch Nutzerfeedback verbessertes Produkt verkauft sich besser.", "Un producto mejorado con las opiniones de los usuarios se vende mejor.", "Produkt", "durch Nutzerfeedback verbessertes precisa cómo se mejoró el producto.", ["Los productos que incorporan la opinión de los usuarios suelen venderse mejor."]),
      phrase("Die in der Testphase gesammelten Rückmeldungen waren hilfreich.", "Las opiniones recogidas durante la fase de pruebas fueron útiles.", "Testphase", "in der Testphase gesammelten describe las Rückmeldungen.", ["Las valoraciones obtenidas durante las pruebas resultaron útiles."]),
      phrase("Der von der Kommission empfohlene Standard gilt ab Januar.", "La norma recomendada por la comisión entra en vigor en enero.", "Kommission", "von der Kommission empfohlene es un atributo participial de Standard.", ["La comisión recomendó una norma que se aplicará desde enero."]),
      phrase("Die sicher verschlüsselten Dateien bleiben vor unbefugtem Zugriff geschützt.", "Los archivos cifrados de forma segura están protegidos contra accesos no autorizados.", "Dateien", "sicher verschlüsselten caracteriza las Dateien mediante un participio.", ["El cifrado seguro impide el acceso no autorizado a esos archivos."]),
    ]),
  ]),
  unit("u46", 46, "Administración y derecho", "Presenta trámites, requisitos y posibilidades formales.", [
    lesson("u46-l1", 1, "Presentar documentos", "Usa formas alternativas a la pasiva en los trámites.", [
      phrase("Die Unterlagen lassen sich online einreichen.", "La documentación se puede presentar por internet.", "Unterlagen", "lassen sich einreichen expresa que es posible presentar la documentación.", ["Es posible entregar los documentos en línea."]),
      phrase("Das Formular ist bis Montag vollständig auszufüllen.", "El formulario debe rellenarse por completo antes del lunes.", "Formular", "ist auszufüllen expresa una obligación con sein más zu más infinitivo.", ["Hay que cumplimentar el formulario entero antes del lunes."], ["Bis Montag ist das Formular vollständig auszufüllen."]),
      phrase("Die gespeicherten Daten sind jederzeit abrufbar.", "Los datos guardados se pueden consultar en cualquier momento.", "Daten", "abrufbar es un adjetivo en -bar que indica posibilidad.", ["Se puede acceder a los datos almacenados cuando se quiera."]),
      phrase("Die Aufgabe ist mit diesem Gerät lösbar.", "La tarea se puede resolver con este aparato.", "Aufgabe", "lösbar deriva de lösen y expresa posibilidad mediante -bar.", ["Este aparato permite resolver la tarea."]),
      phrase("Der Vertrag lässt sich ohne Zusatzkosten kündigen.", "El contrato se puede cancelar sin gastos adicionales.", "Vertrag", "lässt sich kündigen expresa que el contrato puede cancelarse.", ["Es posible rescindir el contrato sin costes extra."]),
      phrase("Die Ergebnisse sind im Kundenportal einzusehen.", "Los resultados pueden consultarse en el portal de clientes.", "Ergebnisse", "sind einzusehen expresa una indicación formal con sein y zu.", ["Consulte los resultados en el portal de clientes."]),
    ]),
    lesson("u46-l2", 2, "Derechos y requisitos", "Interpreta instrucciones y opciones de una solicitud.", [
      phrase("Der Bescheid lässt sich mit einem Formular anfechten.", "La resolución se puede recurrir mediante un formulario.", "Bescheid", "lässt sich anfechten presenta la posibilidad de impugnar la resolución.", ["Es posible recurrir la decisión con un formulario."]),
      phrase("Die Gebühr ist vor der Anmeldung zu bezahlen.", "La tasa debe abonarse antes de la inscripción.", "Gebühr", "ist zu bezahlen expresa una obligación en estilo formal.", ["Hay que pagar la tasa antes de inscribirse."], ["Vor der Anmeldung ist die Gebühr zu bezahlen."]),
      phrase("Die Identität ist durch einen Ausweis nachweisbar.", "La identidad se puede acreditar con un documento.", "Identität", "nachweisbar es un adjetivo en -bar que indica posibilidad.", ["Un documento sirve para demostrar la identidad."]),
      phrase("Die Regel ist ohne Fachwissen erklärbar.", "La norma se puede explicar sin conocimientos especializados.", "Regel", "erklärbar usa -bar para indicar que la norma puede explicarse.", ["Es posible explicar la norma sin ser especialista."]),
      phrase("Die Frist lässt sich in begründeten Fällen verlängern.", "El plazo se puede ampliar en casos justificados.", "Frist", "lässt sich verlängern expresa que es posible ampliar el plazo.", ["En casos justificados, es posible prorrogar el plazo."]),
      phrase("Die Angaben sind vor dem Absenden zu überprüfen.", "Hay que revisar los datos antes de enviarlos.", "Angaben", "sind zu überprüfen formula una instrucción formal con sein y zu.", ["Revise los datos antes de enviar el formulario."]),
    ]),
    lesson("u46-l3", 3, "Servicios digitales", "Describe el acceso y la gestión de información pública.", [
      phrase("Der Antrag lässt sich mit einem digitalen Zertifikat unterschreiben.", "La solicitud se puede firmar con un certificado digital.", "Antrag", "lässt sich unterschreiben expresa que la firma digital es posible.", ["Es posible firmar la solicitud con un certificado electrónico."]),
      phrase("Die Unterlagen sind im Portal jederzeit abrufbar.", "La documentación se puede consultar en el portal en cualquier momento.", "Portal", "abrufbar indica que la documentación puede consultarse.", ["El portal permite acceder a la documentación cuando se necesite."]),
      phrase("Die Adresse ist im Onlineformular zu aktualisieren.", "La dirección debe actualizarse en el formulario en línea.", "Adresse", "ist zu aktualisieren expresa una obligación formal.", ["Hay que poner al día la dirección en el formulario web."]),
      phrase("Der Termin lässt sich über die Webseite verschieben.", "La cita se puede cambiar desde la página web.", "Termin", "lässt sich verschieben indica que es posible cambiar la cita.", ["Es posible aplazar la cita por internet."]),
      phrase("Die Bescheinigung ist problemlos herunterladbar.", "El certificado se puede descargar sin problemas.", "Bescheinigung", "herunterladbar usa el sufijo -bar para expresar posibilidad.", ["Es muy fácil descargar el certificado."]),
      phrase("Alle eingereichten Nachweise sind sorgfältig aufzubewahren.", "Hay que conservar cuidadosamente todos los justificantes presentados.", "Nachweise", "sind aufzubewahren expresa una obligación con sein y zu.", ["Conserve todos los documentos justificativos que haya presentado."]),
    ]),
  ]),
  unit("u47", 47, "Sistema sanitario", "Comprende informes clínicos y comunicación institucional.", [
    lesson("u47-l1", 1, "Informes médicos", "Transmite declaraciones clínicas con Konjunktiv I.", [
      phrase("Die Klinik teilt mit, die Behandlung verlaufe planmäßig.", "La clínica comunica que el tratamiento evoluciona según lo previsto.", "Klinik", "verlaufe es Konjunktiv I y atribuye la valoración a la clínica.", ["Según la clínica, el tratamiento marcha conforme al plan."]),
      phrase("Der Arzt erklärt, die Patientin habe gut auf das Medikament reagiert.", "El médico explica que la paciente ha respondido bien al medicamento.", "Patientin", "habe reagiert transmite indirectamente la explicación del médico.", ["La paciente ha respondido bien al fármaco, según el médico."], ["Die Patientin habe gut auf das Medikament reagiert, erklärt der Arzt."]),
      phrase("Laut der Studie sinke das Fieber nach zwei Tagen.", "Según el estudio, la fiebre baja al cabo de dos días.", "Studie", "sinke reproduce indirectamente un resultado atribuido al estudio.", ["El estudio indica que la fiebre disminuye después de dos días."]),
      phrase("Die Praxis meldet, alle Termine seien bestätigt.", "La consulta informa de que todas las citas están confirmadas.", "Praxis", "seien es Konjunktiv I plural en discurso indirecto.", ["Según la consulta, ya se han confirmado todas las citas."]),
      phrase("Die Sprecherin sagt, das neue Zentrum werde im Herbst öffnen.", "La portavoz dice que el nuevo centro abrirá en otoño.", "Zentrum", "werde öffnen reproduce una previsión atribuida a la portavoz.", ["El nuevo centro abrirá en otoño, según la portavoz."]),
      phrase("Der Bericht hält fest, die Wartezeit sei gesunken.", "El informe señala que se ha reducido el tiempo de espera.", "Wartezeit", "sei gesunken presenta el dato como información atribuida al informe.", ["Según el informe, ahora se espera menos tiempo."]),
    ]),
    lesson("u47-l2", 2, "Investigación clínica", "Presenta hallazgos y conclusiones sin afirmarlos como propios.", [
      phrase("Die Forscher berichten, das Mittel wirke bereits nach einer Stunde.", "Los investigadores informan de que el medicamento hace efecto al cabo de una hora.", "Forscher", "wirke es Konjunktiv I y atribuye la afirmación a los investigadores.", ["Según los investigadores, el fármaco empieza a actuar en una hora."]),
      phrase("Die Autorin erklärt, sie habe die Daten unabhängig ausgewertet.", "La autora explica que ha analizado los datos de forma independiente.", "Autorin", "habe ausgewertet transmite en estilo indirecto lo que explica la autora.", ["La autora asegura que ella misma ha evaluado los datos."], ["Sie habe die Daten unabhängig ausgewertet, erklärt die Autorin."]),
      phrase("Die Klinik meldet, die Beschwerden nähmen deutlich ab.", "La clínica informa de que las molestias están disminuyendo claramente.", "Klinik", "nähmen es Konjunktiv II sustitutivo, ya que la forma plural coincide con el indicativo.", ["Según la clínica, las molestias han remitido de forma notable."]),
      phrase("Der Sprecher betont, das Verfahren sei sicher.", "El portavoz subraya que el procedimiento es seguro.", "Sprecher", "sei es Konjunktiv I de sein en discurso indirecto.", ["El portavoz afirma que el procedimiento no entraña riesgos."]),
      phrase("Laut dem Gutachten könne die Therapie ambulant erfolgen.", "Según el informe pericial, el tratamiento podría hacerse de forma ambulatoria.", "Gutachten", "könne reproduce en Konjunktiv I la valoración del informe.", ["El dictamen considera posible administrar el tratamiento sin ingreso."]),
      phrase("Die Ärztin sagt, der Patient erhole sich gut.", "La médica dice que el paciente se recupera bien.", "Ärztin", "erhole es Konjunktiv I y atribuye el diagnóstico a la médica.", ["Según la doctora, el paciente está evolucionando bien."]),
    ]),
    lesson("u47-l3", 3, "Políticas de salud", "Resume decisiones, plazos y objetivos de un sistema sanitario.", [
      phrase("Die Ministerin kündigt an, die Versorgung werde verbessert.", "La ministra anuncia que mejorará la atención sanitaria.", "Ministerin", "werde verbessert forma la pasiva en Konjunktiv I.", ["La ministra anuncia mejoras en la asistencia sanitaria."]),
      phrase("Der Verband erklärt, die Beiträge blieben stabil.", "La asociación explica que las cuotas se mantendrán estables.", "Verband", "blieben sustituye al Konjunktiv I plural, que coincide con el indicativo.", ["La asociación asegura que no subirán las cuotas."], ["Die Beiträge blieben stabil, erklärt der Verband."]),
      phrase("Die Behörde teilt mit, neue Praxen würden eröffnet.", "La autoridad comunica que se abrirán nuevas consultas.", "Behörde", "würden eröffnet es Konjunktiv II sustitutivo para evitar la coincidencia con el indicativo.", ["Según la autoridad, se pondrán en marcha nuevos centros de salud."]),
      phrase("Der Bericht bestätigt, die Zahl der Impfungen sei gestiegen.", "El informe confirma que ha aumentado el número de vacunaciones.", "Bericht", "sei gestiegen transmite indirectamente el dato confirmado.", ["Según el informe, se han administrado más vacunas."]),
      phrase("Die Sprecherin erklärt, die Beratung bleibe kostenlos.", "La portavoz explica que la orientación seguirá siendo gratuita.", "Sprecherin", "bleibe reproduce la declaración de la portavoz en Konjunktiv I.", ["La portavoz asegura que la consulta informativa no tendrá coste."]),
      phrase("Laut dem Plan solle die Klinik im Sommer öffnen.", "Según el plan, la clínica debería abrir en verano.", "Klinik", "solle introduce en estilo indirecto la fecha prevista en el plan.", ["El plan prevé que la clínica abra en verano."]),
    ]),
  ]),
  unit("u48", 48, "Economía y mercados", "Interpreta previsiones y decisiones empresariales.", [
    lesson("u48-l1", 1, "Datos económicos", "Resume informes con atributos participiales.", [
      phrase("Die vom Verband veröffentlichte Prognose nennt steigende Umsätze.", "La previsión publicada por la asociación apunta a un aumento de las ventas.", "Prognose", "vom Verband veröffentlichte es un atributo participial de Prognose.", ["La asociación publicó una previsión que anuncia mayores ventas."]),
      phrase("Der im Frühjahr beschlossene Tarif gilt ab September.", "La tarifa acordada en primavera se aplica desde septiembre.", "Tarif", "im Frühjahr beschlossene modifica Tarif mediante Partizip II.", ["El acuerdo tarifario adoptado en primavera entra en vigor en septiembre."], ["Ab September gilt der im Frühjahr beschlossene Tarif."]),
      phrase("Die von Fachleuten erwartete Erholung blieb zunächst aus.", "La recuperación esperada por los expertos no llegó al principio.", "Erholung", "von Fachleuten erwartete precisa quién esperaba la recuperación.", ["Al principio no se produjo la recuperación que preveían los especialistas."]),
      phrase("Die Bank prüft einen neu entwickelten Zahlungsdienst.", "El banco está evaluando un servicio de pago recién desarrollado.", "Zahlungsdienst", "neu entwickelten es un atributo participial de Zahlungsdienst.", ["La entidad analiza un nuevo sistema de pagos."]),
      phrase("Die im Ausland produzierten Geräte werden hier verkauft.", "Los dispositivos fabricados en el extranjero se venden aquí.", "Geräte", "im Ausland produzierten describe los dispositivos con Partizip II.", ["Aquí se venden los aparatos que se producen fuera del país."]),
      phrase("Das von der Behörde genehmigte Vorhaben schafft neue Arbeitsplätze.", "El proyecto aprobado por la autoridad crea nuevos puestos de trabajo.", "Vorhaben", "von der Behörde genehmigte modifica Vorhaben y señala quién lo aprobó.", ["La autoridad dio luz verde a un proyecto que generará empleo."]),
    ]),
    lesson("u48-l2", 2, "Empresas y empleo", "Describe medidas, acuerdos y efectos en el mercado laboral.", [
      phrase("Die kürzlich gegründete Firma beschäftigt bereits fünfzig Personen.", "La empresa fundada hace poco ya da trabajo a cincuenta personas.", "Firma", "kürzlich gegründete es un atributo participial de Firma.", ["La compañía, creada recientemente, ya tiene cincuenta empleados."]),
      phrase("Der von beiden Seiten unterzeichnete Vertrag tritt morgen in Kraft.", "El contrato firmado por ambas partes entra en vigor mañana.", "Vertrag", "von beiden Seiten unterzeichnete modifica Vertrag mediante Partizip II.", ["Mañana empieza a aplicarse el acuerdo que firmaron ambas partes."], ["Morgen tritt der von beiden Seiten unterzeichnete Vertrag in Kraft."]),
      phrase("Die für den Standort verantwortliche Direktorin stellte neue Pläne vor.", "La directora responsable de la sede presentó nuevos planes.", "Direktorin", "für den Standort verantwortliche es un atributo ampliado de Direktorin.", ["La responsable de la sede dio a conocer nuevos planes."]),
      phrase("Die neu geschaffenen Stellen richten sich an Berufseinsteiger.", "Los puestos de nueva creación están dirigidos a quienes empiezan su carrera.", "Stellen", "neu geschaffenen caracteriza los puestos mediante Partizip II.", ["Las nuevas vacantes están pensadas para personas que comienzan a trabajar."]),
      phrase("Ein von der Belegschaft gewählter Rat vertritt die Beschäftigten.", "Un consejo elegido por la plantilla representa a los trabajadores.", "Belegschaft", "von der Belegschaft gewählter describe quién eligió al consejo.", ["La plantilla eligió un consejo para representar a los trabajadores."]),
      phrase("Die seit Monaten laufenden Gespräche sollen bald enden.", "Las negociaciones que llevan meses en marcha deberían terminar pronto.", "Gespräche", "seit Monaten laufenden es un atributo participial de Gespräche.", ["Se espera que pronto terminen las conversaciones iniciadas hace meses."]),
    ]),
    lesson("u48-l3", 3, "Consumo y precios", "Explica cambios de precios y hábitos de compra.", [
      phrase("Die von Händlern angekündigte Preiserhöhung gilt ab nächster Woche.", "La subida de precios anunciada por los comerciantes se aplica desde la semana que viene.", "Preiserhöhung", "von Händlern angekündigte precisa quién anunció la subida.", ["Los comerciantes anunciaron un aumento de precios para la semana próxima."]),
      phrase("Das in der Region angebaute Gemüse wird täglich geliefert.", "Las verduras cultivadas en la región se entregan a diario.", "Gemüse", "in der Region angebaute modifica el sustantivo colectivo Gemüse.", ["Cada día se distribuyen verduras que se cultivan en la zona."], ["Täglich wird das in der Region angebaute Gemüse geliefert."]),
      phrase("Die online bestellten Waren treffen morgen ein.", "Los productos pedidos por internet llegarán mañana.", "Waren", "online bestellten es un atributo participial de Waren.", ["Mañana llegan los artículos que se compraron en línea."]),
      phrase("Ein von der Kundschaft gewünschter Rabatt wurde eingeführt.", "Se implantó un descuento solicitado por la clientela.", "Rabatt", "von der Kundschaft gewünschter indica quién pidió el descuento.", ["La empresa aplicó la rebaja que pedían sus clientes."]),
      phrase("Die im Vergleich zum Vorjahr gestiegenen Kosten belasten kleine Betriebe.", "El aumento de costes respecto al año anterior perjudica a las pequeñas empresas.", "Kosten", "im Vergleich zum Vorjahr gestiegenen describe la evolución de los costes.", ["Las pequeñas empresas acusan la subida de costes frente al año pasado."]),
      phrase("Der gestern veröffentlichte Index zeigt eine leichte Erholung.", "El índice publicado ayer muestra una recuperación moderada.", "Index", "gestern veröffentlichte modifica Index y señala cuándo se publicó.", ["El índice que salió ayer apunta a una leve recuperación."]),
    ]),
  ]),
  unit("u49", 49, "Medio ambiente y ciudades", "Describe soluciones técnicas y servicios sostenibles.", [
    lesson("u49-l1", 1, "Agua y residuos", "Expresa posibilidades y obligaciones con formas pasivas alternativas.", [
      phrase("Die beschädigten Rohre lassen sich nicht kurzfristig ersetzen.", "Las tuberías dañadas no se pueden sustituir de inmediato.", "Rohre", "lassen sich ersetzen presenta una posibilidad de sustitución.", ["No es posible cambiar enseguida las tuberías averiadas."]),
      phrase("Der Umweltbericht ist im Internet abrufbar.", "El informe medioambiental se puede consultar en internet.", "Umweltbericht", "abrufbar deriva de abrufen y expresa posibilidad.", ["El informe ambiental está disponible en línea."], ["Im Internet ist der Umweltbericht abrufbar."]),
      phrase("Diese Fläche ist nur zu Fuß erreichbar.", "A esta zona solo se puede llegar a pie.", "Fläche", "erreichbar usa -bar para indicar que es posible llegar.", ["Solo se puede acceder a esta zona caminando."]),
      phrase("Die Filter sind jedes Jahr zu wechseln.", "Los filtros deben cambiarse cada año.", "Filter", "sind zu wechseln expresa una obligación formal.", ["Hay que sustituir los filtros una vez al año."]),
      phrase("Abfälle lassen sich an mehreren Stellen trennen.", "Los residuos se pueden separar en varios puntos.", "Abfälle", "lassen sich trennen indica que la separación es posible.", ["Hay varios puntos donde se pueden clasificar los residuos."]),
      phrase("Die Solaranlage ist problemlos erweiterbar.", "La instalación solar se puede ampliar sin problemas.", "Solaranlage", "erweiterbar es un adjetivo en -bar que expresa posibilidad.", ["Es fácil ampliar la instalación de energía solar."]),
    ]),
    lesson("u49-l2", 2, "Energía y movilidad", "Habla de mejoras urbanas y medidas de ahorro.", [
      phrase("Die Beleuchtung lässt sich automatisch regulieren.", "La iluminación se puede regular automáticamente.", "Beleuchtung", "lässt sich regulieren expresa que la regulación es posible.", ["Es posible ajustar la iluminación de forma automática."]),
      phrase("Die neuen Ladestationen sind rund um die Uhr nutzbar.", "Los nuevos puntos de recarga se pueden usar a cualquier hora.", "Ladestationen", "nutzbar se forma con -bar y señala que las estaciones pueden utilizarse.", ["Las estaciones de carga están disponibles las veinticuatro horas."], ["Rund um die Uhr sind die neuen Ladestationen nutzbar."]),
      phrase("Die Batterien sind vor hohen Temperaturen zu schützen.", "Las baterías deben protegerse de las temperaturas altas.", "Batterien", "sind zu schützen expresa una obligación de cuidado.", ["Hay que mantener las baterías alejadas del calor intenso."]),
      phrase("Der Fahrplan ist über die App abrufbar.", "El horario se puede consultar en la aplicación.", "Fahrplan", "abrufbar indica que es posible consultar el horario.", ["La aplicación permite ver el horario."]),
      phrase("Die Straße lässt sich mit wenig Aufwand begrünen.", "La calle se puede llenar de zonas verdes con poco esfuerzo.", "Straße", "lässt sich begrünen presenta una posibilidad de transformación.", ["Es fácil añadir vegetación a la calle."]),
      phrase("Die neuen Wege sind mit dem Rollstuhl befahrbar.", "Las nuevas rutas se pueden recorrer en silla de ruedas.", "Wege", "befahrbar expresa con -bar que se puede circular por los caminos.", ["Las personas en silla de ruedas pueden recorrer las nuevas rutas."]),
    ]),
    lesson("u49-l3", 3, "Protección de recursos", "Formula requisitos y medidas para preservar recursos.", [
      phrase("Der Wasserverbrauch ist monatlich zu kontrollieren.", "El consumo de agua debe controlarse cada mes.", "Wasserverbrauch", "ist zu kontrollieren expresa una obligación formal.", ["Hay que comprobar el gasto de agua todos los meses."]),
      phrase("Die Anlage lässt sich mit Regenwasser betreiben.", "La instalación puede funcionar con agua de lluvia.", "Anlage", "lässt sich betreiben expresa una posibilidad de funcionamiento.", ["Es posible hacer funcionar el sistema con agua pluvial."]),
      phrase("Die Messwerte sind jederzeit online einsehbar.", "Los valores medidos se pueden consultar en línea en cualquier momento.", "Messwerte", "einsehbar usa -bar para señalar que los valores están disponibles.", ["Los datos de medición están disponibles en internet cuando se necesiten."]),
      phrase("Diese Verpackung ist vollständig recycelbar.", "Este envase se puede reciclar por completo.", "Verpackung", "recycelbar expresa la posibilidad de reciclar el envase.", ["El envase es totalmente reciclable."]),
      phrase("Die Nutzung öffentlicher Verkehrsmittel ist zu fördern.", "Se debe fomentar el uso del transporte público.", "Verkehrsmittel", "ist zu fördern expresa una recomendación formal con sein y zu.", ["Conviene impulsar el uso del transporte público."]),
      phrase("Die gespeicherten Daten lassen sich sicher übertragen.", "Los datos almacenados se pueden transmitir de forma segura.", "Daten", "lassen sich übertragen presenta la transferencia como posible.", ["Es posible enviar los datos guardados con seguridad."]),
    ]),
  ]),
  unit("u50", 50, "Educación y empleo", "Analiza la formación, la selección y la incorporación laboral.", [
    lesson("u50-l1", 1, "Acceso a la formación", "Resume procesos educativos con sustantivos de acción.", [
      phrase("Die Teilnahme an der Fortbildung setzt Erfahrung voraus.", "Para participar en la formación continua se necesita experiencia.", "Fortbildung", "Teilnahme nominaliza teilnehmen y aparece con an más dativo.", ["La formación continua exige experiencia previa."]),
      phrase("Nach Abschluss des Seminars erhalten alle ein Zertifikat.", "Al terminar el seminario, todos reciben un certificado.", "Abschluss", "Nach Abschluss usa un sustantivo para ordenar las acciones.", ["Al finalizar el curso, se entrega un certificado a todos."], ["Alle erhalten nach Abschluss des Seminars ein Zertifikat."]),
      phrase("Die Vermittlung neuer Kompetenzen braucht Zeit.", "La enseñanza de nuevas competencias requiere tiempo.", "Kompetenzen", "Vermittlung es una nominalización de vermitteln.", ["Hace falta tiempo para enseñar nuevas habilidades."]),
      phrase("Zur Vorbereitung auf die Prüfung arbeitet sie in einer Lerngruppe.", "Para preparar el examen, estudia en grupo.", "Vorbereitung", "Vorbereitung nominaliza vorbereiten y expresa el propósito.", ["Se prepara para la prueba con un grupo de estudio."]),
      phrase("Die Bewertung der Leistungen erfolgt nach klaren Kriterien.", "La evaluación del rendimiento se realiza según criterios claros.", "Leistungen", "Bewertung es un sustantivo de acción que funciona como sujeto.", ["El rendimiento se valora siguiendo unas pautas claras."]),
      phrase("Bei der Beratung wählen die Teilnehmenden einen Schwerpunkt.", "Durante la orientación, los participantes eligen una especialidad.", "Beratung", "Beratung convierte beraten en un sustantivo tras bei.", ["En la sesión de orientación, cada participante escoge un área."]),
    ]),
    lesson("u50-l2", 2, "Candidaturas y selección", "Describe criterios, entrevistas y decisiones.", [
      phrase("Die Prüfung der Zeugnisse erfolgt vor dem Gespräch.", "Los certificados se revisan antes de la entrevista.", "Zeugnisse", "Prüfung nominaliza prüfen y nombra el proceso de selección.", ["La revisión de los títulos se hace antes de la entrevista."]),
      phrase("Nach der Vorauswahl lädt die Firma drei Personen ein.", "Tras la preselección, la empresa invita a tres personas.", "Vorauswahl", "Nach der Vorauswahl sitúa la invitación tras una fase de selección.", ["La empresa cita a tres candidatos después de la primera criba."], ["Die Firma lädt nach der Vorauswahl drei Personen ein."]),
      phrase("Die Einladung zum Gespräch kam gestern an.", "La invitación a la entrevista llegó ayer.", "Einladung", "Einladung nominaliza einladen y funciona como sujeto.", ["Ayer recibieron la invitación para la entrevista."]),
      phrase("Bei der Entscheidung berücksichtigt das Team alle Erfahrungen.", "Al decidir, el equipo tiene en cuenta toda la experiencia.", "Entscheidung", "Entscheidung es el sustantivo de entscheiden.", ["El equipo valora toda la trayectoria antes de decidir."]),
      phrase("Die Zusammenarbeit mit dem Betriebsrat ist vorgeschrieben.", "La colaboración con el comité de empresa es obligatoria.", "Betriebsrat", "Zusammenarbeit resume la acción de colaborar.", ["Es obligatorio trabajar con el comité de empresa."]),
      phrase("Zur Besetzung der Stelle veröffentlicht die Agentur eine Anzeige.", "Para cubrir el puesto, la agencia publica un anuncio.", "Besetzung", "Besetzung nominaliza besetzen y depende de zur.", ["La agencia publica una oferta para cubrir la vacante."]),
    ]),
    lesson("u50-l3", 3, "Nuevas competencias", "Valora la actualización y el aprendizaje profesional.", [
      phrase("Die Entwicklung digitaler Fähigkeiten gehört zur Weiterbildung.", "El desarrollo de competencias digitales forma parte de la formación continua.", "Fähigkeiten", "Entwicklung es una nominalización que presenta el proceso como sujeto.", ["Actualizar las competencias digitales es parte del aprendizaje permanente."]),
      phrase("Nach erfolgreichem Abschluss des Kurses beginnt die Einarbeitung.", "Tras terminar el curso con éxito, empieza la incorporación al puesto.", "Einarbeitung", "Abschluss nominaliza abschließen y señala el momento previo a la incorporación.", ["La incorporación comienza una vez finalizado el curso."]),
      phrase("Die Anwendung der neuen Kenntnisse erleichtert den Arbeitsalltag.", "Aplicar los nuevos conocimientos facilita el trabajo diario.", "Anwendung", "Anwendung convierte anwenden en un sustantivo de acción.", ["Poner en práctica lo aprendido hace más sencillo el día a día."]),
      phrase("Der Bericht stellt fest, die Einstellung neuer Fachkräfte gelinge.", "El informe indica que la contratación de nuevos especialistas está saliendo bien.", "Bericht", "gelinge es Konjunktiv I y transmite una conclusión del informe.", ["Según el informe, se está logrando contratar a nuevos profesionales."]),
      phrase("Die Beratung der Beschäftigten erfolgt vertraulich.", "La orientación a los empleados se ofrece de forma confidencial.", "Beschäftigten", "Beratung nominaliza beraten y especifica quién recibe el servicio.", ["Las consultas de los trabajadores se atienden con confidencialidad."]),
      phrase("Die Anerkennung zusätzlicher Qualifikationen dauert oft lange.", "El reconocimiento de cualificaciones adicionales suele tardar mucho.", "Qualifikationen", "Anerkennung convierte anerkennen en un sustantivo de acción.", ["Reconocer títulos y competencias adicionales puede llevar tiempo."]),
    ]),
  ]),
  unit("u51", 51, "Medios y tecnología", "Comprende publicaciones, contenidos digitales y normas de uso.", [
    lesson("u51-l1", 1, "Publicar y verificar", "Describe contenidos mediante atributos participiales.", [
      phrase("Die von der Redaktion geprüfte Aufnahme wurde nicht ausgestrahlt.", "La grabación revisada por la redacción no se emitió.", "Aufnahme", "von der Redaktion geprüfte modifica Aufnahme mediante Partizip II.", ["La redacción revisó una grabación que finalmente no se emitió."]),
      phrase("Die gestern hochgeladenen Bilder sind frei zugänglich.", "Las imágenes subidas ayer están disponibles para todo el mundo.", "Bilder", "gestern hochgeladenen describe las imágenes con Partizip II.", ["Cualquiera puede consultar las imágenes que se subieron ayer."], ["Die Bilder, die gestern hochgeladen wurden, sind frei zugänglich."]),
      phrase("Ein von mehreren Quellen bestätigter Bericht verbreitete sich schnell.", "Un informe confirmado por varias fuentes se difundió rápidamente.", "Bericht", "von mehreren Quellen bestätigter es un atributo ampliado de Bericht.", ["El informe, corroborado por varias fuentes, se difundió enseguida."]),
      phrase("Die im Archiv gespeicherten Dateien bleiben erhalten.", "Los archivos guardados en el archivo se conservarán.", "Archiv", "im Archiv gespeicherten precisa el lugar de almacenamiento de los archivos.", ["Se conservarán los ficheros que están guardados en el archivo."]),
      phrase("Der neu produzierte Podcast erscheint jeden Montag.", "El pódcast recién producido sale todos los lunes.", "Podcast", "neu produzierte es un atributo participial de Podcast.", ["El pódcast que acaba de producirse se publica cada lunes."]),
      phrase("Die während der Sendung eingegangenen Fragen beantwortete die Expertin.", "La experta contestó las preguntas recibidas durante el programa.", "Sendung", "während der Sendung eingegangenen modifica Fragen con un participio.", ["La experta respondió a las preguntas que llegaron durante la emisión."]),
    ]),
    lesson("u51-l2", 2, "Herramientas digitales", "Expresa qué se puede hacer con archivos y aplicaciones.", [
      phrase("Die Datei lässt sich mit dem neuen Programm öffnen.", "El archivo se puede abrir con el nuevo programa.", "Datei", "lässt sich öffnen expresa que es posible abrir el archivo.", ["El nuevo programa permite abrir el archivo."]),
      phrase("Diese Information ist in wenigen Sekunden überprüfbar.", "Esta información se puede comprobar en unos segundos.", "Information", "überprüfbar deriva de überprüfen y expresa posibilidad.", ["Basta con unos segundos para verificar este dato."], ["In wenigen Sekunden ist diese Information überprüfbar."]),
      phrase("Die Einstellungen sind jederzeit veränderbar.", "La configuración se puede cambiar en cualquier momento.", "Einstellungen", "veränderbar usa -bar para indicar que es posible modificarla.", ["Es posible ajustar la configuración cuando se quiera."]),
      phrase("Das Passwort ist regelmäßig zu erneuern.", "La contraseña debe renovarse con regularidad.", "Passwort", "ist zu erneuern formula una obligación formal.", ["Hay que cambiar la contraseña periódicamente."]),
      phrase("Die beschädigte Datei lässt sich nicht wiederherstellen.", "El archivo dañado no se puede recuperar.", "Datei", "lässt sich nicht wiederherstellen expresa que la recuperación no es posible.", ["No es posible restaurar el fichero dañado."]),
      phrase("Die Anwendung ist auf älteren Geräten nutzbar.", "La aplicación se puede usar en dispositivos antiguos.", "Anwendung", "nutzbar es un adjetivo en -bar que expresa posibilidad.", ["La aplicación funciona también en aparatos antiguos."]),
    ]),
    lesson("u51-l3", 3, "Contenido y audiencia", "Atribuye cambios y opiniones a sus fuentes.", [
      phrase("Der Sender teilt mit, die Sendung falle heute aus.", "La cadena comunica que hoy no se emitirá el programa.", "Sender", "falle es Konjunktiv I y transmite el aviso de la cadena.", ["Según la cadena, hoy se cancela el programa."]),
      phrase("Die Redaktion erklärt, sie habe den Beitrag gekürzt.", "La redacción explica que ha recortado el reportaje.", "Redaktion", "habe gekürzt reproduce indirectamente la explicación de la redacción.", ["La redacción dice que ha acortado la pieza."], ["Sie habe den Beitrag gekürzt, erklärt die Redaktion."]),
      phrase("Laut der Umfrage nutzten mehr Menschen digitale Angebote.", "Según la encuesta, más personas utilizaron servicios digitales.", "Umfrage", "laut atribuye la información a la encuesta.", ["La encuesta muestra un aumento de usuarios de servicios digitales."]),
      phrase("Die Auswertung der Kommentare dauerte mehrere Tage.", "El análisis de los comentarios llevó varios días.", "Auswertung", "Auswertung nominaliza auswerten y funciona como sujeto.", ["Analizar los comentarios requirió varios días."]),
      phrase("Die von Fachleuten empfohlene Plattform schützt persönliche Daten.", "La plataforma recomendada por especialistas protege los datos personales.", "Plattform", "von Fachleuten empfohlene precisa quién recomendó la plataforma.", ["Los especialistas aconsejan una plataforma que protege la privacidad."]),
      phrase("Der Vertrag ist jederzeit digital kündbar.", "El contrato se puede cancelar en línea en cualquier momento.", "Vertrag", "kündbar deriva de kündigen y expresa posibilidad con -bar.", ["Es posible rescindir el contrato por internet cuando se quiera."]),
    ]),
  ]),
];
