import type { LessonDraft, Phrase, UnitDraft } from "./units";

const phrase = (
  german: string,
  spanish: string,
  blankWord: string,
  explanation: string,
  spanishAlt?: string[],
  germanAlt?: string[],
): Phrase => ({
  german,
  spanish,
  blankWord,
  explanation,
  ...(spanishAlt ? { spanishAlt } : {}),
  ...(germanAlt ? { germanAlt } : {}),
});

const lesson = (
  id: string,
  order: number,
  title: string,
  description: string,
  phrases: Phrase[],
): LessonDraft => ({ id, order, title, description, xpReward: 10, phrases });

const unit = (
  id: string,
  order: number,
  title: string,
  description: string,
  lessons: LessonDraft[],
): UnitDraft => ({
  id,
  order,
  title,
  description,
  color: "#58CC02",
  cefrLevel: "B2.2",
  lessons,
});

export const b2_2UnitDrafts: UnitDraft[] = [
  unit("u52", 52, "Política y debate público", "Interpreta rumores, afirmaciones y valoraciones.", [
    lesson("u52-l1", 1, "Afirmaciones y rumores", "Distingue soll, will, dürfte y müsste subjetivos.", [
      phrase("Der Minister soll über einen Rücktritt nachdenken.", "Según dicen, el ministro está pensando en dimitir.", "Minister", "soll expresa un rumor atribuido a otras personas, no una obligación.", ["Al parecer, el ministro se plantea dejar el cargo."]),
      phrase("Die Sprecherin will keine Warnung erhalten haben.", "La portavoz afirma que no recibió ninguna advertencia.", "Sprecherin", "will erhalten haben indica que la portavoz sostiene que recibió esa información.", ["La portavoz asegura que no le llegó ningún aviso."], ["Keine Warnung will die Sprecherin erhalten haben."]),
      phrase("Die Verzögerung dürfte auf einen Personalengpass zurückgehen.", "Es probable que el retraso se deba a falta de personal.", "Verzögerung", "dürfte expresa una suposición probable sobre la causa del retraso.", ["El retraso seguramente está relacionado con la falta de personal."]),
      phrase("Der Ausschuss müsste den Entwurf inzwischen geprüft haben.", "El comité ya debería haber revisado el borrador.", "Entwurf", "müsste geprüft haben expresa una deducción sobre una acción pasada.", ["A estas alturas, es probable que el comité haya revisado el borrador."]),
      phrase("Der Kandidat soll mehrere Gespräche geführt haben.", "Según se dice, el candidato ha mantenido varias conversaciones.", "Kandidat", "soll geführt haben transmite información no confirmada sobre el candidato.", ["Al parecer, el candidato ha mantenido varias reuniones."]),
      phrase("Das Gerücht dürfte aus einem Missverständnis entstanden sein.", "Es probable que el rumor surgiera de un malentendido.", "Gerücht", "dürfte entstanden sein expresa una suposición sobre el origen del rumor.", ["El rumor seguramente se originó en una confusión."]),
    ]),
    lesson("u52-l2", 2, "Ciencia y declaraciones", "Expresa lo que alguien afirma haber hecho o sabido.", [
      phrase("Die Zeugin will den Vertrag nie gesehen haben.", "La testigo afirma que nunca ha visto el contrato.", "Zeugin", "will gesehen haben reproduce una afirmación de la testigo.", ["La testigo asegura no haber visto el contrato."]),
      phrase("Der Ausfall dürfte durch einen Kurzschluss verursacht worden sein.", "Es probable que el fallo lo causara un cortocircuito.", "Ausfall", "dürfte verursacht worden sein expresa una hipótesis sobre la causa.", ["El cortocircuito seguramente provocó la avería."], ["Durch einen Kurzschluss dürfte der Ausfall verursacht worden sein."]),
      phrase("Die Behörde soll die Daten gelöscht haben.", "Según se afirma, la autoridad ha borrado los datos.", "Behörde", "soll gelöscht haben transmite una noticia no confirmada.", ["Al parecer, la autoridad eliminó los datos."]),
      phrase("Das Signal müsste auch bei schlechtem Wetter sichtbar sein.", "La señal debería verse incluso con mal tiempo.", "Signal", "müsste sichtbar sein expresa una suposición sobre la visibilidad.", ["En principio, la señal tendría que verse aunque haga mal tiempo."]),
      phrase("Der Techniker will die Ursache gefunden haben.", "El técnico afirma que ha encontrado la causa.", "Techniker", "will gefunden haben atribuye al técnico la afirmación de haberla encontrado.", ["El técnico asegura haber dado con la causa."]),
      phrase("Die Messung dürfte ungenau gewesen sein.", "Es probable que la medición fuera inexacta.", "Messung", "dürfte gewesen sein formula una valoración probable sobre la medición.", ["Seguramente, la medición no fue precisa."]),
    ]),
    lesson("u52-l3", 3, "Sociedad y responsabilidades", "Valora hipótesis y declaraciones en asuntos públicos.", [
      phrase("Die Gruppe soll die Sitzung vorzeitig verlassen haben.", "Según se dice, el grupo abandonó la sesión antes de tiempo.", "Gruppe", "soll verlassen haben presenta como rumor una acción pasada.", ["Al parecer, el grupo se marchó de la reunión antes de que acabara."]),
      phrase("Der Vorschlag dürfte breite Zustimmung finden.", "Es probable que la propuesta reciba un amplio respaldo.", "Vorschlag", "dürfte finden expresa una expectativa probable.", ["La propuesta seguramente contará con mucho apoyo."]),
      phrase("Die Abgeordnete will die Unterlagen selbst geprüft haben.", "La diputada afirma que revisó ella misma la documentación.", "Abgeordnete", "will geprüft haben atribuye a la diputada esa afirmación.", ["La diputada asegura haber examinado personalmente los documentos."]),
      phrase("Der Bericht müsste bis morgen vorliegen.", "El informe debería estar listo para mañana.", "Bericht", "müsste expresa una expectativa razonable sobre la disponibilidad del informe.", ["En principio, el informe tendría que estar para mañana."]),
      phrase("Der Kandidat soll Kontakte zu mehreren Firmen haben.", "Según se comenta, el candidato tiene contactos con varias empresas.", "Kontakte", "soll haben atribuye la información a fuentes externas.", ["Al parecer, el candidato mantiene contactos con varias empresas."]),
      phrase("Die Entscheidung dürfte auf neuen Zahlen beruhen.", "Es probable que la decisión se base en cifras nuevas.", "Entscheidung", "dürfte beruhen expresa una hipótesis probable sobre el fundamento de la decisión.", ["La decisión seguramente se apoya en datos recientes."]),
    ]),
  ]),
  unit("u53", 53, "Economía y empresas", "Comprende expresiones verbales frecuentes en contextos económicos.", [
    lesson("u53-l1", 1, "Acuerdos y decisiones", "Practica Funktionsverbgefüge en reuniones y anuncios.", [
      phrase("Die Regierung hat eine Entscheidung über die Steuerreform getroffen.", "El Gobierno ha tomado una decisión sobre la reforma fiscal.", "Regierung", "eine Entscheidung treffen es un grupo verbal funcional con el sustantivo Entscheidung.", ["El Ejecutivo ha decidido qué hacer con la reforma de impuestos."]),
      phrase("Der Vertrag tritt am ersten Januar in Kraft.", "El contrato entra en vigor el uno de enero.", "Vertrag", "in Kraft treten significa empezar a tener validez.", ["El acuerdo empieza a aplicarse el primero de enero."], ["Am ersten Januar tritt der Vertrag in Kraft."]),
      phrase("Die Firma stellte zusätzliche Mittel zur Verfügung.", "La empresa puso a disposición recursos adicionales.", "Firma", "Mittel zur Verfügung stellen es un grupo verbal funcional.", ["La compañía facilitó más recursos."]),
      phrase("Der Vorstand übte deutliche Kritik an dem Vorschlag.", "La junta directiva criticó claramente la propuesta.", "Vorstand", "Kritik üben an equivale a expresar críticas sobre algo.", ["La dirección expresó su desacuerdo con la propuesta."]),
      phrase("Das Unternehmen nahm Gespräche mit dem Betriebsrat auf.", "La empresa inició conversaciones con el comité de empresa.", "Unternehmen", "Gespräche aufnehmen significa iniciar negociaciones.", ["La compañía empezó a negociar con la representación laboral."]),
      phrase("Die Kommission brachte den Entwurf zur Abstimmung.", "La comisión sometió el borrador a votación.", "Kommission", "einen Entwurf zur Abstimmung bringen significa proponerlo para votar.", ["La comisión presentó el borrador para que se votara."]),
    ]),
    lesson("u53-l2", 2, "Finanzas y administración", "Usa grupos verbales funcionales en gestiones y operaciones.", [
      phrase("Die Behörde nahm eine Prüfung der Zahlen vor.", "La autoridad llevó a cabo una revisión de las cifras.", "Behörde", "eine Prüfung vornehmen es un grupo verbal funcional formal.", ["La autoridad revisó las cifras."]),
      phrase("Die Kommission traf eine endgültige Entscheidung.", "La comisión tomó una decisión definitiva.", "Kommission", "eine Entscheidung treffen es una expresión verbal funcional.", ["La comisión decidió de forma definitiva."], ["Eine endgültige Entscheidung traf die Kommission."]),
      phrase("Der Fonds leistete einen wichtigen Beitrag zur Forschung.", "El fondo hizo una contribución importante a la investigación.", "Fonds", "einen Beitrag leisten es un grupo verbal funcional frecuente.", ["El fondo contribuyó de forma importante a la investigación."]),
      phrase("Das Unternehmen stellte einen Antrag auf Förderung.", "La empresa presentó una solicitud de subvención.", "Unternehmen", "einen Antrag stellen significa presentar formalmente una solicitud.", ["La compañía pidió una ayuda económica."]),
      phrase("Die Verhandlungen kamen nach drei Stunden zum Abschluss.", "Las negociaciones concluyeron después de tres horas.", "Verhandlungen", "zum Abschluss kommen significa llegar al final de un proceso.", ["Tras tres horas, las negociaciones llegaron a su fin."]),
      phrase("Der Aufsichtsrat gab eine Empfehlung zur Senkung der Kosten ab.", "El consejo de supervisión emitió una recomendación para reducir los costes.", "Aufsichtsrat", "eine Empfehlung abgeben es un grupo verbal funcional formal.", ["El consejo recomendó medidas para reducir los costes."]),
    ]),
    lesson("u53-l3", 3, "Empleo y negociación", "Describe compromisos, posturas y consecuencias.", [
      phrase("Die Beschäftigten kamen nach langen Gesprächen zu einer Einigung.", "Tras largas conversaciones, los trabajadores llegaron a un acuerdo.", "Beschäftigten", "zu einer Einigung kommen describe el resultado de una negociación.", ["Los trabajadores alcanzaron un acuerdo después de negociar durante horas."]),
      phrase("Der Verband nahm Stellung zu dem neuen Bericht.", "La asociación se pronunció sobre el nuevo informe.", "Verband", "Stellung nehmen zu significa expresar una opinión sobre un asunto.", ["La asociación hizo una valoración del nuevo informe."], ["Zu dem neuen Bericht nahm der Verband Stellung."]),
      phrase("Die Leitung zog Konsequenzen aus den Beschwerden.", "La dirección tomó medidas a raíz de las reclamaciones.", "Leitung", "Konsequenzen ziehen es un grupo verbal funcional.", ["La dirección extrajo conclusiones de las quejas."]),
      phrase("Die Partei brachte eine Reform zur Sprache.", "El partido planteó una reforma.", "Partei", "etwas zur Sprache bringen significa mencionarlo o proponerlo.", ["El partido puso la reforma sobre la mesa."]),
      phrase("Das Unternehmen übernahm Verantwortung für den Fehler.", "La empresa asumió la responsabilidad por el error.", "Unternehmen", "Verantwortung übernehmen es una expresión verbal funcional.", ["La compañía se hizo responsable del fallo."]),
      phrase("Der Betrieb erteilte dem neuen Plan seine Zustimmung.", "La empresa dio su aprobación al nuevo plan.", "Betrieb", "Zustimmung erteilen es un grupo verbal funcional que significa aprobar algo.", ["La empresa aprobó el nuevo plan."]),
    ]),
  ]),
  unit("u54", 54, "Investigación y patrimonio", "Interpreta descripciones complejas de estudios y colecciones.", [
    lesson("u54-l1", 1, "Datos científicos", "Comprende atributos participiales ampliados.", [
      phrase("Die von einer internationalen Gruppe ausgewerteten Daten widersprechen der Annahme.", "Los datos analizados por un grupo internacional contradicen esa hipótesis.", "Daten", "von einer internationalen Gruppe ausgewerteten describe quién analizó los datos.", ["Un equipo internacional analizó unos datos que contradicen la hipótesis."]),
      phrase("Ein über Jahrzehnte hinweg untersuchtes Archiv wurde digitalisiert.", "Se digitalizó un archivo estudiado durante décadas.", "Archiv", "über Jahrzehnte hinweg untersuchtes es un atributo ampliado de Archiv.", ["El archivo, que llevaba décadas siendo estudiado, se digitalizó."]),
      phrase("Die am Institut entwickelte und später getestete Software erkennt Muster.", "El programa desarrollado en el instituto y probado después reconoce patrones.", "Institut", "am Institut entwickelte und später getestete incluye dos participios que describen el programa.", ["El instituto desarrolló y probó más tarde un programa capaz de reconocer patrones."]),
      phrase("Die in den Proben nachgewiesenen Stoffe gelten als unbedenklich.", "Las sustancias detectadas en las muestras se consideran inocuas.", "Proben", "in den Proben nachgewiesenen precisa dónde se detectaron las sustancias.", ["Las sustancias que aparecen en las muestras no se consideran peligrosas."]),
      phrase("Ein unter kontrollierten Bedingungen durchgeführter Versuch lieferte andere Ergebnisse.", "Un experimento realizado en condiciones controladas dio otros resultados.", "Versuch", "unter kontrollierten Bedingungen durchgeführter es un atributo ampliado de Versuch.", ["El ensayo realizado bajo condiciones controladas produjo resultados distintos."]),
      phrase("Die von mehreren Teams gleichzeitig beobachteten Sterne bilden ein seltenes System.", "Las estrellas observadas a la vez por varios equipos forman un sistema poco común.", "Sterne", "von mehreren Teams gleichzeitig beobachteten describe las estrellas.", ["Varios equipos observaron simultáneamente las estrellas de este sistema poco frecuente."]),
    ]),
    lesson("u54-l2", 2, "Museos y colecciones", "Describe obras, catálogos y archivos con precisión.", [
      phrase("Die von der Jury ausgewählten Beiträge werden nächste Woche gezeigt.", "Las obras elegidas por el jurado se expondrán la semana que viene.", "Jury", "von der Jury ausgewählten modifica Beiträge mediante un atributo participial.", ["La próxima semana se mostrarán las piezas que seleccionó el jurado."]),
      phrase("Ein aus privaten Sammlungen zusammengestellter Katalog erscheint im Herbst.", "En otoño aparecerá un catálogo elaborado a partir de colecciones privadas.", "Katalog", "aus privaten Sammlungen zusammengestellter describe cómo se creó el catálogo.", ["El catálogo reúne piezas de varias colecciones privadas y saldrá en otoño."], ["Im Herbst erscheint ein aus privaten Sammlungen zusammengestellter Katalog."]),
      phrase("Die im Vorjahr restaurierten Gemälde hängen wieder im Museum.", "Los cuadros restaurados el año pasado vuelven a estar colgados en el museo.", "Gemälde", "im Vorjahr restaurierten es un atributo participial de Gemälde.", ["El museo vuelve a mostrar los cuadros que restauró el año pasado."]),
      phrase("Die von der Autorin selbst übersetzten Gedichte bewahren ihren Klang.", "Los poemas traducidos por la propia autora conservan su sonoridad.", "Autorin", "von der Autorin selbst übersetzten indica quién hizo las traducciones.", ["La propia autora tradujo los poemas, que mantienen su musicalidad."]),
      phrase("Ein nach historischen Vorbildern entworfener Saal öffnet morgen.", "Mañana abre una sala diseñada según modelos históricos.", "Saal", "nach historischen Vorbildern entworfener modifica el sustantivo Saal.", ["Mañana se inaugura una sala cuyo diseño sigue modelos históricos."]),
      phrase("Die während des Festivals aufgenommenen Gespräche sind online verfügbar.", "Las conversaciones grabadas durante el festival están disponibles en línea.", "Festivals", "während des Festivals aufgenommenen describe las conversaciones.", ["Ya se pueden escuchar en internet las charlas grabadas durante el festival."]),
    ]),
    lesson("u54-l3", 3, "Historia de la ciudad", "Habla de hallazgos, monumentos y documentos históricos.", [
      phrase("Die im Stadtarchiv entdeckten Briefe werden nun katalogisiert.", "Las cartas descubiertas en el archivo municipal se están catalogando.", "Stadtarchiv", "im Stadtarchiv entdeckten precisa dónde aparecieron las cartas.", ["Ahora se está elaborando un catálogo de las cartas halladas en el archivo de la ciudad."]),
      phrase("Ein von Freiwilligen sorgfältig restauriertes Denkmal zieht Besucher an.", "Un monumento restaurado con esmero por voluntarios atrae a visitantes.", "Denkmal", "von Freiwilligen sorgfältig restauriertes describe quién restauró el monumento.", ["Los voluntarios restauraron cuidadosamente un monumento que ahora atrae al público."]),
      phrase("Die vor dem Krieg errichteten Gebäude stehen unter Schutz.", "Los edificios construidos antes de la guerra están protegidos.", "Gebäude", "vor dem Krieg errichteten es un atributo participial de Gebäude.", ["Los inmuebles anteriores a la guerra cuentan con protección."]),
      phrase("Die nach mehreren Jahren abgeschlossene Sanierung wertet den Platz auf.", "La renovación, terminada tras varios años, mejora la plaza.", "Sanierung", "nach mehreren Jahren abgeschlossene describe cuándo se terminó la renovación.", ["La plaza ha mejorado gracias a una renovación que duró varios años."]),
      phrase("Ein von Historikern neu bewerteter Vertrag veränderte die Grenzen.", "Un tratado reevaluado por historiadores modificó las fronteras.", "Historikern", "von Historikern neu bewerteter indica quién reevaluó el tratado.", ["Los historiadores volvieron a evaluar un tratado que modificó las fronteras."]),
      phrase("Die in der Region überlieferte Erzählung ist weithin bekannt.", "La historia transmitida en la región es muy conocida.", "Region", "in der Region überlieferte modifica el sustantivo Erzählung.", ["La narración, transmitida de generación en generación en la región, es muy conocida."]),
    ]),
  ]),
  unit("u55", 55, "Administración y estilo formal", "Lee instrucciones, resoluciones y procedimientos escritos.", [
    lesson("u55-l1", 1, "Solicitudes y expedientes", "Reconoce el estilo nominal de los trámites.", [
      phrase("Nach Eingang des Antrags erfolgt die Prüfung der Unterlagen.", "La documentación se revisará una vez recibida la solicitud.", "Antrags", "Nach Eingang y die Prüfung presentan acciones como sustantivos formales.", ["Tras la recepción de la solicitud, se examinará la documentación."]),
      phrase("Die Einreichung fehlender Nachweise ist bis Freitag möglich.", "Se pueden presentar los justificantes que faltan hasta el viernes.", "Einreichung", "Einreichung nominaliza einreichen y funciona como sujeto.", ["El plazo para aportar los documentos pendientes termina el viernes."], ["Bis Freitag ist die Einreichung fehlender Nachweise möglich."]),
      phrase("Aufgrund einer verspäteten Zustellung wurde die Frist verlängert.", "El plazo se amplió por un retraso en la entrega.", "Zustellung", "Aufgrund einer verspäteten Zustellung es un grupo nominal formal.", ["La demora en la notificación obligó a ampliar el plazo."]),
      phrase("Eine Bearbeitung des Vorgangs erfolgt nach Zahlungseingang.", "El expediente se tramitará una vez recibido el pago.", "Vorgangs", "Bearbeitung es un sustantivo de acción y des Vorgangs indica qué se tramita.", ["La tramitación comenzará cuando conste el pago."]),
      phrase("Zur Vermeidung weiterer Verzögerungen bitten wir um Rückmeldung.", "Para evitar más demoras, rogamos que nos respondan.", "Verzögerungen", "Zur Vermeidung es una construcción nominal que expresa finalidad.", ["Con el fin de evitar nuevos retrasos, solicitamos una respuesta."]),
      phrase("Die Entscheidung über die Vergabe wird schriftlich mitgeteilt.", "La decisión sobre la adjudicación se comunicará por escrito.", "Vergabe", "Entscheidung y Vergabe son sustantivos que condensan acciones.", ["La resolución de la adjudicación se notificará por escrito."]),
    ]),
    lesson("u55-l2", 2, "Normas y procedimientos", "Interpreta condiciones y obligaciones de un reglamento.", [
      phrase("Die Anhörung der betroffenen Parteien ist vorgesehen.", "Está prevista la audiencia de las partes afectadas.", "Anhörung", "Anhörung nominaliza anhören y funciona como sujeto.", ["Se prevé escuchar a todas las partes afectadas."]),
      phrase("Nach Abschluss der Untersuchung erfolgt die Bekanntgabe des Ergebnisses.", "El resultado se dará a conocer al terminar la investigación.", "Untersuchung", "Nach Abschluss y die Bekanntgabe expresan acciones mediante sustantivos.", ["Una vez concluida la investigación, se anunciará el resultado."], ["Die Bekanntgabe des Ergebnisses erfolgt nach Abschluss der Untersuchung."]),
      phrase("Die Übermittlung personenbezogener Daten bedarf einer Einwilligung.", "La transmisión de datos personales requiere consentimiento.", "Übermittlung", "Übermittlung nominaliza übermitteln y bedarf rige genitivo.", ["Para transmitir datos personales hace falta autorización."]),
      phrase("Zur Wahrung der Frist ist die Einreichung per E-Mail ausreichend.", "Para respetar el plazo, basta con presentar la documentación por correo electrónico.", "Wahrung", "Zur Wahrung expresa finalidad con el sustantivo Wahrung.", ["El envío por correo electrónico es suficiente para cumplir el plazo."]),
      phrase("Die weitere Bearbeitung setzt den Eingang aller Unterlagen voraus.", "La continuación del trámite requiere recibir toda la documentación.", "Bearbeitung", "Bearbeitung nominaliza bearbeiten y funciona como sujeto.", ["El expediente no seguirá tramitándose hasta que se reciba toda la documentación."]),
      phrase("Eine Rückerstattung bereits gezahlter Gebühren ist ausgeschlossen.", "No se contempla el reembolso de las tasas ya abonadas.", "Rückerstattung", "Rückerstattung es un sustantivo de acción que expresa devolver un pago.", ["Las tasas pagadas no se pueden recuperar."]),
    ]),
    lesson("u55-l3", 3, "Servicios públicos", "Comprende requisitos de registro, certificados y plazos.", [
      phrase("Die Ausstellung einer Bescheinigung erfolgt nach Identitätsprüfung.", "El certificado se expedirá tras comprobar la identidad.", "Ausstellung", "Ausstellung nominaliza ausstellen y nombra el proceso.", ["La emisión del certificado se hará una vez verificada la identidad."]),
      phrase("Bei Verlust des Dokuments ist unverzüglich eine Meldung erforderlich.", "Si se pierde el documento, hay que comunicarlo de inmediato.", "Dokuments", "Bei Verlust usa una nominalización para presentar la situación.", ["La pérdida del documento debe notificarse sin demora."]),
      phrase("Die Nutzung des Portals setzt eine Registrierung voraus.", "Para usar el portal es necesario registrarse.", "Nutzung", "Nutzung nominaliza nutzen y funciona como sujeto.", ["El acceso al portal requiere completar el registro."]),
      phrase("Zur Bestätigung des Termins bitten wir um eine kurze Nachricht.", "Para confirmar la cita, rogamos que nos envíe un mensaje breve.", "Bestätigung", "Zur Bestätigung expresa finalidad mediante un sustantivo.", ["Le pedimos un breve mensaje para confirmar la cita."]),
      phrase("Eine Verlängerung der Aufenthaltsdauer ist gesondert zu beantragen.", "La ampliación de la estancia debe solicitarse por separado.", "Aufenthaltsdauer", "Verlängerung nominaliza verlängern y es el sujeto de la oración.", ["Para prolongar la estancia, hay que presentar una solicitud aparte."]),
      phrase("Die Änderung persönlicher Daten erfolgt im Bürgerbüro.", "Los datos personales se modifican en la oficina de atención ciudadana.", "Änderung", "Änderung nominaliza ändern y presenta formalmente el proceso.", ["La actualización de los datos personales se realiza en la oficina municipal."]),
    ]),
  ]),
  unit("u56", 56, "Salud y sistema sanitario", "Interpreta hipótesis, fuentes y afirmaciones clínicas.", [
    lesson("u56-l1", 1, "Efectos y tratamientos", "Expresa rumores y deducciones con modales subjetivos.", [
      phrase("Die Behandlung soll gut vertragen worden sein.", "Según se dice, el tratamiento se toleró bien.", "Behandlung", "soll vertragen worden sein transmite información atribuida sobre el tratamiento.", ["Al parecer, el tratamiento fue bien tolerado."]),
      phrase("Der Patient will keine Nebenwirkungen bemerkt haben.", "El paciente afirma que no notó efectos secundarios.", "Patient", "will bemerkt haben reproduce la afirmación del paciente.", ["El paciente asegura no haber notado ningún efecto adverso."], ["Keine Nebenwirkungen will der Patient bemerkt haben."]),
      phrase("Die Beschwerden dürften durch das neue Präparat ausgelöst worden sein.", "Es probable que el nuevo medicamento haya causado las molestias.", "Beschwerden", "dürften ausgelöst worden sein expresa una suposición sobre la causa.", ["Las molestias seguramente se deben al nuevo fármaco."]),
      phrase("Die Symptome müssten bald nachlassen.", "Los síntomas deberían remitir pronto.", "Symptome", "müssten expresa una expectativa fundada, no una obligación.", ["En principio, los síntomas tendrían que disminuir pronto."]),
      phrase("Die Ärztin soll eine zweite Meinung eingeholt haben.", "Según se dice, la médica ha pedido una segunda opinión.", "Ärztin", "soll eingeholt haben presenta como noticia indirecta una acción pasada.", ["Al parecer, la doctora consultó a otro especialista."]),
      phrase("Die Werte dürften inzwischen stabil sein.", "Es probable que los valores ya estén estables.", "Werte", "dürften sein expresa una valoración probable del estado actual.", ["A estas alturas, seguramente los valores se han estabilizado."]),
    ]),
    lesson("u56-l2", 2, "Informes de pacientes", "Separa afirmaciones de conclusiones probables.", [
      phrase("Der Impfstoff soll besonders schnell wirken.", "Según se dice, la vacuna hace efecto muy rápido.", "Impfstoff", "soll wirken transmite una información atribuida a otras fuentes.", ["Al parecer, la vacuna actúa con especial rapidez."]),
      phrase("Die Klinik will die Wartezeit halbiert haben.", "La clínica afirma que ha reducido a la mitad el tiempo de espera.", "Klinik", "will halbiert haben presenta la afirmación de la propia clínica.", ["La clínica asegura que ahora se espera la mitad."]),
      phrase("Die Ursache dürfte eine seltene Unverträglichkeit sein.", "Es probable que la causa sea una intolerancia poco frecuente.", "Ursache", "dürfte sein introduce una conclusión probable.", ["Seguramente se trata de una intolerancia poco habitual."]),
      phrase("Die Patientin müsste inzwischen auf dem Weg der Besserung sein.", "A estas alturas, la paciente probablemente estará mejorando.", "Patientin", "müsste sein expresa una deducción sobre su recuperación.", ["En principio, la paciente ya tendría que estar recuperándose."]),
      phrase("Das Medikament soll die Genesung beschleunigen.", "Según se afirma, el medicamento acelera la recuperación.", "Medikament", "soll beschleunigen atribuye la información a una fuente externa.", ["Al parecer, el fármaco ayuda a recuperarse antes."]),
      phrase("Der Eingriff dürfte ohne Komplikationen verlaufen sein.", "Es probable que la intervención transcurriera sin complicaciones.", "Eingriff", "dürfte verlaufen sein expresa una suposición sobre un hecho pasado.", ["La operación seguramente salió sin complicaciones."]),
    ]),
    lesson("u56-l3", 3, "Datos de salud pública", "Comenta tendencias e hipótesis con cautela.", [
      phrase("Die Zahl der Fälle soll deutlich gesunken sein.", "Según se informa, el número de casos ha bajado mucho.", "Fälle", "soll gesunken sein transmite un dato no confirmado directamente.", ["Al parecer, los casos han disminuido de forma notable."]),
      phrase("Der Sprecher will keine Zunahme der Infektionen festgestellt haben.", "El portavoz afirma que no ha detectado un aumento de las infecciones.", "Sprecher", "will festgestellt haben atribuye al portavoz la afirmación.", ["El portavoz asegura que las infecciones no han aumentado."]),
      phrase("Die Tests dürften die neue Variante erkennen.", "Es probable que las pruebas detecten la nueva variante.", "Tests", "dürften erkennen expresa una valoración sobre la capacidad de las pruebas.", ["En principio, las pruebas deberían detectar la nueva variante."]),
      phrase("Die Impfung soll auch ältere Menschen schützen.", "Según se afirma, la vacuna protege también a las personas mayores.", "Impfung", "soll schützen transmite una afirmación atribuida a fuentes externas.", ["Al parecer, la vacuna ofrece protección a las personas mayores."]),
      phrase("Der Patient müsste die Praxis bereits erreicht haben.", "Es probable que el paciente ya haya llegado a la consulta.", "Praxis", "müsste erreicht haben expresa una deducción sobre una acción pasada.", ["A estas horas, seguramente el paciente ya está en la consulta."]),
      phrase("Die Nebenwirkungen sollen nur leicht gewesen sein.", "Según se informa, los efectos secundarios fueron leves.", "Nebenwirkungen", "sollen gewesen sein atribuye a una fuente una valoración pasada.", ["Al parecer, solo hubo efectos adversos leves."]),
    ]),
  ]),
  unit("u57", 57, "Medio ambiente y clima", "Analiza datos, medidas y efectos de la adaptación climática.", [
    lesson("u57-l1", 1, "Mediciones y previsiones", "Combina información nominal y atributos ampliados.", [
      phrase("Die von Messstationen erfassten Temperaturdaten zeigen einen Rekord.", "Los datos de temperatura registrados por las estaciones indican un récord.", "Temperaturdaten", "von Messstationen erfassten precisa el origen de los datos.", ["Las estaciones han registrado temperaturas sin precedentes."]),
      phrase("Nach Auswertung der Satellitenbilder veröffentlichte das Institut neue Zahlen.", "El instituto publicó nuevos datos tras analizar las imágenes por satélite.", "Satellitenbilder", "Nach Auswertung presenta la acción mediante una nominalización.", ["El análisis de las imágenes de satélite permitió al instituto publicar nuevos datos."]),
      phrase("Die in Küstennähe gemessenen Werte steigen weiter.", "Los valores medidos cerca de la costa siguen aumentando.", "Küstennähe", "in Küstennähe gemessenen describe dónde se tomaron las mediciones.", ["Continúan subiendo las cifras registradas en las zonas costeras."]),
      phrase("Die von Dürren bedrohten Ernten fallen kleiner aus.", "Las cosechas amenazadas por la sequía son menos abundantes.", "Dürren", "von Dürren bedrohten modifica Ernten y señala la amenaza.", ["La sequía pone en peligro cosechas menos abundantes."]),
      phrase("Zur Verringerung des Energieverbrauchs werden Gebäude saniert.", "Se rehabilitan edificios para reducir el consumo energético.", "Energieverbrauchs", "Zur Verringerung expresa finalidad con una nominalización.", ["La rehabilitación de edificios permite gastar menos energía."]),
      phrase("Die in den Bericht aufgenommenen Prognosen werden jährlich aktualisiert.", "Las previsiones incluidas en el informe se actualizan cada año.", "Bericht", "in den Bericht aufgenommenen describe qué previsiones se actualizan.", ["Cada año se revisan las previsiones que recoge el informe."]),
    ]),
    lesson("u57-l2", 2, "Suelo y agricultura", "Describe consecuencias y respuestas ante condiciones cambiantes.", [
      phrase("Der über mehrere Jahre erhobene Datensatz macht Veränderungen sichtbar.", "El conjunto de datos recopilado durante varios años permite ver los cambios.", "Datensatz", "über mehrere Jahre erhobene modifica Datensatz mediante Partizip II.", ["Los datos recogidos a lo largo de varios años muestran los cambios."]),
      phrase("Die durch intensive Landwirtschaft belasteten Böden benötigen Erholung.", "Los suelos afectados por la agricultura intensiva necesitan recuperarse.", "Landwirtschaft", "durch intensive Landwirtschaft belasteten explica el origen del daño.", ["Hace falta recuperar los suelos afectados por la agricultura intensiva."]),
      phrase("Nach dem Rückgang der Emissionen verbesserte sich die Luftqualität.", "La calidad del aire mejoró tras reducirse las emisiones.", "Emissionen", "Nach dem Rückgang presenta la causa temporal con un sustantivo.", ["Al disminuir las emisiones, mejoró la calidad del aire."], ["Die Luftqualität verbesserte sich nach dem Rückgang der Emissionen."]),
      phrase("Die von Fachleuten empfohlene Maßnahme wurde umgesetzt.", "La medida recomendada por especialistas se puso en práctica.", "Maßnahme", "von Fachleuten empfohlene es un atributo participial que identifica la medida.", ["Se aplicó la medida que aconsejaban los expertos."]),
      phrase("Die bereits versiegelten Flächen speichern kaum Regenwasser.", "Las zonas ya impermeabilizadas apenas absorben agua de lluvia.", "Flächen", "bereits versiegelten describe el estado de las superficies.", ["Las superficies con el suelo sellado casi no retienen agua pluvial."]),
      phrase("Zur Anpassung an häufigere Hitzewellen pflanzt die Stadt Bäume.", "El ayuntamiento planta árboles para adaptarse a las olas de calor más frecuentes.", "Hitzewellen", "Zur Anpassung expresa la finalidad mediante una nominalización.", ["La ciudad planta árboles como respuesta al aumento de las olas de calor."]),
    ]),
    lesson("u57-l3", 3, "Protección de ecosistemas", "Explica medidas para conservar paisajes y especies.", [
      phrase("Die entlang des Flusses angelegten Schutzstreifen halten Schadstoffe zurück.", "Las franjas protectoras creadas junto al río retienen contaminantes.", "Schutzstreifen", "entlang des Flusses angelegten precisa dónde se crearon las franjas.", ["Las barreras vegetales de la ribera frenan la llegada de contaminantes."]),
      phrase("Die von der Regierung angekündigte Förderung beginnt im Herbst.", "La ayuda anunciada por el Gobierno empieza en otoño.", "Regierung", "von der Regierung angekündigte describe quién anunció la ayuda.", ["En otoño comenzará la subvención anunciada por el Ejecutivo."]),
      phrase("Nach Abschluss der Renaturierung kehrten seltene Vögel zurück.", "Al terminar la recuperación ambiental, volvieron aves poco comunes.", "Renaturierung", "Nach Abschluss sitúa el regreso después de una acción nominalizada.", ["Una vez restaurado el entorno, regresaron especies de aves poco frecuentes."]),
      phrase("Die während der Dürre gesammelten Daten stützen die Prognose.", "Los datos recogidos durante la sequía respaldan la previsión.", "Dürre", "während der Dürre gesammelten precisa cuándo se reunieron los datos.", ["La previsión se apoya en datos recopilados durante la sequía."]),
      phrase("Eine Verringerung des Verbrauchs bleibt das wichtigste Ziel.", "Reducir el consumo sigue siendo el objetivo principal.", "Verbrauchs", "Verringerung nominaliza verringern y funciona como sujeto.", ["El objetivo prioritario continúa siendo gastar menos recursos."]),
      phrase("Die neu ausgewiesenen Schutzgebiete stehen unter besonderem Schutz.", "Las nuevas zonas protegidas cuentan con una protección especial.", "Schutzgebiete", "neu ausgewiesenen describe las áreas que acaban de designarse.", ["Se ha otorgado una protección especial a las zonas declaradas recientemente."]),
    ]),
  ]),
  unit("u58", 58, "Educación e investigación", "Debate resultados y compromisos en instituciones académicas.", [
    lesson("u58-l1", 1, "Proyectos universitarios", "Usa grupos verbales funcionales en el ámbito académico.", [
      phrase("Die Hochschule stellte den Teilnehmenden neue Ressourcen zur Verfügung.", "La universidad puso nuevos recursos a disposición de los participantes.", "Hochschule", "Ressourcen zur Verfügung stellen es un grupo verbal funcional.", ["La universidad facilitó nuevos recursos a quienes participaron."]),
      phrase("Der Senat brachte einen Vorschlag zur Sprache.", "El senado académico planteó una propuesta.", "Senat", "einen Vorschlag zur Sprache bringen significa introducirlo en el debate.", ["El órgano académico puso una propuesta sobre la mesa."], ["Einen Vorschlag brachte der Senat zur Sprache."]),
      phrase("Die Forschenden kamen zu einem eindeutigen Ergebnis.", "El equipo investigador llegó a un resultado claro.", "Forschenden", "zu einem Ergebnis kommen es un grupo verbal funcional.", ["La investigación condujo a una conclusión inequívoca."]),
      phrase("Die Leitung traf eine Vereinbarung mit der Bibliothek.", "La dirección llegó a un acuerdo con la biblioteca.", "Leitung", "eine Vereinbarung treffen significa acordar formalmente algo.", ["La dirección pactó unas condiciones con la biblioteca."]),
      phrase("Die Universität nahm eine Prüfung der Förderanträge vor.", "La universidad revisó las solicitudes de financiación.", "Universität", "eine Prüfung vornehmen es un grupo verbal funcional formal.", ["La universidad llevó a cabo una revisión de las solicitudes de financiación."]),
      phrase("Die Fakultät zog eine Bilanz des Programms.", "La facultad hizo balance del programa.", "Fakultät", "eine Bilanz ziehen es una expresión funcional que resume resultados.", ["La facultad evaluó los resultados del programa."]),
    ]),
    lesson("u58-l2", 2, "Métodos y resultados", "Expresa evaluaciones, contribuciones y medidas.", [
      phrase("Die Gruppe führte eine Untersuchung zur Lernzeit durch.", "El grupo realizó un estudio sobre el tiempo de aprendizaje.", "Gruppe", "eine Untersuchung durchführen es un grupo verbal funcional.", ["El equipo llevó a cabo una investigación sobre cuánto se tarda en aprender."]),
      phrase("Die Teilnehmenden leisteten einen Beitrag zur Diskussion.", "Los participantes contribuyeron al debate.", "Teilnehmenden", "einen Beitrag leisten equivale a contribuir.", ["Las personas asistentes aportaron ideas al debate."], ["Einen Beitrag zur Diskussion leisteten die Teilnehmenden."]),
      phrase("Das Gremium stellte eine Frage zur Finanzierung.", "El comité planteó una pregunta sobre la financiación.", "Gremium", "eine Frage stellen es una expresión verbal funcional.", ["El órgano pidió aclaraciones sobre cómo se financiaría."]),
      phrase("Die Forschenden setzten sich mit den Ergebnissen auseinander.", "Los investigadores analizaron los resultados en profundidad.", "Forschenden", "sich mit etwas auseinandersetzen significa examinarlo con detenimiento.", ["El equipo investigador estudió a fondo los resultados."]),
      phrase("Der Bericht kommt zu dem Schluss, dass die Methode wirkt.", "El informe concluye que el método funciona.", "Bericht", "zu dem Schluss kommen introduce la conclusión de un análisis.", ["La conclusión del informe es que el método da resultado."]),
      phrase("Die Universität ergriff Maßnahmen zur Verbesserung der Betreuung.", "La universidad tomó medidas para mejorar la atención.", "Universität", "Maßnahmen ergreifen significa tomar medidas.", ["La universidad puso en marcha acciones para ofrecer mejor apoyo."]),
    ]),
    lesson("u58-l3", 3, "Acuerdos y cooperación", "Describe decisiones compartidas y resultados institucionales.", [
      phrase("Die Dozentin nahm die Ergebnisse zum Anlass, den Kurs anzupassen.", "La docente aprovechó los resultados para adaptar el curso.", "Dozentin", "etwas zum Anlass nehmen significa utilizarlo como motivo para actuar.", ["Los resultados llevaron a la profesora a modificar el curso."]),
      phrase("Die Studierenden brachten eigene Vorschläge zur Diskussion.", "Los estudiantes plantearon sus propias propuestas.", "Studierenden", "eigene Vorschläge zur Diskussion bringen significa proponer ideas para debatirlas.", ["El alumnado puso sus propias propuestas sobre la mesa."]),
      phrase("Die Kommission setzte neue Kriterien in Kraft.", "La comisión hizo entrar en vigor nuevos criterios.", "Kommission", "Kriterien in Kraft setzen es un grupo verbal funcional.", ["La comisión empezó a aplicar nuevas pautas."]),
      phrase("Die Fachbereiche kamen überein, Lehrmaterialien zu teilen.", "Los departamentos acordaron compartir materiales didácticos.", "Fachbereiche", "übereinkommen significa llegar a un acuerdo.", ["Los departamentos acordaron poner en común los materiales de enseñanza."]),
      phrase("Die Hochschule stellt eine Datenbank zur Verfügung.", "La universidad pone a disposición una base de datos.", "Hochschule", "eine Datenbank zur Verfügung stellen es un grupo verbal funcional.", ["La universidad facilita acceso a una base de datos."]),
      phrase("Der Ausschuss nahm Stellung zu den Ergebnissen.", "El comité se pronunció sobre los resultados.", "Ausschuss", "Stellung nehmen zu significa expresar una valoración sobre algo.", ["El comité dio su opinión sobre los resultados."]),
    ]),
  ]),
  unit("u59", 59, "Medios y opinión pública", "Comprende debates, rectificaciones y responsabilidades.", [
    lesson("u59-l1", 1, "Correcciones y debates", "Expresa acciones editoriales con grupos verbales funcionales.", [
      phrase("Die Redaktion nahm eine Korrektur des Artikels vor.", "La redacción corrigió el artículo.", "Redaktion", "eine Korrektur vornehmen equivale a corregir algo.", ["El equipo editorial introdujo una corrección en el artículo."]),
      phrase("Die Zeitung brachte eine Debatte über Wohnraum in Gang.", "El periódico puso en marcha un debate sobre la vivienda.", "Zeitung", "eine Debatte in Gang bringen significa iniciarla.", ["El diario abrió un debate sobre el acceso a la vivienda."], ["Eine Debatte über Wohnraum brachte die Zeitung in Gang."]),
      phrase("Der Sender übernahm Verantwortung für den Fehler.", "La cadena asumió la responsabilidad por el error.", "Sender", "Verantwortung übernehmen es un grupo verbal funcional.", ["La cadena reconoció que era responsable del fallo."]),
      phrase("Die Sprecherin übte Kritik an der Darstellung.", "La portavoz criticó la forma de presentar la información.", "Sprecherin", "Kritik üben an significa expresar una crítica.", ["La portavoz cuestionó cómo se había contado la noticia."]),
      phrase("Das Portal stellte Hintergrundinformationen zur Verfügung.", "El portal ofreció información de contexto.", "Portal", "Hintergrundinformationen zur Verfügung stellen significa facilitarlas.", ["La plataforma proporcionó datos para contextualizar la noticia."]),
      phrase("Die Diskussion nahm eine unerwartete Wendung.", "El debate dio un giro inesperado.", "Diskussion", "eine Wendung nehmen es un grupo verbal funcional.", ["La conversación cambió de rumbo de forma inesperada."]),
    ]),
    lesson("u59-l2", 2, "Informes y fuentes", "Atribuye versiones y valora su grado de certeza.", [
      phrase("Der Sprecher soll interne Dokumente weitergegeben haben.", "Según se dice, el portavoz filtró documentos internos.", "Sprecher", "soll weitergegeben haben transmite una acusación no confirmada.", ["Al parecer, el portavoz hizo llegar documentos internos a terceros."]),
      phrase("Die Redaktion will alle Angaben überprüft haben.", "La redacción afirma que ha comprobado todos los datos.", "Redaktion", "will überprüft haben presenta una afirmación de la propia redacción.", ["El equipo editorial asegura haber verificado toda la información."], ["Alle Angaben will die Redaktion überprüft haben."]),
      phrase("Die Meldung dürfte auf einer Verwechslung beruhen.", "Es probable que la noticia se deba a una confusión.", "Meldung", "dürfte beruhen expresa una hipótesis probable sobre el origen de la noticia.", ["Seguramente, la información surgió de una equivocación."]),
      phrase("Der Bericht müsste inzwischen veröffentlicht worden sein.", "Es probable que el informe ya se haya publicado.", "Bericht", "müsste veröffentlicht worden sein formula una deducción sobre una acción pasada.", ["A estas alturas, el informe tendría que estar publicado."]),
      phrase("Die Quelle soll weitere Belege angekündigt haben.", "Según se informa, la fuente ha anunciado más pruebas.", "Quelle", "soll angekündigt haben atribuye una declaración a una fuente indirecta.", ["Al parecer, la fuente prometió aportar más pruebas."]),
      phrase("Die Aufnahme dürfte nachträglich verändert worden sein.", "Es probable que la grabación se modificara después.", "Aufnahme", "dürfte verändert worden sein expresa una sospecha sobre la grabación.", ["Seguramente, alguien retocó la grabación más tarde."]),
    ]),
    lesson("u59-l3", 3, "Reputación y responsabilidad", "Habla de respuestas públicas y compromisos editoriales.", [
      phrase("Der Verlag hat eine Erklärung zu dem Vorfall abgegeben.", "La editorial ha emitido un comunicado sobre el incidente.", "Verlag", "eine Erklärung abgeben es un grupo verbal funcional formal.", ["La editorial publicó una declaración sobre lo ocurrido."]),
      phrase("Die Moderatorin stellte eine Frage zur Verantwortung.", "La presentadora hizo una pregunta sobre la responsabilidad.", "Moderatorin", "eine Frage stellen es una expresión verbal funcional.", ["La presentadora preguntó quién debía asumir la responsabilidad."]),
      phrase("Das Unternehmen zog seine Beschwerde zurück.", "La empresa retiró su reclamación.", "Unternehmen", "eine Beschwerde zurückziehen es un grupo verbal funcional.", ["La compañía decidió retirar la queja."]),
      phrase("Die Redaktion räumte einen Fehler ein.", "La redacción reconoció un error.", "Redaktion", "einen Fehler einräumen significa admitirlo.", ["El equipo editorial admitió que se había equivocado."]),
      phrase("Der Ausschuss setzte eine Untersuchung in Gang.", "El comité puso en marcha una investigación.", "Ausschuss", "eine Untersuchung in Gang setzen significa iniciarla.", ["El comité inició una investigación sobre el caso."]),
      phrase("Die Zeitung nahm den Leserbrief zum Anlass für eine Debatte.", "El periódico aprovechó la carta del lector para abrir un debate.", "Leserbrief", "etwas zum Anlass nehmen significa utilizarlo como motivo para actuar.", ["La carta de un lector motivó un debate en el periódico."]),
    ]),
  ]),
  unit("u60", 60, "Cooperación internacional", "Lee acuerdos, requisitos y medidas en un registro formal.", [
    lesson("u60-l1", 1, "Acuerdos internacionales", "Usa nominalizaciones en comunicados y convenios.", [
      phrase("Nach Unterzeichnung des Abkommens beginnt die gemeinsame Umsetzung.", "La aplicación conjunta empieza tras la firma del acuerdo.", "Unterzeichnung", "Nach Unterzeichnung expresa el momento mediante un sustantivo de acción.", ["Una vez firmado el acuerdo, comienza la aplicación conjunta."]),
      phrase("Die Bereitstellung technischer Unterstützung erfolgt auf Anfrage.", "El apoyo técnico se proporcionará previa solicitud.", "Bereitstellung", "Bereitstellung nominaliza bereitstellen y forma parte del estilo formal.", ["La asistencia técnica se facilitará cuando se solicite."], ["Technische Unterstützung erfolgt auf Anfrage."]),
      phrase("Aufgrund veränderter Rahmenbedingungen wurde eine Anpassung beschlossen.", "Se aprobó una modificación debido a cambios en las circunstancias.", "Rahmenbedingungen", "Aufgrund veränderter Rahmenbedingungen presenta la causa con un grupo nominal.", ["Los cambios en el contexto motivaron la aprobación de un ajuste."]),
      phrase("Die Einhaltung der vereinbarten Standards wird regelmäßig überprüft.", "El cumplimiento de las normas acordadas se revisa con regularidad.", "Standards", "Einhaltung nominaliza einhalten y funciona como sujeto.", ["Se comprueba periódicamente que se respeten los estándares acordados."]),
      phrase("Zur Förderung des Austauschs ist eine Erweiterung des Programms vorgesehen.", "Para fomentar el intercambio, se prevé ampliar el programa.", "Austauschs", "Zur Förderung expresa finalidad mediante una nominalización.", ["La ampliación del programa busca impulsar el intercambio."]),
      phrase("Die Genehmigung zusätzlicher Mittel steht noch aus.", "La aprobación de fondos adicionales sigue pendiente.", "Genehmigung", "Genehmigung nominaliza genehmigen y funciona como sujeto.", ["Aún falta que se autoricen más recursos."]),
    ]),
    lesson("u60-l2", 2, "Normas y cumplimiento", "Comprende procedimientos, plazos y requisitos formales.", [
      phrase("Die Prüfung eingereichter Anträge erfolgt in mehreren Schritten.", "La revisión de las solicitudes presentadas se realiza en varias fases.", "Prüfung", "Prüfung nominaliza prüfen y presenta el proceso formalmente.", ["Las solicitudes recibidas se examinan en varias etapas."]),
      phrase("Vor Veröffentlichung der Ergebnisse ist eine Freigabe erforderlich.", "Antes de publicar los resultados, es necesaria una autorización.", "Veröffentlichung", "Vor Veröffentlichung expresa el momento mediante un sustantivo.", ["Los resultados no se pueden publicar sin autorización previa."], ["Eine Freigabe ist vor Veröffentlichung der Ergebnisse erforderlich."]),
      phrase("Die Nichteinhaltung der Frist führt zur Zurückweisung.", "El incumplimiento del plazo provoca el rechazo.", "Nichteinhaltung", "Nichteinhaltung convierte nicht einhalten en un sustantivo formal.", ["Si no se cumple el plazo, se rechazará la solicitud."]),
      phrase("Nach Eingang der Beschwerde wird eine Untersuchung eingeleitet.", "Al recibirse la reclamación, se inicia una investigación.", "Beschwerde", "Nach Eingang presenta formalmente el momento en que comienza la investigación.", ["La investigación se pondrá en marcha una vez recibida la queja."]),
      phrase("Die Übermittlung vertraulicher Daten bedarf besonderer Sicherung.", "La transmisión de datos confidenciales requiere protección especial.", "Übermittlung", "Übermittlung nominaliza übermitteln; bedarf rige genitivo.", ["Los datos confidenciales deben transmitirse con medidas de seguridad especiales."]),
      phrase("Zur Umsetzung der Vereinbarung wurde eine Arbeitsgruppe eingerichtet.", "Se creó un grupo de trabajo para aplicar el acuerdo.", "Vereinbarung", "Zur Umsetzung presenta la finalidad mediante una nominalización.", ["La puesta en práctica del acuerdo quedó a cargo de un grupo de trabajo."]),
    ]),
    lesson("u60-l3", 3, "Comercio y diplomacia", "Describe medidas y cambios en relaciones entre países.", [
      phrase("Die Aufnahme diplomatischer Beziehungen erfolgte im Frühjahr.", "El establecimiento de relaciones diplomáticas tuvo lugar en primavera.", "Aufnahme", "Aufnahme nominaliza aufnehmen y es habitual en el estilo formal.", ["Las relaciones diplomáticas se iniciaron en primavera."]),
      phrase("Zur Beschleunigung des Warenverkehrs werden Grenzkontrollen vereinfacht.", "Se simplifican los controles fronterizos para agilizar el tránsito de mercancías.", "Warenverkehrs", "Zur Beschleunigung expresa finalidad con una nominalización.", ["La simplificación de los controles busca acelerar el tráfico de mercancías."]),
      phrase("Die Ausweitung des Handels setzt verlässliche Regeln voraus.", "La ampliación del comercio requiere normas fiables.", "Ausweitung", "Ausweitung nominaliza ausweiten y funciona como sujeto.", ["Para ampliar el comercio hacen falta reglas fiables."]),
      phrase("Nach Bekanntgabe des Ergebnisses stieg der Kurs deutlich.", "La cotización subió notablemente tras anunciarse el resultado.", "Bekanntgabe", "Nach Bekanntgabe sitúa el cambio después de una acción nominalizada.", ["El valor aumentó de forma clara una vez conocido el resultado."]),
      phrase("Die Lieferung benötigter Geräte erfolgt bis Jahresende.", "Los equipos necesarios se entregarán antes de que acabe el año.", "Lieferung", "Lieferung nominaliza liefern y presenta formalmente la entrega.", ["La entrega del material necesario se realizará antes de fin de año."]),
      phrase("Eine Aussetzung des Abkommens ist derzeit nicht vorgesehen.", "Por ahora no se contempla suspender el acuerdo.", "Aussetzung", "Aussetzung nominaliza aussetzen y funciona como sujeto.", ["De momento, no está prevista la suspensión del convenio."]),
    ]),
  ]),
];
