import type { LessonDraft, Phrase, UnitDraft } from "./units";

const phrase = (
  german: string,
  spanish: string,
  blankWord: string,
  explanation: string,
  spanishAlt?: string[],
  germanAlt?: string[],
): Phrase => ({
  german,
  spanish,
  blankWord,
  explanation,
  ...(spanishAlt ? { spanishAlt } : {}),
  ...(germanAlt ? { germanAlt } : {}),
});

const lesson = (
  id: string,
  order: number,
  title: string,
  description: string,
  phrases: Phrase[],
): LessonDraft => ({ id, order, title, description, xpReward: 10, phrases });

const unit = (
  id: string,
  order: number,
  title: string,
  description: string,
  lessons: LessonDraft[],
): UnitDraft => ({
  id,
  order,
  title,
  description,
  color: "#FF9600",
  cefrLevel: "B1.2",
  lessons,
});

export const b1_2UnitDrafts: UnitDraft[] = [
  unit("u34", 34, "Experiencias laborales", "Relata proyectos y decisiones anteriores.", [
    lesson("u34-l1", 1, "Antes de empezar", "Ordena hechos pasados con el Plusquamperfekt.", [
      phrase("Als ich im neuen Büro anfing, hatte das Team schon ein Projekt gestartet.", "Cuando empecé en la nueva oficina, el equipo ya había puesto en marcha un proyecto.", "Projekt", "hatte gestartet indica que el equipo inició el proyecto antes de que yo empezara.", ["Al incorporarme a la oficina, el equipo ya había iniciado un proyecto."]),
      phrase("Nachdem die Firma den Vertrag geprüft hatte, unterschrieb die Chefin ihn.", "Después de que la empresa revisara el contrato, la directora lo firmó.", "Vertrag", "La subordinada con nachdem expresa la acción anterior a la firma.", ["Una vez revisado el contrato por la empresa, la directora lo firmó."], ["Die Chefin unterschrieb den Vertrag, nachdem die Firma ihn geprüft hatte."]),
      phrase("Bevor wir den Kunden anriefen, hatten wir alle Zahlen kontrolliert.", "Antes de llamar al cliente, habíamos comprobado todas las cifras.", "Zahlen", "hatten kontrolliert presenta la comprobación como anterior a la llamada.", ["Habíamos revisado todas las cifras antes de llamar al cliente."]),
      phrase("Wir hatten bereits eine passende Lösung gefunden.", "Ya habíamos encontrado una solución adecuada.", "Lösung", "hatten gefunden es Plusquamperfekt y sitúa el hallazgo antes de otro momento pasado.", ["Ya habíamos dado con una solución apropiada."]),
      phrase("Als der Termin begann, waren die Gäste schon eingetroffen.", "Cuando empezó la cita, los invitados ya habían llegado.", "Gäste", "waren eingetroffen es Plusquamperfekt con el auxiliar sein.", ["Al comenzar la reunión, los invitados ya habían llegado."]),
      phrase("Die Abteilung hatte die neuen Regeln rechtzeitig erklärt.", "El departamento había explicado las nuevas normas a tiempo.", "Regeln", "hatte erklärt sitúa la explicación antes de otro hecho pasado.", ["El departamento ya había explicado las nuevas reglas."]),
    ]),
    lesson("u34-l2", 2, "Retrasos y soluciones", "Describe qué había ocurrido antes de una avería.", [
      phrase("Der Techniker hatte die Ursache gefunden, bevor das System ausfiel.", "El técnico había encontrado la causa antes de que fallara el sistema.", "Ursache", "hatte gefunden describe la acción anterior al fallo del sistema.", ["El técnico ya había localizado la causa cuando se averió el sistema."]),
      phrase("Nachdem die Daten gesichert worden waren, startete das Update.", "Después de que se hubieran guardado los datos, comenzó la actualización.", "Daten", "waren gesichert worden es Plusquamperfekt pasivo.", ["Una vez guardados los datos, comenzó la actualización."]),
      phrase("Als wir die Baustelle erreichten, hatte der Regen bereits aufgehört.", "Cuando llegamos a la obra, ya había dejado de llover.", "Baustelle", "hatte aufgehört indica que la lluvia cesó antes de nuestra llegada.", ["Al llegar a la obra, la lluvia ya había parado."]),
      phrase("Die Firma hatte den Zeitplan genau geprüft.", "La empresa había revisado el calendario con detalle.", "Zeitplan", "hatte geprüft expresa una revisión anterior a otro momento pasado.", ["La empresa ya había comprobado minuciosamente el calendario."]),
      phrase("Bevor die Reparatur begann, hatte die Leitung den Raum geräumt.", "Antes de que empezara la reparación, la dirección había desalojado la sala.", "Reparatur", "hatte geräumt sitúa el desalojo antes del inicio de la reparación.", ["La dirección ya había vaciado la sala cuando comenzó la reparación."]),
      phrase("Nach der Pause war der Strom wieder ausgefallen.", "Después de la pausa, la luz había vuelto a fallar.", "Strom", "war ausgefallen es Plusquamperfekt con sein y describe un fallo anterior al relato.", ["La electricidad había vuelto a cortarse tras la pausa."]),
    ]),
    lesson("u34-l3", 3, "Informar al equipo", "Explica cómo se resolvió un problema con un cliente.", [
      phrase("Der Kunde wartete, weil wir die Lieferung schon bestellt hatten.", "El cliente esperaba porque ya habíamos pedido el envío.", "Lieferung", "hatten bestellt presenta el pedido como anterior a la espera.", ["El cliente aguardaba porque ya habíamos encargado el envío."]),
      phrase("Nachdem die Kollegin den Fehler entdeckt hatte, informierte sie den Chef.", "Después de que la compañera detectara el error, informó al jefe.", "Fehler", "La acción con entdecken ocurre antes de que ella informe al jefe.", ["Una vez detectado el error, la compañera avisó al jefe."], ["Die Kollegin informierte den Chef, nachdem sie den Fehler entdeckt hatte."]),
      phrase("Wir hatten dem Team die neuen Aufgaben erklärt.", "Habíamos explicado las nuevas tareas al equipo.", "Aufgaben", "hatten erklärt es Plusquamperfekt; dem Team es el destinatario en dativo.", ["Ya habíamos comunicado las nuevas tareas al equipo."]),
      phrase("Die Sitzung hatte pünktlich begonnen.", "La reunión había empezado puntual.", "Sitzung", "hatte begonnen presenta el inicio como anterior a otro hecho pasado.", ["La reunión ya había comenzado a su hora."]),
      phrase("Bevor der Kunde zurückkam, hatten wir das Problem gelöst.", "Antes de que volviera el cliente, habíamos resuelto el problema.", "Problem", "hatten gelöst sitúa la solución antes del regreso del cliente.", ["Ya habíamos solucionado el problema cuando volvió el cliente."]),
      phrase("Das Unternehmen hatte zuvor eine andere Lösung angeboten.", "La empresa había ofrecido antes otra solución.", "Unternehmen", "hatte angeboten es Plusquamperfekt y marca una oferta anterior.", ["La empresa ya había propuesto otra solución."]),
    ]),
  ]),
  unit("u35", 35, "Vivienda y reparaciones", "Pide arreglos y comprende las normas de una comunidad.", [
    lesson("u35-l1", 1, "Averías en casa", "Usa la pasiva con modales para solicitar reparaciones.", [
      phrase("Der Aufzug muss wegen des Schadens sofort geprüft werden.", "Hay que revisar el ascensor de inmediato por la avería.", "Aufzug", "muss geprüft werden expresa una obligación en pasiva.", ["El ascensor debe revisarse de inmediato debido a la avería."]),
      phrase("Die Heizung kann heute noch repariert werden.", "La calefacción todavía se puede reparar hoy.", "Heizung", "kann repariert werden combina können con la pasiva.", ["La calefacción puede arreglarse aún hoy."], ["Heute kann die Heizung noch repariert werden."]),
      phrase("Im Treppenhaus müssen neue Lampen installiert werden.", "Hay que instalar lámparas nuevas en la escalera.", "Lampen", "müssen installiert werden expresa una necesidad en pasiva.", ["Se deben instalar nuevas lámparas en la escalera."]),
      phrase("Die Haustür soll bis Freitag ersetzt werden.", "La puerta principal se sustituirá antes del viernes.", "Haustür", "soll ersetzt werden presenta una medida prevista en pasiva.", ["Está previsto cambiar la puerta principal antes del viernes."]),
      phrase("Die Kosten müssen von der Eigentümergemeinschaft getragen werden.", "La comunidad de propietarios debe asumir los gastos.", "Kosten", "von der Eigentümergemeinschaft nombra el agente en dativo.", ["Los gastos tienen que ser asumidos por la comunidad de propietarios."]),
      phrase("Der Handwerker muss vor Arbeitsbeginn benachrichtigt werden.", "Hay que avisar al técnico antes de que empiece el trabajo.", "Handwerker", "muss benachrichtigt werden forma la pasiva con el modal müssen.", ["El técnico debe ser avisado antes del inicio de los trabajos."]),
    ]),
    lesson("u35-l2", 2, "Obras y permisos", "Habla de autorizaciones y medidas de seguridad.", [
      phrase("Für den Umbau muss zuerst eine Genehmigung beantragt werden.", "Para la reforma, primero hay que solicitar una autorización.", "Umbau", "muss beantragt werden expresa una obligación en pasiva.", ["Antes de reformar, se debe pedir una autorización."]),
      phrase("Die Fenster dürfen während der Bauarbeiten nicht geöffnet werden.", "No se pueden abrir las ventanas durante las obras.", "Fenster", "dürfen nicht geöffnet werden expresa una prohibición en pasiva.", ["Está prohibido abrir las ventanas durante la obra."], ["Während der Bauarbeiten dürfen die Fenster nicht geöffnet werden."]),
      phrase("Der Lärm kann durch bessere Dämmung verringert werden.", "El ruido se puede reducir con un aislamiento mejor.", "Lärm", "kann verringert werden expresa una posibilidad en pasiva.", ["Un mejor aislamiento puede reducir el ruido."]),
      phrase("Der Antrag muss vollständig ausgefüllt werden.", "Hay que rellenar la solicitud por completo.", "Antrag", "muss ausgefüllt werden combina el modal müssen y la pasiva.", ["La solicitud debe cumplimentarse íntegramente."]),
      phrase("Die Sicherheitsregeln müssen von allen Firmen beachtet werden.", "Todas las empresas deben respetar las normas de seguridad.", "Sicherheitsregeln", "von allen Firmen expresa quién debe cumplir las reglas.", ["Las normas de seguridad tienen que ser respetadas por todas las empresas."]),
      phrase("Der Innenhof soll im Frühjahr neu gestaltet werden.", "El patio se acondicionará de nuevo en primavera.", "Innenhof", "soll gestaltet werden presenta un plan en pasiva.", ["Está previsto renovar el patio en primavera."]),
    ]),
    lesson("u35-l3", 3, "Reclamaciones y seguros", "Explica cómo se tramita una incidencia.", [
      phrase("Der Schaden muss noch heute der Versicherung gemeldet werden.", "Hay que comunicar hoy mismo el daño al seguro.", "Schaden", "muss gemeldet werden expresa una obligación en pasiva.", ["El siniestro debe notificarse a la aseguradora hoy mismo."]),
      phrase("Die Rechnung kann online eingereicht werden.", "La factura se puede presentar por internet.", "Rechnung", "kann eingereicht werden presenta una posibilidad en pasiva.", ["Es posible enviar la factura en línea."], ["Online kann die Rechnung eingereicht werden."]),
      phrase("Die Unterlagen sollen bis zum Monatsende geprüft werden.", "Está previsto revisar la documentación antes de que termine el mes.", "Unterlagen", "sollen geprüft werden expresa una revisión prevista en pasiva.", ["La documentación debe revisarse antes de fin de mes."]),
      phrase("Die beschädigte Tür muss fachgerecht ersetzt werden.", "La puerta dañada debe sustituirse de forma profesional.", "Tür", "muss ersetzt werden es una obligación formulada en pasiva.", ["Hay que cambiar la puerta dañada con garantías."]),
      phrase("Der Eigentümer musste über den Wasserschaden informiert werden.", "Hubo que informar al propietario de los daños por agua.", "Eigentümer", "musste informiert werden es pasiva en pasado con müssen.", ["El propietario tuvo que ser informado de la fuga de agua."]),
      phrase("Die Reparaturkosten dürfen erst nach der Prüfung freigegeben werden.", "Los gastos de reparación solo se pueden aprobar después de la revisión.", "Reparaturkosten", "dürfen freigegeben werden expresa cuándo se permite aprobar los gastos.", ["No se deben autorizar los costes de reparación hasta después de revisarlos."]),
    ]),
  ]),
  unit("u36", 36, "Contratos y seguros", "Comprende condiciones, plazos y decisiones administrativas.", [
    lesson("u36-l1", 1, "Alquiler y condiciones", "Usa el genitivo en cláusulas y plazos.", [
      phrase("Wegen des neuen Vertrags ändern sich die Zahlungsfristen.", "Las fechas de pago cambian por el nuevo contrato.", "Vertrags", "wegen rige genitivo: des Vertrags.", ["Debido al nuevo contrato, cambian los plazos de pago."]),
      phrase("Trotz der kurzen Kündigungsfrist fand sie eine neue Wohnung.", "A pesar del breve plazo de preaviso, encontró otra vivienda.", "Kündigungsfrist", "trotz introduce el genitivo femenino der Kündigungsfrist.", ["Pese al poco tiempo de preaviso, encontró una vivienda nueva."], ["Sie fand trotz der kurzen Kündigungsfrist eine neue Wohnung."]),
      phrase("Während des Gesprächs erklärte der Vermieter die Nebenkosten.", "Durante la conversación, el casero explicó los gastos adicionales.", "Gesprächs", "während rige genitivo: des Gesprächs.", ["El propietario explicó los gastos de comunidad durante la conversación."]),
      phrase("Die Höhe der Kaution steht im Mietvertrag.", "El importe de la fianza aparece en el contrato de alquiler.", "Kaution", "der Kaution es genitivo femenino y especifica el importe.", ["El contrato de alquiler indica cuánto asciende la fianza."]),
      phrase("Innerhalb einer Woche muss die Beschwerde eingehen.", "La reclamación debe llegar en el plazo de una semana.", "Beschwerde", "innerhalb rige genitivo: einer Woche.", ["La reclamación tiene que recibirse en una semana."]),
      phrase("Statt eines langen Schreibens schickte er eine E-Mail.", "En vez de una carta larga, envió un correo electrónico.", "Schreibens", "statt introduce el genitivo: eines langen Schreibens.", ["En lugar de una carta extensa, mandó un correo."]),
    ]),
    lesson("u36-l2", 2, "Seguros y daños", "Describe causas y consecuencias con preposiciones de genitivo.", [
      phrase("Aufgrund eines Sturms wurde der Keller überflutet.", "El sótano se inundó debido a una tormenta.", "Sturms", "aufgrund rige genitivo: eines Sturms.", ["A causa de una tormenta, se inundó el sótano."]),
      phrase("Die Dauer des Schutzes hängt vom Tarif ab.", "La duración de la cobertura depende de la tarifa.", "Schutzes", "des Schutzes es genitivo masculino y depende del sustantivo Dauer.", ["El tiempo de cobertura depende de la póliza contratada."]),
      phrase("Trotz des Schadens blieb das Gerät versichert.", "A pesar de los daños, el aparato siguió asegurado.", "Schadens", "trotz rige genitivo: des Schadens.", ["El aparato continuó cubierto por el seguro pese a los daños."]),
      phrase("Außerhalb der Öffnungszeiten erreichen Sie den Notdienst.", "Fuera del horario de apertura, puede contactar con el servicio de urgencias.", "Öffnungszeiten", "außerhalb introduce el genitivo plural der Öffnungszeiten.", ["El servicio de urgencias está disponible fuera del horario habitual."]),
      phrase("Wegen der Selbstbeteiligung zahlt sie einen Teil selbst.", "Por la franquicia, ella paga una parte.", "Selbstbeteiligung", "wegen rige aquí el genitivo femenino der Selbstbeteiligung.", ["Debido a la franquicia, le toca pagar una parte."]),
      phrase("Die Erstattung erfolgt innerhalb eines Monats.", "El reembolso se realizará en el plazo de un mes.", "Erstattung", "innerhalb rige genitivo: eines Monats.", ["El importe se devolverá dentro de un mes."]),
    ]),
    lesson("u36-l3", 3, "Trámites y resoluciones", "Interpreta documentos y argumentos formales.", [
      phrase("Während der Anhörung beantwortete der Zeuge alle Fragen.", "Durante la audiencia, el testigo respondió a todas las preguntas.", "Anhörung", "während introduce el genitivo femenino der Anhörung.", ["El testigo contestó todas las preguntas durante la vista."]),
      phrase("Die Entscheidung des Gerichts wird morgen veröffentlicht.", "La decisión del tribunal se publicará mañana.", "Gerichts", "des Gerichts es genitivo neutro y especifica quién tomó la decisión.", ["Mañana se hará pública la resolución judicial."], ["Morgen wird die Entscheidung des Gerichts veröffentlicht."]),
      phrase("Aufgrund der Beweise wurde das Verfahren eingestellt.", "El procedimiento se archivó por las pruebas presentadas.", "Beweise", "aufgrund rige genitivo: der Beweise.", ["A la vista de las pruebas, se archivó el procedimiento."]),
      phrase("Der Eingang des Antrags wurde schriftlich bestätigt.", "La recepción de la solicitud se confirmó por escrito.", "Antrags", "des Antrags es genitivo y depende del sustantivo Eingang.", ["Se confirmó por escrito que la solicitud había llegado."]),
      phrase("Trotz aller Einwände stimmte der Ausschuss dem Plan zu.", "A pesar de todas las objeciones, el comité aprobó el plan.", "Einwände", "trotz introduce aquí el genitivo plural aller Einwände.", ["El comité dio su visto bueno al plan pese a las objeciones."]),
      phrase("Die Frist des Bescheids endet am kommenden Freitag.", "El plazo indicado en la resolución termina el próximo viernes.", "Bescheids", "des Bescheids es genitivo masculino y precisa el plazo.", ["El plazo de la notificación vence el próximo viernes."]),
    ]),
  ]),
  unit("u37", 37, "Viajes y horarios", "Organiza desplazamientos y relata acontecimientos en orden.", [
    lesson("u37-l1", 1, "Imprevistos en el viaje", "Distingue als, bevor, nachdem y bis.", [
      phrase("Als wir am Flughafen ankamen, war der Schalter bereits geschlossen.", "Cuando llegamos al aeropuerto, el mostrador ya estaba cerrado.", "Flughafen", "als introduce un acontecimiento único y terminado en el pasado.", ["Al llegar al aeropuerto, el mostrador ya había cerrado."]),
      phrase("Bevor der Zug abfuhr, kaufte ich noch eine Fahrkarte.", "Antes de que saliera el tren, compré otro billete.", "Fahrkarte", "bevor introduce la acción anterior a la salida del tren.", ["Compré un billete más antes de que partiera el tren."], ["Ich kaufte noch eine Fahrkarte, bevor der Zug abfuhr."]),
      phrase("Nachdem das Gepäck angekommen war, verließen wir den Flughafen.", "Una vez que llegó el equipaje, salimos del aeropuerto.", "Gepäck", "nachdem introduce la acción que ocurrió antes de salir del aeropuerto.", ["Una vez recibido el equipaje, abandonamos el aeropuerto."]),
      phrase("Wir warteten, bis der Bus eintraf.", "Esperamos hasta que llegó el autobús.", "Bus", "bis introduce el límite temporal de la espera.", ["Nos quedamos esperando hasta la llegada del autobús."]),
      phrase("Während sie auf das Taxi wartete, las sie die Nachricht.", "Mientras esperaba el taxi, leyó el mensaje.", "Taxi", "während expresa dos acciones simultáneas.", ["Leyó el mensaje mientras aguardaba el taxi."]),
      phrase("Seitdem ich in Madrid wohne, fahre ich selten mit dem Auto.", "Desde que vivo en Madrid, voy pocas veces en coche.", "Madrid", "seitdem marca un comienzo pasado que sigue vigente.", ["Desde que resido en Madrid, casi nunca cojo el coche."]),
    ]),
    lesson("u37-l2", 2, "Ferias y citas", "Habla de rutinas y condiciones temporales.", [
      phrase("Wenn die Messe beginnt, betreuen wir den Stand gemeinsam.", "Cuando empieza la feria, atendemos juntos el puesto.", "Messe", "wenn introduce una situación repetida o futura.", ["Al comenzar la feria, nos encargamos juntos del puesto."]),
      phrase("Sobald die Ergebnisse vorliegen, informieren wir die Presse.", "En cuanto tengamos los resultados, informaremos a la prensa.", "Ergebnisse", "sobald expresa que la información se dará justo después.", ["Informaremos a la prensa nada más recibir los resultados."]),
      phrase("Bevor die Sitzung endet, sammeln wir offene Fragen.", "Antes de que termine la reunión, recopilamos las preguntas pendientes.", "Sitzung", "bevor introduce una acción que debe ocurrir antes del final.", ["Recopilamos las dudas pendientes antes de cerrar la reunión."]),
      phrase("Wenn er nach Berlin fährt, besucht er seine Schwester.", "Cuando viaja a Berlín, visita a su hermana.", "Berlin", "wenn describe una circunstancia repetida.", ["Cada vez que va a Berlín, visita a su hermana."]),
      phrase("Die Gäste blieben, bis das Konzert vorbei war.", "Los invitados se quedaron hasta que acabó el concierto.", "Gäste", "bis indica el momento hasta el que permanecieron los invitados.", ["Los invitados no se fueron hasta que terminó el concierto."]),
      phrase("Während der Vortrag lief, notierte sie wichtige Zahlen.", "Mientras se desarrollaba la ponencia, anotó cifras importantes.", "Vortrag", "während presenta la toma de notas como simultánea a la ponencia.", ["Anotó cifras relevantes mientras escuchaba la charla."]),
    ]),
    lesson("u37-l3", 3, "Decisiones en el trabajo", "Ordena conversaciones, plazos y respuestas.", [
      phrase("Nachdem die Bewerberin das Gespräch beendet hatte, wartete sie draußen.", "Después de terminar la entrevista, la candidata esperó fuera.", "Bewerberin", "La entrevista terminó antes de que la candidata esperara fuera.", ["Una vez finalizada la entrevista, la candidata se quedó fuera."]),
      phrase("Als der Chef die Nachricht erhielt, rief er sofort zurück.", "Cuando el jefe recibió el mensaje, devolvió la llamada enseguida.", "Nachricht", "als introduce un hecho único y terminado en el pasado.", ["En cuanto recibió el mensaje, el jefe volvió a llamar."]),
      phrase("Seit wir die neue Software nutzen, sparen wir Zeit.", "Desde que usamos el nuevo programa, ahorramos tiempo.", "Software", "seit presenta un cambio que empezó antes y continúa ahora.", ["Desde que implantamos el nuevo programa, ganamos tiempo."]),
      phrase("Bevor die Leitung entscheidet, hört sie beide Seiten an.", "Antes de decidir, la dirección escucha a las dos partes.", "Leitung", "bevor introduce la acción que precede a la decisión.", ["La dirección escucha a ambas partes antes de tomar una decisión."]),
      phrase("Wenn der Kunde nachfragt, erklären wir den Ablauf erneut.", "Si el cliente pregunta, le explicamos otra vez el proceso.", "Kunde", "wenn introduce una condición para volver a explicar el proceso.", ["Le volvemos a explicar el procedimiento cuando el cliente lo pide."]),
      phrase("Sobald der Vertrag unterschrieben ist, beginnt die Arbeit.", "En cuanto se firme el contrato, empezará el trabajo.", "Vertrag", "sobald expresa que el trabajo comienza inmediatamente después de la firma.", ["El trabajo comenzará nada más firmarse el contrato."]),
    ]),
  ]),
  unit("u38", 38, "Decisiones y arrepentimientos", "Expresa deseos y consecuencias hipotéticas del pasado.", [
    lesson("u38-l1", 1, "Lo que habría sido mejor", "Forma el Konjunktiv II Vergangenheit.", [
      phrase("Ich hätte den Bericht früher abschicken sollen.", "Debería haber enviado el informe antes.", "Bericht", "hätte abschicken sollen expresa una obligación pasada que no se cumplió.", ["Tendría que haber mandado antes el informe."]),
      phrase("Sie hätte gern im Ausland studiert.", "Le habría gustado estudiar en el extranjero.", "Ausland", "hätte studiert forma el Konjunktiv II pasado de studieren.", ["A ella le habría gustado cursar estudios fuera."], ["Im Ausland hätte sie gern studiert."]),
      phrase("Wir hätten die Warnung ernst nehmen müssen.", "Tendríamos que haber tomado en serio la advertencia.", "Warnung", "hätten nehmen müssen es la construcción de doble infinitivo con müssen.", ["Deberíamos haber hecho caso de la advertencia."]),
      phrase("Wenn er früher losgefahren wäre, hätte er den Zug erreicht.", "Si hubiera salido antes, habría llegado a tiempo para coger el tren.", "Zug", "La condición irreal usa wäre losgefahren y el resultado hätte erreicht.", ["De haber salido antes, habría podido coger el tren."]),
      phrase("An deiner Stelle hätte ich anders reagiert.", "En tu lugar, habría reaccionado de otra manera.", "Stelle", "hätte reagiert expresa una reacción hipotética pasada.", ["Yo, en tu lugar, habría actuado de otra forma."]),
      phrase("Ohne den Rat der Ärztin wäre sie nicht gesund geworden.", "Sin el consejo de la médica, no habría recuperado la salud.", "Ärztin", "wäre gesund geworden expresa un resultado pasado que dependía de una condición.", ["De no haber seguido el consejo de la médica, no se habría recuperado."]),
    ]),
    lesson("u38-l2", 2, "Oportunidades perdidas", "Habla de planes y consejos que no se siguieron.", [
      phrase("Er hätte sich vor der Reise besser informieren sollen.", "Debería haberse informado mejor antes del viaje.", "Reise", "hätte informieren sollen expresa una recomendación pasada no seguida.", ["Tendría que haber buscado más información antes de viajar."]),
      phrase("Wir wären lieber am Meer geblieben.", "Habríamos preferido quedarnos junto al mar.", "Meer", "wären geblieben expresa una alternativa hipotética en pasado.", ["Nos habría gustado más quedarnos en la costa."]),
      phrase("Sie hätte den Vertrag vor der Unterschrift lesen müssen.", "Tendría que haber leído el contrato antes de firmarlo.", "Unterschrift", "hätte lesen müssen emplea el doble infinitivo con müssen.", ["Debería haber revisado el contrato antes de la firma."]),
      phrase("Wären die Gäste früher gekommen, hätten sie den Vortrag gehört.", "Si los invitados hubieran llegado antes, habrían escuchado la ponencia.", "Gäste", "La condición y el resultado usan el Konjunktiv II pasado.", ["De haber llegado antes, los invitados habrían oído la ponencia."]),
      phrase("Mit mehr Geduld hättest du den Fehler vermeiden können.", "Con más paciencia, habrías podido evitar el error.", "Geduld", "hättest vermeiden können es la forma pasada del modal können.", ["Si hubieras tenido más paciencia, podrías haber evitado el error."]),
      phrase("Ich wäre fast in den falschen Zug gestiegen.", "Estuve a punto de subirme al tren equivocado.", "Zug", "wäre gestiegen expresa una acción pasada que estuvo a punto de ocurrir.", ["Por poco me subo al tren que no era."]),
    ]),
    lesson("u38-l3", 3, "Resultados alternativos", "Imagina cómo habrían cambiado los resultados.", [
      phrase("Die Firma hätte den Auftrag annehmen können.", "La empresa podría haber aceptado el encargo.", "Auftrag", "hätte annehmen können combina hätte con el doble infinitivo del modal.", ["La empresa habría podido aceptar el proyecto."]),
      phrase("Ohne die Baustelle wäre die Straße rechtzeitig fertig geworden.", "Sin las obras, la carretera habría estado lista a tiempo.", "Baustelle", "wäre fertig geworden expresa un resultado hipotético pasado.", ["De no ser por las obras, la carretera se habría terminado a tiempo."]),
      phrase("Du hättest der Kollegin früher Bescheid sagen sollen.", "Deberías haber avisado antes a la compañera.", "Kollegin", "hättest sagen sollen expresa una recomendación pasada.", ["Tendrías que haber informado antes a tu compañera."]),
      phrase("Wäre der Zug pünktlich abgefahren, hätten wir den Anschluss erreicht.", "Si el tren hubiera salido puntual, habríamos llegado a tiempo al enlace.", "Anschluss", "La inversión wäre … abgefahren introduce una condición irreal pasada.", ["De haber salido a su hora el tren, habríamos enlazado."]),
      phrase("Der Arzt hätte dem Patienten eine Pause empfehlen müssen.", "El médico tendría que haber recomendado una pausa al paciente.", "Patienten", "hätte empfehlen müssen emplea el doble infinitivo con müssen.", ["El médico debería haber aconsejado al paciente que descansara."]),
      phrase("Sie wäre gern früher nach Hause gegangen.", "Le habría gustado volver antes a casa.", "Hause", "wäre gegangen forma el Konjunktiv II pasado de gehen.", ["Ella habría preferido regresar antes a casa."]),
    ]),
  ]),
  unit("u39", 39, "Atención sanitaria", "Comprende instrucciones clínicas y gestiones médicas.", [
    lesson("u39-l1", 1, "En la consulta", "Usa la pasiva con modales para describir la atención.", [
      phrase("Vor der Behandlung muss der Blutdruck gemessen werden.", "Antes del tratamiento, hay que medir la tensión.", "Blutdruck", "muss gemessen werden expresa una obligación en pasiva.", ["La tensión debe medirse antes del tratamiento."]),
      phrase("Die Ergebnisse können am Nachmittag abgeholt werden.", "Los resultados se pueden recoger por la tarde.", "Ergebnisse", "können abgeholt werden expresa una posibilidad en pasiva.", ["Es posible recoger los resultados por la tarde."], ["Am Nachmittag können die Ergebnisse abgeholt werden."]),
      phrase("Bei Fieber sollte ein Arzt verständigt werden.", "En caso de fiebre, se debería avisar a un médico.", "Fieber", "sollte verständigt werden es una recomendación en pasiva.", ["Si aparece fiebre, conviene avisar a un médico."]),
      phrase("Die Patientin muss über die Risiken aufgeklärt werden.", "Hay que informar a la paciente de los riesgos.", "Patientin", "muss aufgeklärt werden expresa una obligación médica en pasiva.", ["La paciente debe recibir información sobre los riesgos."]),
      phrase("Das Rezept kann digital eingelöst werden.", "La receta se puede dispensar en formato digital.", "Rezept", "kann eingelöst werden presenta una posibilidad en pasiva.", ["Es posible usar la receta de forma electrónica."]),
      phrase("Der Termin darf nur im Notfall abgesagt werden.", "La cita solo se puede cancelar en caso de urgencia.", "Notfall", "darf abgesagt werden indica en qué caso está permitido cancelar.", ["Únicamente se permite cancelar la cita por una urgencia."]),
    ]),
    lesson("u39-l2", 2, "Tratamientos y recetas", "Explica cómo se registran y entregan los datos médicos.", [
      phrase("Impfungen müssen in der Akte dokumentiert werden.", "Las vacunas deben constar en el historial.", "Impfungen", "müssen dokumentiert werden formula una obligación en pasiva.", ["Hay que registrar las vacunas en la ficha médica."]),
      phrase("Die Medikamente sollen kühl gelagert werden.", "Los medicamentos deben conservarse en frío.", "Medikamente", "sollen gelagert werden expresa una instrucción en pasiva.", ["Se recomienda guardar los medicamentos en un lugar fresco."]),
      phrase("Der Befund kann direkt an die Praxis gesendet werden.", "El informe se puede enviar directamente a la consulta.", "Befund", "kann gesendet werden presenta una posibilidad en pasiva.", ["Es posible remitir el resultado directamente a la clínica."]),
      phrase("Die Kosten müssen von der Krankenkasse geprüft werden.", "La aseguradora debe revisar los gastos.", "Kosten", "von der Krankenkasse nombra el agente de la pasiva.", ["Los gastos tienen que ser revisados por la mutua."], ["Von der Krankenkasse müssen die Kosten geprüft werden."]),
      phrase("Die Patientendaten dürfen nicht weitergegeben werden.", "No se pueden compartir los datos de los pacientes.", "Patientendaten", "dürfen nicht weitergegeben werden expresa una prohibición.", ["Está prohibido facilitar datos de pacientes a terceros."]),
      phrase("Eine Überweisung muss rechtzeitig ausgestellt werden.", "El volante debe emitirse a tiempo.", "Überweisung", "muss ausgestellt werden expresa una obligación en pasiva.", ["Hay que preparar la derivación con antelación."]),
    ]),
    lesson("u39-l3", 3, "Servicios públicos", "Comprende obligaciones y plazos de una administración.", [
      phrase("Die Bescheinigung muss beim Bürgeramt vorgelegt werden.", "Hay que presentar el certificado en la oficina municipal.", "Bescheinigung", "muss vorgelegt werden expresa un requisito en pasiva.", ["El certificado debe entregarse en la oficina de atención ciudadana."]),
      phrase("Anträge können nach der Prüfung genehmigt werden.", "Las solicitudes se pueden aprobar después de revisarlas.", "Anträge", "können genehmigt werden expresa una posibilidad en pasiva.", ["Una vez revisadas, las solicitudes pueden recibir aprobación."]),
      phrase("Die Gebühren müssen innerhalb der Frist bezahlt werden.", "Las tasas deben pagarse dentro del plazo.", "Gebühren", "müssen bezahlt werden indica una obligación en pasiva.", ["Hay que abonar las tasas antes de que venza el plazo."]),
      phrase("Der Bescheid sollte schriftlich begründet werden.", "La resolución debería justificarse por escrito.", "Bescheid", "sollte begründet werden formula una recomendación en pasiva.", ["Conviene explicar por escrito los motivos de la resolución."]),
      phrase("Die Daten dürfen nur mit Zustimmung verarbeitet werden.", "Los datos solo se pueden tratar con consentimiento.", "Zustimmung", "dürfen verarbeitet werden indica permiso sujeto a una condición.", ["El tratamiento de los datos requiere consentimiento."]),
      phrase("Eine Kopie kann auf Wunsch zugesandt werden.", "Se puede enviar una copia si se solicita.", "Kopie", "kann zugesandt werden expresa una posibilidad en pasiva.", ["La copia está disponible para su envío a petición."]),
    ]),
  ]),
  unit("u40", 40, "Educación y empleo", "Compara opciones y resultados en instituciones y empresas.", [
    lesson("u40-l1", 1, "Investigación y educación", "Conecta ideas con estructuras correlativas.", [
      phrase("Sowohl die Studie als auch die Umfrage bestätigen den Trend.", "Tanto el estudio como la encuesta confirman la tendencia.", "Studie", "sowohl … als auch coordina dos sujetos y lleva el verbo al plural.", ["La encuesta y el estudio corroboran la tendencia."]),
      phrase("Nicht nur die Schulen, sondern auch die Vereine fördern das Projekt.", "No solo los colegios, sino también las asociaciones apoyan el proyecto.", "Vereine", "nicht nur … sondern auch añade un segundo sujeto.", ["Las asociaciones también impulsan el proyecto, además de los colegios."]),
      phrase("Weder die Stadt noch das Land übernimmt die Kosten.", "Ni el ayuntamiento ni el estado asumen los gastos.", "Land", "weder … noch niega las dos opciones y el verbo concuerda con el sujeto más cercano.", ["Ni el municipio ni el estado se hacen cargo de los costes."]),
      phrase("Entweder wird der Antrag genehmigt, oder er wird abgelehnt.", "O se aprueba la solicitud o se rechaza.", "Antrag", "entweder … oder presenta dos resultados posibles.", ["La solicitud será aprobada o bien denegada."]),
      phrase("Das Ergebnis ist zwar eindeutig, aber noch nicht öffentlich.", "El resultado está claro, pero todavía no es público.", "Ergebnis", "zwar … aber contrapone dos aspectos de la misma situación.", ["Aunque el resultado es claro, aún no se ha hecho público."]),
      phrase("Je mehr Daten vorliegen, desto genauer wird die Analyse.", "Cuantos más datos hay, más precisa es el análisis.", "Analyse", "je … desto relaciona el aumento de datos con una mayor precisión.", ["La precisión del análisis aumenta con la cantidad de datos."]),
    ]),
    lesson("u40-l2", 2, "Decisiones de empresa", "Expresa acuerdos, contrastes y alternativas.", [
      phrase("Sowohl die Ärztin als auch der Pfleger arbeiten im Notdienst.", "Tanto la médica como el enfermero trabajan en el servicio de urgencias.", "Pfleger", "sowohl … als auch coordina dos sujetos; el verbo aparece en plural.", ["La médica y el enfermero trabajan en urgencias."]),
      phrase("Nicht nur der Preis, sondern auch die Qualität überzeugte uns.", "No solo el precio, sino también la calidad nos convenció.", "Qualität", "nicht nur … sondern auch añade dos factores relacionados.", ["La calidad también nos convenció, además del precio."]),
      phrase("Weder das Team noch die Leitung fand eine einfache Lösung.", "Ni el equipo ni la dirección encontraron una solución sencilla.", "Leitung", "weder … noch coordina dos sujetos; fand concuerda con el más cercano.", ["Ni la dirección ni el equipo dieron con una solución fácil."]),
      phrase("Die Firma ist zwar klein, aber international tätig.", "La empresa es pequeña, pero opera a escala internacional.", "Firma", "zwar … aber expresa un contraste.", ["Aunque es pequeña, la empresa trabaja a nivel internacional."]),
      phrase("Je länger das Gespräch dauerte, desto klarer wurde der Plan.", "Cuanto más duró la conversación, más claro quedó el plan.", "Gespräch", "je … desto conecta la duración con la claridad del plan.", ["El plan se aclaró a medida que avanzaba la conversación."]),
      phrase("Entweder reisen wir heute ab, oder wir warten bis morgen.", "O salimos hoy o esperamos hasta mañana.", "morgen", "entweder … oder introduce dos posibilidades.", ["Podemos partir hoy o quedarnos hasta mañana."]),
    ]),
    lesson("u40-l3", 3, "Transporte y servicio", "Debate cambios y comparaciones en los viajes.", [
      phrase("Sowohl die Bahn als auch die Fluggesellschaft entschuldigten sich.", "Tanto el ferrocarril como la aerolínea pidieron disculpas.", "Fluggesellschaft", "sowohl … als auch coordina dos sujetos que se disculpan.", ["La compañía ferroviaria y la aerolínea se disculparon."]),
      phrase("Weder der Sturm noch der Nebel verzögerte die Fähre.", "Ni la tormenta ni la niebla retrasaron el ferry.", "Fähre", "weder … noch coordina dos causas; el verbo concuerda con el sujeto más cercano.", ["El ferry no se retrasó ni por la tormenta ni por la niebla."]),
      phrase("Nicht nur die Abfahrt, sondern auch die Ankunft wurde verschoben.", "Se aplazó tanto la salida como la llegada.", "Ankunft", "nicht nur … sondern auch enlaza dos elementos afectados por el aplazamiento.", ["Se retrasaron la salida y también la llegada."]),
      phrase("Je früher wir buchen, desto günstiger wird die Reise.", "Cuanto antes reservemos, más barato saldrá el viaje.", "günstiger", "je … desto relaciona la antelación con un precio más bajo.", ["Reservar con tiempo hace que el viaje cueste menos."]),
      phrase("Das Hotel liegt zwar zentral, aber es ist schlecht isoliert.", "El hotel está céntrico, pero tiene poco aislamiento.", "isoliert", "zwar … aber contrapone la ubicación y el aislamiento.", ["Aunque el hotel está bien situado, está mal aislado."]),
      phrase("Entweder nehmen sie den Nachtzug, oder sie fliegen morgens.", "O cogen el tren nocturno o vuelan por la mañana.", "Nachtzug", "entweder … oder ofrece dos formas alternativas de viajar.", ["Pueden viajar en el tren nocturno o volar por la mañana."]),
    ]),
  ]),
  unit("u41", 41, "Ciencia y formación", "Describe proyectos, estudios y resultados con precisión.", [
    lesson("u41-l1", 1, "En el laboratorio", "Usa oraciones de relativo para precisar información.", [
      phrase("Die Forscherin, die das Projekt leitete, veröffentlichte einen Bericht.", "La investigadora que dirigió el proyecto publicó un informe.", "Forscherin", "die es nominativo femenino y funciona como sujeto de leitete.", ["La investigadora responsable del proyecto publicó un informe."]),
      phrase("Das Labor, in dem die Proben lagern, bleibt geschlossen.", "El laboratorio en el que se conservan las muestras seguirá cerrado.", "Proben", "in dem es dativo y el verbo lagern queda al final de la relativa.", ["El laboratorio donde se guardan las muestras permanece cerrado."], ["Das Labor bleibt geschlossen, in dem die Proben lagern."]),
      phrase("Der Versuch, den wir gestern wiederholt haben, gelang endlich.", "El experimento que repetimos ayer por fin salió bien.", "Versuch", "den es acusativo porque es el objeto de wiederholt haben.", ["Por fin funcionó el experimento que repetimos ayer."]),
      phrase("Die Daten, auf die sich das Team stützt, sind vollständig.", "Los datos en los que se basa el equipo están completos.", "Daten", "auf die acompaña a sich stützen y el verbo conjugado cierra la relativa.", ["El equipo dispone de todos los datos en los que basa su análisis."]),
      phrase("Als die Geräte ausfielen, stoppte das Experiment.", "Cuando fallaron los aparatos, se detuvo el experimento.", "Geräte", "als introduce el momento pasado y único en que se interrumpió el ensayo.", ["El experimento se detuvo cuando dejaron de funcionar los aparatos."]),
      phrase("Nachdem die Analyse abgeschlossen war, teilte sie die Ergebnisse.", "Después de terminar el análisis, comunicó los resultados.", "Analyse", "nachdem introduce el análisis terminado antes de comunicar los resultados.", ["Una vez concluido el análisis, presentó los resultados."]),
    ]),
    lesson("u41-l2", 2, "Cursos especializados", "Relaciona personas, contenidos y plazos.", [
      phrase("Der Kurs, an dem ich teilnehme, beginnt nächste Woche.", "El curso en el que participo empieza la semana que viene.", "Kurs", "an dem es dativo porque teilnehmen rige an más dativo.", ["La semana que viene empieza el curso al que asisto."]),
      phrase("Die Dozentin, deren Artikel oft zitiert wird, hält heute einen Vortrag.", "La profesora cuyo artículo se cita a menudo da hoy una charla.", "Dozentin", "deren es el relativo genitivo que expresa posesión.", ["Hoy da una conferencia la docente cuyo artículo se cita con frecuencia."]),
      phrase("Bevor die Prüfung begann, hatten alle ihre Plätze gefunden.", "Antes de que empezara el examen, todos habían encontrado su sitio.", "Prüfung", "hatten gefunden presenta el hallazgo como anterior al comienzo del examen.", ["Todos estaban sentados antes de que comenzara la prueba."]),
      phrase("Seitdem wir das neue Labor nutzen, arbeiten wir präziser.", "Desde que usamos el nuevo laboratorio, trabajamos con más precisión.", "Labor", "seitdem expresa una situación que comenzó en el pasado y continúa.", ["Nuestro trabajo es más preciso desde que usamos el laboratorio nuevo."]),
      phrase("Die Aufgabe, die der Professor erklärt, ist anspruchsvoll.", "El ejercicio que explica el profesor es exigente.", "Professor", "die es acusativo femenino porque es el objeto de erklärt.", ["El profesor explica un ejercicio que tiene bastante dificultad."]),
      phrase("Sobald das Zertifikat eintrifft, senden wir eine Kopie.", "En cuanto llegue el certificado, enviaremos una copia.", "Zertifikat", "sobald indica que la copia se enviará inmediatamente después.", ["Enviaremos una copia nada más recibir el certificado."]),
    ]),
    lesson("u41-l3", 3, "Becas y proyectos", "Describe candidaturas y resultados académicos.", [
      phrase("Die Studierenden, denen wir geholfen haben, bestanden die Prüfung.", "Los estudiantes a quienes ayudamos aprobaron el examen.", "Studierenden", "denen es dativo plural porque helfen rige dativo.", ["Aprobaron el examen los estudiantes a los que prestamos ayuda."]),
      phrase("Als das Stipendium bewilligt wurde, begann sie mit der Forschung.", "Cuando concedieron la beca, empezó a investigar.", "Stipendium", "als presenta la concesión como un acontecimiento pasado y único.", ["La investigación empezó al aprobarse la beca."]),
      phrase("Der Bericht, auf dessen Ergebnisse die Kommission wartet, erscheint morgen.", "El informe cuyos resultados espera la comisión se publica mañana.", "Kommission", "dessen es genitivo y remite al sustantivo masculino Bericht.", ["Mañana se publicará el informe del que espera resultados la comisión."]),
      phrase("Während die Bewerberinnen warteten, prüfte der Ausschuss ihre Unterlagen.", "Mientras esperaban las candidatas, el comité revisó sus documentos.", "Bewerberinnen", "während expresa que la revisión ocurrió al mismo tiempo que la espera.", ["El comité examinó la documentación mientras las candidatas aguardaban."]),
      phrase("Nachdem sie den Kurs beendet hatte, bewarb sie sich um ein Stipendium.", "Después de terminar el curso, solicitó una beca.", "Stipendium", "hatte beendet es Plusquamperfekt y precede a la solicitud.", ["Una vez acabado el curso, presentó una solicitud para una beca."]),
      phrase("Die Schule, die neue Fachkräfte ausbildet, liegt am Stadtrand.", "La escuela que forma a nuevos profesionales está en las afueras.", "Fachkräfte", "die es nominativo plural y funciona como sujeto de ausbildet.", ["El centro que prepara a nuevos especialistas está a las afueras."]),
    ]),
  ]),
  unit("u42", 42, "Cultura y sociedad", "Habla de eventos, iniciativas y debates públicos.", [
    lesson("u42-l1", 1, "Exposiciones y festivales", "Combina conectores temporales y oraciones de relativo.", [
      phrase("Als die Ausstellung eröffnete, standen viele Besucher vor dem Eingang.", "Cuando inauguraron la exposición, había muchos visitantes ante la entrada.", "Ausstellung", "als introduce un acontecimiento cultural único en el pasado.", ["Muchos visitantes esperaban en la entrada cuando abrió la exposición."]),
      phrase("Nachdem die Schauspielerin den Preis erhalten hatte, dankte sie dem Team.", "Después de recibir el premio, la actriz dio las gracias al equipo.", "Schauspielerin", "hatte erhalten expresa una acción anterior al agradecimiento.", ["La actriz agradeció al equipo tras recibir el galardón."]),
      phrase("Bevor das Festival endet, findet noch ein Konzert statt.", "Antes de que termine el festival, se celebra otro concierto.", "Festival", "bevor introduce el evento que ocurrirá antes del final.", ["Aún habrá un concierto antes de que acabe el festival."]),
      phrase("Die Moderatorin, die das Gespräch leitete, stellte kritische Fragen.", "La presentadora que dirigió la conversación hizo preguntas críticas.", "Moderatorin", "die es nominativo femenino y funciona como sujeto de leitete.", ["La periodista que moderó el debate planteó preguntas incisivas."]),
      phrase("Sowohl die Autorin als auch der Übersetzer nahmen an der Lesung teil.", "Tanto la autora como el traductor participaron en la lectura.", "Übersetzer", "sowohl … als auch coordina dos sujetos en la acción.", ["La autora y el traductor asistieron a la lectura."]),
      phrase("Seitdem das Theater renoviert wurde, zieht es mehr Publikum an.", "Desde que se renovó, el teatro atrae a más público.", "Theater", "seitdem presenta una situación que empezó con la renovación y continúa.", ["El teatro recibe más espectadores desde que lo reformaron."]),
    ]),
    lesson("u42-l2", 2, "Cine, música y prensa", "Describe artistas y críticas en medios culturales.", [
      phrase("Der Film, über den gestern alle sprachen, gewann einen Preis.", "La película de la que todo el mundo habló ayer ganó un premio.", "Film", "über den acompaña a sprechen über y el verbo va al final de la relativa.", ["La película que ayer comentó todo el mundo se llevó un galardón."]),
      phrase("Die Sängerin, deren Album erschienen ist, geht bald auf Tournee.", "La cantante cuyo álbum acaba de salir se irá pronto de gira.", "Sängerin", "deren expresa posesión y remite al sustantivo femenino Sängerin.", ["La artista, cuyo disco acaba de publicarse, pronto saldrá de gira."]),
      phrase("Wenn die Karten ausverkauft sind, übertragen wir die Aufführung online.", "Si se agotan las entradas, retransmitiremos la función por internet.", "Karten", "wenn introduce la condición para emitir la función en línea.", ["Emitiremos la actuación en línea si ya no quedan entradas."]),
      phrase("Nicht nur Zuschauer, sondern auch Kritiker lobten das Stück.", "No solo los espectadores, sino también los críticos elogiaron la obra.", "Kritiker", "nicht nur … sondern auch añade dos grupos que valoraron la obra.", ["La crítica también elogió la obra, al igual que el público."]),
      phrase("Während die Jury beriet, warteten die Nominierten draußen.", "Mientras deliberaba el jurado, los nominados esperaban fuera.", "Jury", "während expresa que la espera y la deliberación fueron simultáneas.", ["Los nominados aguardaron fuera mientras el jurado deliberaba."]),
      phrase("Der Autor, dem die Stadt den Preis verlieh, hielt eine Rede.", "El autor a quien la ciudad concedió el premio pronunció un discurso.", "Autor", "dem es dativo porque es el destinatario de verlieh.", ["El escritor que recibió el premio municipal pronunció unas palabras."]),
    ]),
    lesson("u42-l3", 3, "Participación ciudadana", "Relata debates y decisiones colectivas.", [
      phrase("Die Initiative, die sich für Jugendliche einsetzt, sucht Freiwillige.", "La iniciativa que defiende a los jóvenes busca voluntarios.", "Initiative", "die es nominativo femenino y funciona como sujeto de sich einsetzt.", ["La asociación que trabaja por la juventud busca personas voluntarias."]),
      phrase("Bevor die Debatte begann, hatte der Ausschuss den Vorschlag geprüft.", "Antes de que empezara el debate, el comité había revisado la propuesta.", "Debatte", "hatte geprüft presenta la revisión como anterior al debate.", ["El comité ya había estudiado la propuesta cuando comenzó el debate."]),
      phrase("Weder die Bürger noch die Verwaltung kannten den genauen Zeitplan.", "Ni la ciudadanía ni la administración conocían el calendario exacto.", "Verwaltung", "weder … noch coordina los dos grupos que desconocían el calendario.", ["La administración y los vecinos desconocían el calendario previsto."]),
      phrase("Sobald die Ergebnisse vorliegen, veröffentlicht die Stadt einen Bericht.", "En cuanto estén los resultados, el ayuntamiento publicará un informe.", "Ergebnisse", "sobald indica que el informe se publicará inmediatamente después.", ["La ciudad hará público un informe nada más recibir los resultados."]),
      phrase("Die Entscheidung, die nach langer Beratung fiel, überraschte viele.", "La decisión que se tomó tras un largo debate sorprendió a muchos.", "Entscheidung", "die es nominativo femenino y se refiere al sujeto de fiel.", ["A muchos les sorprendió la decisión tomada después de deliberar durante horas."]),
      phrase("Je mehr Menschen teilnahmen, desto lebhafter wurde die Diskussion.", "Cuanta más gente participó, más animado se volvió el debate.", "Diskussion", "je … desto relaciona la participación con la intensidad del debate.", ["El debate ganó viveza a medida que aumentaba la participación."]),
    ]),
  ]),
];
