import type { CefrLevel } from "../../src/lib/levels";

type VocabularyDraft = {
  cefrLevel?: CefrLevel;
  german: string;
  spanish: string;
  article?: "der" | "die" | "das";
  plural?: string;
  exampleDe?: string;
  exampleEs?: string;
};

const topics: Array<{ topic: string; items: VocabularyDraft[] }> = [
  {
    topic: "saludos",
    items: [
      { german: "Name", article: "der", plural: "Namen", spanish: "nombre" },
      { german: "Gruß", article: "der", plural: "Grüße", spanish: "saludo", exampleDe: "Viele Grüße aus Berlin.", exampleEs: "Muchos saludos desde Berlín." },
      { german: "Frage", article: "die", plural: "Fragen", spanish: "pregunta", exampleDe: "Die Frage ist einfach.", exampleEs: "La pregunta es fácil." },
      { german: "Antwort", article: "die", plural: "Antworten", spanish: "respuesta" },
      { german: "Morgen", article: "der", plural: "Morgen", spanish: "mañana", exampleDe: "Der Morgen ist ruhig.", exampleEs: "La mañana está tranquila." },
      { german: "Tag", article: "der", plural: "Tage", spanish: "día", exampleDe: "Der Tag ist schön.", exampleEs: "El día es bonito." },
      { german: "Abend", article: "der", plural: "Abende", spanish: "tarde; noche" },
      { german: "Nacht", article: "die", plural: "Nächte", spanish: "noche" },
      { german: "Freund", article: "der", plural: "Freunde", spanish: "amigo", exampleDe: "Mein Freund heißt Pablo.", exampleEs: "Mi amigo se llama Pablo." },
      { german: "Freundin", article: "die", plural: "Freundinnen", spanish: "amiga" },
      { german: "Gespräch", article: "das", plural: "Gespräche", spanish: "conversación" },
      { german: "Sprache", article: "die", plural: "Sprachen", spanish: "idioma" },
      { german: "Wort", article: "das", plural: "Wörter", spanish: "palabra", exampleDe: "Das Wort ist neu.", exampleEs: "La palabra es nueva." },
      { german: "Satz", article: "der", plural: "Sätze", spanish: "frase" },
      { german: "Beispiel", article: "das", plural: "Beispiele", spanish: "ejemplo" },
      { german: "Person", article: "die", plural: "Personen", spanish: "persona" },
      { german: "Herr", article: "der", plural: "Herren", spanish: "señor" },
      { german: "Frau", article: "die", plural: "Frauen", spanish: "mujer; señora", exampleDe: "Die Frau kommt aus Spanien.", exampleEs: "La mujer es de España." },
      { german: "Land", article: "das", plural: "Länder", spanish: "país" },
      { german: "Stadt", article: "die", plural: "Städte", spanish: "ciudad" },
      { german: "Abschied", article: "der", plural: "Abschiede", spanish: "despedida" },
    ],
  },
  {
    topic: "numeros",
    items: [
      { german: "Zahl", article: "die", plural: "Zahlen", spanish: "número", exampleDe: "Die Zahl ist sieben.", exampleEs: "El número es siete." },
      { german: "Nummer", article: "die", plural: "Nummern", spanish: "número; cifra" },
      { german: "Alter", article: "das", plural: "—", spanish: "edad" },
      { german: "Jahr", article: "das", plural: "Jahre", spanish: "año", exampleDe: "Das Jahr hat zwölf Monate.", exampleEs: "El año tiene doce meses." },
      { german: "Woche", article: "die", plural: "Wochen", spanish: "semana" },
      { german: "Monat", article: "der", plural: "Monate", spanish: "mes" },
      { german: "Stunde", article: "die", plural: "Stunden", spanish: "hora" },
      { german: "Minute", article: "die", plural: "Minuten", spanish: "minuto" },
      { german: "Sekunde", article: "die", plural: "Sekunden", spanish: "segundo" },
      { german: "Geburtstag", article: "der", plural: "Geburtstage", spanish: "cumpleaños" },
      { german: "Euro", article: "der", plural: "Euro", spanish: "euro" },
      { german: "Cent", article: "der", plural: "Cent", spanish: "céntimo" },
      { german: "Preis", article: "der", plural: "Preise", spanish: "precio", exampleDe: "Der Preis ist niedrig.", exampleEs: "El precio es bajo." },
      { german: "Rechnung", article: "die", plural: "Rechnungen", spanish: "cuenta; factura" },
      { german: "Menge", article: "die", plural: "Mengen", spanish: "cantidad" },
      { german: "Hälfte", article: "die", plural: "Hälften", spanish: "mitad" },
      { german: "Paar", article: "das", plural: "Paare", spanish: "par" },
      { german: "Summe", article: "die", plural: "Summen", spanish: "suma" },
      { german: "Zeit", article: "die", plural: "Zeiten", spanish: "tiempo" },
      { german: "Million", article: "die", plural: "Millionen", spanish: "millón" },
      { german: "Ziffer", article: "die", plural: "Ziffern", spanish: "dígito" },
    ],
  },
  {
    topic: "familia",
    items: [
      { german: "Mutter", article: "die", plural: "Mütter", spanish: "madre", exampleDe: "Meine Mutter kocht gern.", exampleEs: "A mi madre le gusta cocinar." },
      { german: "Vater", article: "der", plural: "Väter", spanish: "padre" },
      { german: "Eltern", article: "die", plural: "Eltern", spanish: "padres" },
      { german: "Bruder", article: "der", plural: "Brüder", spanish: "hermano", exampleDe: "Mein Bruder wohnt in Madrid.", exampleEs: "Mi hermano vive en Madrid." },
      { german: "Schwester", article: "die", plural: "Schwestern", spanish: "hermana" },
      { german: "Sohn", article: "der", plural: "Söhne", spanish: "hijo" },
      { german: "Tochter", article: "die", plural: "Töchter", spanish: "hija" },
      { german: "Kind", article: "das", plural: "Kinder", spanish: "niño; hijo", exampleDe: "Das Kind spielt im Garten.", exampleEs: "El niño juega en el jardín." },
      { german: "Familie", article: "die", plural: "Familien", spanish: "familia" },
      { german: "Großmutter", article: "die", plural: "Großmütter", spanish: "abuela" },
      { german: "Großvater", article: "der", plural: "Großväter", spanish: "abuelo" },
      { german: "Großeltern", article: "die", plural: "Großeltern", spanish: "abuelos" },
      { german: "Onkel", article: "der", plural: "Onkel", spanish: "tío" },
      { german: "Tante", article: "die", plural: "Tanten", spanish: "tía" },
      { german: "Cousin", article: "der", plural: "Cousins", spanish: "primo" },
      { german: "Cousine", article: "die", plural: "Cousinen", spanish: "prima" },
      { german: "Mann", article: "der", plural: "Männer", spanish: "hombre; marido" },
      { german: "Frau", article: "die", plural: "Frauen", spanish: "mujer; esposa" },
      { german: "Partner", article: "der", plural: "Partner", spanish: "pareja" },
      { german: "Partnerin", article: "die", plural: "Partnerinnen", spanish: "pareja" },
      { german: "Geschwister", article: "das", plural: "Geschwister", spanish: "hermano o hermana" },
    ],
  },
  {
    topic: "comida",
    items: [
      { german: "Essen", article: "das", plural: "—", spanish: "comida" },
      { german: "Apfel", article: "der", plural: "Äpfel", spanish: "manzana", exampleDe: "Der Apfel ist rot.", exampleEs: "La manzana es roja." },
      { german: "Banane", article: "die", plural: "Bananen", spanish: "plátano; banana" },
      { german: "Brot", article: "das", plural: "Brote", spanish: "pan", exampleDe: "Das Brot ist frisch.", exampleEs: "El pan está fresco." },
      { german: "Käse", article: "der", plural: "Käse", spanish: "queso" },
      { german: "Milch", article: "die", plural: "—", spanish: "leche", exampleDe: "Die Milch ist kalt.", exampleEs: "La leche está fría." },
      { german: "Wasser", article: "das", plural: "—", spanish: "agua" },
      { german: "Kaffee", article: "der", plural: "Kaffees", spanish: "café" },
      { german: "Tee", article: "der", plural: "Tees", spanish: "té" },
      { german: "Ei", article: "das", plural: "Eier", spanish: "huevo" },
      { german: "Fleisch", article: "das", plural: "—", spanish: "carne" },
      { german: "Fisch", article: "der", plural: "Fische", spanish: "pescado; pez" },
      { german: "Kartoffel", article: "die", plural: "Kartoffeln", spanish: "patata" },
      { german: "Tomate", article: "die", plural: "Tomaten", spanish: "tomate" },
      { german: "Suppe", article: "die", plural: "Suppen", spanish: "sopa" },
      { german: "Salat", article: "der", plural: "Salate", spanish: "ensalada" },
      { german: "Zucker", article: "der", plural: "—", spanish: "azúcar" },
      { german: "Salz", article: "das", plural: "—", spanish: "sal" },
      { german: "Butter", article: "die", plural: "—", spanish: "mantequilla" },
      { german: "Orange", article: "die", plural: "Orangen", spanish: "naranja" },
      { german: "Saft", article: "der", plural: "Säfte", spanish: "zumo", exampleDe: "Der Saft ist frisch.", exampleEs: "El zumo está fresco." },
      { german: "Erdbeere", article: "die", plural: "Erdbeeren", spanish: "fresa" },
    ],
  },
  {
    topic: "casa",
    items: [
      { german: "Haus", article: "das", plural: "Häuser", spanish: "casa", exampleDe: "Das Haus ist groß.", exampleEs: "La casa es grande." },
      { german: "Wohnung", article: "die", plural: "Wohnungen", spanish: "piso; apartamento", exampleDe: "Die Wohnung hat zwei Zimmer.", exampleEs: "El piso tiene dos habitaciones." },
      { german: "Zimmer", article: "das", plural: "Zimmer", spanish: "habitación" },
      { german: "Küche", article: "die", plural: "Küchen", spanish: "cocina", exampleDe: "Die Küche ist hell.", exampleEs: "La cocina es luminosa." },
      { german: "Bad", article: "das", plural: "Bäder", spanish: "baño" },
      { german: "Schlafzimmer", article: "das", plural: "Schlafzimmer", spanish: "dormitorio" },
      { german: "Wohnzimmer", article: "das", plural: "Wohnzimmer", spanish: "salón" },
      { german: "Bett", article: "das", plural: "Betten", spanish: "cama", exampleDe: "Das Bett ist bequem.", exampleEs: "La cama es cómoda." },
      { german: "Tisch", article: "der", plural: "Tische", spanish: "mesa", exampleDe: "Der Tisch steht im Zimmer.", exampleEs: "La mesa está en la habitación." },
      { german: "Stuhl", article: "der", plural: "Stühle", spanish: "silla" },
      { german: "Tür", article: "die", plural: "Türen", spanish: "puerta" },
      { german: "Fenster", article: "das", plural: "Fenster", spanish: "ventana", exampleDe: "Das Fenster ist offen.", exampleEs: "La ventana está abierta." },
      { german: "Lampe", article: "die", plural: "Lampen", spanish: "lámpara" },
      { german: "Schrank", article: "der", plural: "Schränke", spanish: "armario" },
      { german: "Sofa", article: "das", plural: "Sofas", spanish: "sofá" },
      { german: "Schlüssel", article: "der", plural: "Schlüssel", spanish: "llave" },
      { german: "Wand", article: "die", plural: "Wände", spanish: "pared" },
      { german: "Boden", article: "der", plural: "Böden", spanish: "suelo" },
      { german: "Teppich", article: "der", plural: "Teppiche", spanish: "alfombra" },
      { german: "Treppe", article: "die", plural: "Treppen", spanish: "escalera" },
      { german: "Garten", article: "der", plural: "Gärten", spanish: "jardín" },
    ],
  },
  {
    topic: "ciudad",
    items: [
      { german: "Stadt", article: "die", plural: "Städte", spanish: "ciudad" },
      { german: "Straße", article: "die", plural: "Straßen", spanish: "calle", exampleDe: "Die Straße ist lang.", exampleEs: "La calle es larga." },
      { german: "Bahnhof", article: "der", plural: "Bahnhöfe", spanish: "estación de tren", exampleDe: "Der Bahnhof ist hier.", exampleEs: "La estación está aquí." },
      { german: "Bus", article: "der", plural: "Busse", spanish: "autobús", exampleDe: "Der Bus kommt gleich.", exampleEs: "El autobús llega enseguida." },
      { german: "Zug", article: "der", plural: "Züge", spanish: "tren" },
      { german: "Auto", article: "das", plural: "Autos", spanish: "coche" },
      { german: "Fahrrad", article: "das", plural: "Fahrräder", spanish: "bicicleta", exampleDe: "Das Fahrrad steht draußen.", exampleEs: "La bicicleta está fuera." },
      { german: "Haltestelle", article: "die", plural: "Haltestellen", spanish: "parada" },
      { german: "U-Bahn", article: "die", plural: "U-Bahnen", spanish: "metro" },
      { german: "S-Bahn", article: "die", plural: "S-Bahnen", spanish: "tren de cercanías" },
      { german: "Flughafen", article: "der", plural: "Flughäfen", spanish: "aeropuerto" },
      { german: "Ticket", article: "das", plural: "Tickets", spanish: "billete" },
      { german: "Karte", article: "die", plural: "Karten", spanish: "mapa; tarjeta" },
      { german: "Schule", article: "die", plural: "Schulen", spanish: "escuela", exampleDe: "Die Schule ist in der Stadt.", exampleEs: "La escuela está en la ciudad." },
      { german: "Universität", article: "die", plural: "Universitäten", spanish: "universidad" },
      { german: "Geschäft", article: "das", plural: "Geschäfte", spanish: "tienda" },
      { german: "Supermarkt", article: "der", plural: "Supermärkte", spanish: "supermercado" },
      { german: "Apotheke", article: "die", plural: "Apotheken", spanish: "farmacia", exampleDe: "Die Apotheke ist geöffnet.", exampleEs: "La farmacia está abierta." },
      { german: "Krankenhaus", article: "das", plural: "Krankenhäuser", spanish: "hospital" },
      { german: "Brücke", article: "die", plural: "Brücken", spanish: "puente" },
      { german: "Park", article: "der", plural: "Parks", spanish: "parque" },
    ],
  },
  {
    topic: "tiempo",
    items: [
      { german: "Uhr", article: "die", plural: "Uhren", spanish: "reloj; hora", exampleDe: "Es ist sieben Uhr.", exampleEs: "Son las siete." },
      { german: "Wecker", article: "der", plural: "Wecker", spanish: "despertador" },
      { german: "Vormittag", article: "der", plural: "Vormittage", spanish: "mañana (antes del mediodía)" },
      { german: "Mittag", article: "der", plural: "Mittage", spanish: "mediodía" },
      { german: "Nachmittag", article: "der", plural: "Nachmittage", spanish: "tarde" },
      { german: "Morgen", article: "der", plural: "Morgen", spanish: "mañana" },
      { german: "Abend", article: "der", plural: "Abende", spanish: "tarde; noche" },
      { german: "Nacht", article: "die", plural: "Nächte", spanish: "noche" },
      { german: "Termin", article: "der", plural: "Termine", spanish: "cita" },
      { german: "Arbeit", article: "die", plural: "Arbeiten", spanish: "trabajo" },
      { german: "Beruf", article: "der", plural: "Berufe", spanish: "profesión" },
      { german: "Pause", article: "die", plural: "Pausen", spanish: "pausa", exampleDe: "Die Pause ist kurz.", exampleEs: "La pausa es corta." },
      { german: "Alltag", article: "der", plural: "Alltage", spanish: "vida cotidiana" },
      { german: "Frühstück", article: "das", plural: "Frühstücke", spanish: "desayuno", exampleDe: "Das Frühstück ist fertig.", exampleEs: "El desayuno está listo." },
      { german: "Mittagessen", article: "das", plural: "Mittagessen", spanish: "comida; almuerzo" },
      { german: "Abendessen", article: "das", plural: "Abendessen", spanish: "cena" },
      { german: "Schlaf", article: "der", plural: "—", spanish: "sueño" },
      { german: "Sport", article: "der", plural: "—", spanish: "deporte" },
      { german: "Kalender", article: "der", plural: "Kalender", spanish: "calendario" },
      { german: "Woche", article: "die", plural: "Wochen", spanish: "semana" },
      { german: "Wochenende", article: "das", plural: "Wochenenden", spanish: "fin de semana", exampleDe: "Am Wochenende haben wir frei.", exampleEs: "El fin de semana tenemos libre." },
    ],
  },
  {
    topic: "ropa",
    items: [
      { german: "Kleidung", article: "die", plural: "—", spanish: "ropa" },
      { german: "Hemd", article: "das", plural: "Hemden", spanish: "camisa", exampleDe: "Das Hemd ist blau.", exampleEs: "La camisa es azul." },
      { german: "Bluse", article: "die", plural: "Blusen", spanish: "blusa", exampleDe: "Die Bluse ist schön.", exampleEs: "La blusa es bonita." },
      { german: "Hose", article: "die", plural: "Hosen", spanish: "pantalón", exampleDe: "Die Hose ist neu.", exampleEs: "El pantalón es nuevo." },
      { german: "Kleid", article: "das", plural: "Kleider", spanish: "vestido" },
      { german: "Pullover", article: "der", plural: "Pullover", spanish: "jersey" },
      { german: "Jacke", article: "die", plural: "Jacken", spanish: "chaqueta" },
      { german: "Mantel", article: "der", plural: "Mäntel", spanish: "abrigo", exampleDe: "Der Mantel ist warm.", exampleEs: "El abrigo es abrigado." },
      { german: "Schuh", article: "der", plural: "Schuhe", spanish: "zapato", exampleDe: "Die Schuhe sind bequem.", exampleEs: "Los zapatos son cómodos." },
      { german: "Socke", article: "die", plural: "Socken", spanish: "calcetín" },
      { german: "Rock", article: "der", plural: "Röcke", spanish: "falda" },
      { german: "Mütze", article: "die", plural: "Mützen", spanish: "gorro" },
      { german: "Hut", article: "der", plural: "Hüte", spanish: "sombrero" },
      { german: "Tasche", article: "die", plural: "Taschen", spanish: "bolso; bolsa" },
      { german: "Größe", article: "die", plural: "Größen", spanish: "talla; tamaño" },
      { german: "Farbe", article: "die", plural: "Farben", spanish: "color" },
      { german: "Preis", article: "der", plural: "Preise", spanish: "precio" },
      { german: "Geld", article: "das", plural: "—", spanish: "dinero" },
      { german: "Kasse", article: "die", plural: "Kassen", spanish: "caja" },
      { german: "Geschäft", article: "das", plural: "Geschäfte", spanish: "tienda" },
      { german: "Umkleidekabine", article: "die", plural: "Umkleidekabinen", spanish: "probador" },
    ],
  },
  {
    topic: "trabajo",
    items: [
      { german: "Arbeit", article: "die", plural: "Arbeiten", spanish: "trabajo", exampleDe: "Die Arbeit beginnt um neun Uhr.", exampleEs: "El trabajo empieza a las nueve." },
      { german: "Arbeitsplatz", article: "der", plural: "Arbeitsplätze", spanish: "puesto de trabajo" },
      { german: "Büro", article: "das", plural: "Büros", spanish: "oficina", exampleDe: "Das Büro ist hell.", exampleEs: "La oficina es luminosa." },
      { german: "Kollege", article: "der", plural: "Kollegen", spanish: "compañero de trabajo" },
      { german: "Kollegin", article: "die", plural: "Kolleginnen", spanish: "compañera de trabajo" },
      { german: "Chef", article: "der", plural: "Chefs", spanish: "jefe" },
      { german: "Chefin", article: "die", plural: "Chefinnen", spanish: "jefa" },
      { german: "Lehrer", article: "der", plural: "Lehrer", spanish: "profesor" },
      { german: "Lehrerin", article: "die", plural: "Lehrerinnen", spanish: "profesora", exampleDe: "Die Lehrerin erklärt die Aufgabe.", exampleEs: "La profesora explica el ejercicio." },
      { german: "Student", article: "der", plural: "Studenten", spanish: "estudiante" },
      { german: "Studentin", article: "die", plural: "Studentinnen", spanish: "estudiante" },
      { german: "Schule", article: "die", plural: "Schulen", spanish: "escuela" },
      { german: "Universität", article: "die", plural: "Universitäten", spanish: "universidad" },
      { german: "Unterricht", article: "der", plural: "—", spanish: "clase; enseñanza" },
      { german: "Buch", article: "das", plural: "Bücher", spanish: "libro", exampleDe: "Das Buch liegt auf dem Tisch.", exampleEs: "El libro está sobre la mesa." },
      { german: "Stift", article: "der", plural: "Stifte", spanish: "bolígrafo" },
      { german: "Heft", article: "das", plural: "Hefte", spanish: "cuaderno" },
      { german: "Aufgabe", article: "die", plural: "Aufgaben", spanish: "tarea; ejercicio" },
      { german: "Prüfung", article: "die", plural: "Prüfungen", spanish: "examen" },
      { german: "Sprache", article: "die", plural: "Sprachen", spanish: "idioma" },
      { german: "E-Mail", article: "die", plural: "E-Mails", spanish: "correo electrónico" },
      { german: "Computer", article: "der", plural: "Computer", spanish: "ordenador" },
      { german: "Kurs", article: "der", plural: "Kurse", spanish: "curso", exampleDe: "Der Kurs beginnt um neun Uhr.", exampleEs: "El curso empieza a las nueve." },
    ],
  },
  {
    topic: "ocio",
    items: [
      { german: "Hobby", article: "das", plural: "Hobbys", spanish: "afición", exampleDe: "Mein Hobby macht Spaß.", exampleEs: "Mi afición es divertida." },
      { german: "Musik", article: "die", plural: "—", spanish: "música", exampleDe: "Die Musik ist schön.", exampleEs: "La música es bonita." },
      { german: "Sport", article: "der", plural: "Sportarten", spanish: "deporte" },
      { german: "Fußballspiel", article: "das", plural: "Fußballspiele", spanish: "partido de fútbol" },
      { german: "Ball", article: "der", plural: "Bälle", spanish: "pelota" },
      { german: "Kino", article: "das", plural: "Kinos", spanish: "cine" },
      { german: "Film", article: "der", plural: "Filme", spanish: "película", exampleDe: "Der Film beginnt um acht Uhr.", exampleEs: "La película empieza a las ocho." },
      { german: "Buch", article: "das", plural: "Bücher", spanish: "libro" },
      { german: "Zeitung", article: "die", plural: "Zeitungen", spanish: "periódico" },
      { german: "Lied", article: "das", plural: "Lieder", spanish: "canción" },
      { german: "Instrument", article: "das", plural: "Instrumente", spanish: "instrumento" },
      { german: "Gitarre", article: "die", plural: "Gitarren", spanish: "guitarra" },
      { german: "Konzert", article: "das", plural: "Konzerte", spanish: "concierto" },
      { german: "Freund", article: "der", plural: "Freunde", spanish: "amigo" },
      { german: "Freundin", article: "die", plural: "Freundinnen", spanish: "amiga" },
      { german: "Park", article: "der", plural: "Parks", spanish: "parque" },
      { german: "Wochenende", article: "das", plural: "Wochenenden", spanish: "fin de semana" },
      { german: "Reise", article: "die", plural: "Reisen", spanish: "viaje", exampleDe: "Die Reise ist sehr schön.", exampleEs: "El viaje es muy bonito." },
      { german: "Urlaub", article: "der", plural: "Urlaube", spanish: "vacaciones" },
      { german: "Schwimmbad", article: "das", plural: "Schwimmbäder", spanish: "piscina" },
      { german: "Foto", article: "das", plural: "Fotos", spanish: "foto" },
      { german: "Spiel", article: "das", plural: "Spiele", spanish: "juego" },
    ],
  },
];

const verbDraft = (
  cefrLevel: CefrLevel,
  german: string,
  spanish: string,
  exampleDe: string,
  exampleEs: string,
): VocabularyDraft => ({ cefrLevel, german, spanish, exampleDe, exampleEs });

const nounDraft = (
  cefrLevel: CefrLevel,
  german: string,
  article: "der" | "die" | "das",
  plural: string,
  spanish: string,
): VocabularyDraft => ({ cefrLevel, german, article, plural, spanish });

const connectorDraft = (
  cefrLevel: CefrLevel,
  german: string,
  spanish: string,
  exampleDe: string,
  exampleEs: string,
): VocabularyDraft => ({ cefrLevel, german, spanish, exampleDe, exampleEs });

const verbItems: VocabularyDraft[] = [
  verbDraft("A1", "sein", "ser; estar", "Ich bin heute müde.", "Hoy estoy cansado."),
  verbDraft("A1", "haben", "tener", "Wir haben einen Hund.", "Tenemos un perro."),
  verbDraft("A1", "gehen", "ir", "Ich gehe zu Fuß zur Schule.", "Voy a la escuela a pie."),
  verbDraft("A1", "kommen", "venir", "Sie kommt aus Spanien.", "Ella viene de España."),
  verbDraft("A1", "wohnen", "vivir; residir", "Ich wohne in Berlin.", "Vivo en Berlín."),
  verbDraft("A1", "lernen", "aprender", "Wir lernen jeden Tag Deutsch.", "Aprendemos alemán cada día."),
  verbDraft("A1", "arbeiten", "trabajar", "Mein Vater arbeitet im Büro.", "Mi padre trabaja en la oficina."),
  verbDraft("A1", "spielen", "jugar", "Die Kinder spielen im Park.", "Los niños juegan en el parque."),
  verbDraft("A1", "machen", "hacer", "Ich mache meine Hausaufgaben.", "Hago mis deberes."),
  verbDraft("A1", "kaufen", "comprar", "Sie kauft frisches Brot.", "Ella compra pan fresco."),
  verbDraft("A1", "trinken", "beber", "Er trinkt morgens Kaffee.", "Él bebe café por la mañana."),
  verbDraft("A1", "essen", "comer", "Wir essen heute zusammen.", "Hoy comemos juntos."),
  verbDraft("A1", "lesen", "leer", "Ich lese ein interessantes Buch.", "Leo un libro interesante."),
  verbDraft("A1", "schreiben", "escribir", "Sie schreibt eine E-Mail.", "Ella escribe un correo electrónico."),
  verbDraft("A1", "sprechen", "hablar", "Wir sprechen Spanisch.", "Hablamos español."),
  verbDraft("A1", "fahren", "ir; conducir", "Der Bus fährt zum Bahnhof.", "El autobús va a la estación."),
  verbDraft("A1", "schlafen", "dormir", "Das Kind schläft schon.", "El niño ya duerme."),
  verbDraft("A1", "nehmen", "tomar; coger", "Ich nehme einen Apfel.", "Cojo una manzana."),
  verbDraft("A1", "geben", "dar", "Sie gibt mir den Schlüssel.", "Ella me da la llave."),
  verbDraft("A1", "helfen", "ayudar", "Er hilft seiner Schwester.", "Él ayuda a su hermana."),
  verbDraft("A2", "anfangen", "empezar", "Der Film fängt um acht Uhr an.", "La película empieza a las ocho."),
  verbDraft("A2", "aufhören", "parar; dejar de", "Der Regen hört bald auf.", "La lluvia parará pronto."),
  verbDraft("A2", "besuchen", "visitar", "Wir besuchen morgen unsere Großeltern.", "Mañana visitamos a nuestros abuelos."),
  verbDraft("A2", "brauchen", "necesitar", "Ich brauche noch zehn Minuten.", "Necesito diez minutos más."),
  verbDraft("A2", "dürfen", "poder; tener permiso", "Du darfst hier parken.", "Puedes aparcar aquí."),
  verbDraft("A2", "müssen", "tener que", "Wir müssen heute früh aufstehen.", "Hoy tenemos que levantarnos temprano."),
  verbDraft("A2", "sollen", "deber", "Er soll den Arzt anrufen.", "Él debe llamar al médico."),
  verbDraft("A2", "wollen", "querer", "Ich will heute zu Hause bleiben.", "Hoy quiero quedarme en casa."),
  verbDraft("A2", "können", "poder; saber", "Sie kann sehr gut schwimmen.", "Ella sabe nadar muy bien."),
  verbDraft("A2", "vergessen", "olvidar", "Ich vergesse manchmal meinen Schlüssel.", "A veces me olvido de la llave."),
  verbDraft("A2", "verlieren", "perder", "Er verliert oft seine Handschuhe.", "A menudo pierde los guantes."),
  verbDraft("A2", "sich entscheiden", "decidirse", "Wir entscheiden uns für den Zug.", "Nos decidimos por el tren."),
  verbDraft("A2", "gefallen", "gustar", "Das Kleid gefällt meiner Schwester.", "A mi hermana le gusta el vestido."),
  verbDraft("A2", "verstehen", "entender", "Ich verstehe die Frage jetzt.", "Ahora entiendo la pregunta."),
  verbDraft("A2", "anrufen", "llamar por teléfono", "Ich rufe dich später an.", "Te llamo más tarde."),
  verbDraft("B1.1", "sich bewerben", "presentar una candidatura", "Sie bewirbt sich bei einer Firma um eine Stelle.", "Presenta su candidatura a un puesto en una empresa."),
  verbDraft("B1.1", "sich erinnern", "recordar", "Er erinnert sich an seine erste Reise.", "Recuerda su primer viaje."),
  verbDraft("B1.1", "sich beschweren", "quejarse", "Die Gäste beschweren sich über den Lärm.", "Los huéspedes se quejan del ruido."),
  verbDraft("B1.1", "teilnehmen", "participar", "Marta nimmt an einem Sprachkurs teil.", "Marta participa en un curso de idiomas."),
  verbDraft("B1.1", "sich vorbereiten", "prepararse", "Wir bereiten uns auf die Prüfung vor.", "Nos preparamos para el examen."),
  verbDraft("B1.1", "vorschlagen", "proponer", "Ich schlage einen anderen Termin vor.", "Propongo otra fecha."),
  verbDraft("B1.1", "feststellen", "constatar; comprobar", "Die Polizei stellt den Schaden fest.", "La policía constata los daños."),
  verbDraft("B1.1", "vermeiden", "evitar", "Wir vermeiden unnötige Kosten.", "Evitamos gastos innecesarios."),
  verbDraft("B1.1", "erreichen", "alcanzar", "Sie erreicht ihr Ziel pünktlich.", "Alcanza su objetivo a tiempo."),
  verbDraft("B1.1", "entwickeln", "desarrollar", "Das Team entwickelt eine neue Lösung.", "El equipo desarrolla una nueva solución."),
  verbDraft("B1.1", "anbieten", "ofrecer", "Der Laden bietet frisches Brot an.", "La tienda ofrece pan fresco."),
  verbDraft("B1.1", "vergleichen", "comparar", "Ich vergleiche die beiden Angebote.", "Comparo las dos ofertas."),
  verbDraft("B1.1", "empfehlen", "recomendar", "Der Arzt empfiehlt mehr Bewegung.", "El médico recomienda hacer más ejercicio."),
  verbDraft("B1.1", "bestehen", "aprobar; superar", "Sie besteht die Prüfung beim ersten Versuch.", "Aprueba el examen a la primera."),
  verbDraft("B1.1", "sich gewöhnen", "acostumbrarse", "Wir gewöhnen uns an den neuen Zeitplan.", "Nos acostumbramos al nuevo horario."),
  verbDraft("B1.2", "nachweisen", "demostrar", "Der Bericht weist den Fehler nach.", "El informe demuestra el error."),
  verbDraft("B1.2", "verhandeln", "negociar", "Die Firmen verhandeln über den Vertrag.", "Las empresas negocian el contrato."),
  verbDraft("B1.2", "berücksichtigen", "tener en cuenta", "Wir berücksichtigen alle Vorschläge.", "Tenemos en cuenta todas las propuestas."),
  verbDraft("B1.2", "ermöglichen", "hacer posible", "Die neue Bahn ermöglicht eine schnelle Reise.", "El nuevo tren permite viajar rápidamente."),
  verbDraft("B1.2", "voraussetzen", "presuponer; exigir", "Die Stelle setzt Berufserfahrung voraus.", "El puesto exige experiencia profesional."),
  verbDraft("B1.2", "durchführen", "llevar a cabo", "Das Team führt eine Umfrage durch.", "El equipo lleva a cabo una encuesta."),
  verbDraft("B1.2", "sich eignen", "ser adecuado", "Dieses Buch eignet sich für Anfänger.", "Este libro es adecuado para principiantes."),
  verbDraft("B1.2", "nachdenken", "reflexionar", "Er denkt über die Entscheidung nach.", "Reflexiona sobre la decisión."),
  verbDraft("B1.2", "festlegen", "fijar; establecer", "Der Vertrag legt den Termin fest.", "El contrato fija la fecha."),
  verbDraft("B1.2", "übernehmen", "asumir", "Sie übernimmt die Verantwortung.", "Ella asume la responsabilidad."),
  verbDraft("B1.2", "erkennen", "reconocer", "Ich erkenne den Unterschied sofort.", "Reconozco la diferencia enseguida."),
  verbDraft("B1.2", "sich lohnen", "merecer la pena", "Die Reise lohnt sich trotz des Regens.", "El viaje merece la pena a pesar de la lluvia."),
  verbDraft("B1.2", "entstehen", "surgir", "Aus dem Gespräch entsteht eine neue Idee.", "De la conversación surge una nueva idea."),
  verbDraft("B1.2", "beitragen", "contribuir", "Regelmäßige Bewegung trägt zur Gesundheit bei.", "Hacer ejercicio con regularidad contribuye a la salud."),
  verbDraft("B1.2", "sich verlassen", "confiar", "Du kannst dich auf mich verlassen.", "Puedes confiar en mí."),
  verbDraft("B2.1", "gewährleisten", "garantizar", "Klare Regeln gewährleisten faire Bedingungen.", "Unas normas claras garantizan condiciones justas."),
  verbDraft("B2.1", "zurückgreifen", "recurrir", "Bei Fragen greifen wir auf die Anleitung zurück.", "Si tenemos dudas, recurrimos al manual."),
  verbDraft("B2.1", "bewältigen", "afrontar; superar", "Sie bewältigt die Aufgabe allein.", "Resuelve la tarea ella sola."),
  verbDraft("B2.1", "vornehmen", "realizar; efectuar", "Die Firma nimmt eine wichtige Änderung vor.", "La empresa realiza un cambio importante."),
  verbDraft("B2.1", "herausfinden", "averiguar", "Wir finden die Ursache bald heraus.", "Pronto averiguaremos la causa."),
  verbDraft("B2.1", "hinweisen", "señalar", "Der Bericht weist auf ein mögliches Risiko hin.", "El informe señala un posible riesgo."),
  verbDraft("B2.1", "sich auseinandersetzen", "analizar; abordar", "Das Team setzt sich mit dem Problem auseinander.", "El equipo aborda el problema."),
  verbDraft("B2.1", "in Betracht ziehen", "considerar", "Wir ziehen eine andere Lösung in Betracht.", "Consideramos otra solución."),
  verbDraft("B2.1", "festhalten", "dejar constancia", "Der Vertrag hält alle Vereinbarungen fest.", "El contrato deja constancia de todos los acuerdos."),
  verbDraft("B2.1", "nachlassen", "disminuir", "Der Wind lässt am Abend nach.", "El viento amaina por la tarde."),
  verbDraft("B2.1", "sich beschränken", "limitarse", "Der Bericht beschränkt sich auf die wichtigsten Fakten.", "El informe se limita a los hechos más importantes."),
  verbDraft("B2.1", "widersprechen", "contradecir", "Die Ergebnisse widersprechen der Vermutung.", "Los resultados contradicen la hipótesis."),
  verbDraft("B2.1", "einschätzen", "evaluar", "Die Expertin schätzt das Risiko realistisch ein.", "La experta evalúa el riesgo de forma realista."),
  verbDraft("B2.1", "sich auswirken", "repercutir", "Die Änderung wirkt sich auf den Verkehr aus.", "El cambio repercute en el tráfico."),
  verbDraft("B2.1", "verfügen", "disponer", "Die Firma verfügt über genügend Geld.", "La empresa dispone de dinero suficiente."),
  verbDraft("B2.2", "nachvollziehen", "comprender; seguir", "Ich kann seine Entscheidung gut nachvollziehen.", "Puedo comprender bien su decisión."),
  verbDraft("B2.2", "unterliegen", "estar sujeto", "Die Vereinbarung unterliegt deutschem Recht.", "El acuerdo está sujeto al derecho alemán."),
  verbDraft("B2.2", "aufweisen", "presentar; mostrar", "Der Bericht weist mehrere Fehler auf.", "El informe presenta varios errores."),
  verbDraft("B2.2", "beeinträchtigen", "perjudicar", "Der Lärm beeinträchtigt meine Konzentration.", "El ruido perjudica mi concentración."),
  verbDraft("B2.2", "heranziehen", "recurrir a", "Wir ziehen eine unabhängige Expertin heran.", "Recurrimos a una experta independiente."),
  verbDraft("B2.2", "sich ergeben", "resultar", "Aus den Daten ergibt sich ein klares Bild.", "De los datos se desprende una imagen clara."),
  verbDraft("B2.2", "beinhalten", "incluir", "Der Vertrag beinhaltet eine zusätzliche Garantie.", "El contrato incluye una garantía adicional."),
  verbDraft("B2.2", "sich bewähren", "demostrar su eficacia", "Die Methode hat sich im Alltag bewährt.", "El método ha demostrado su eficacia en la vida diaria."),
  verbDraft("B2.2", "nachkommen", "cumplir", "Sie kommt ihrer Pflicht pünktlich nach.", "Cumple puntualmente con su obligación."),
  verbDraft("B2.2", "vorliegen", "estar disponible", "Alle nötigen Unterlagen liegen inzwischen vor.", "Ya están disponibles todos los documentos necesarios."),
  verbDraft("B2.2", "entfallen", "suprimirse; cancelarse", "Der letzte Tagesordnungspunkt entfällt.", "Se suprime el último punto del orden del día."),
  verbDraft("B2.2", "sich herausstellen", "resultar", "Es stellt sich heraus, dass die Zahl falsch war.", "Resulta que la cifra era incorrecta."),
  verbDraft("B2.2", "geltend machen", "hacer valer", "Sie macht ihre Ansprüche schriftlich geltend.", "Hace valer sus derechos por escrito."),
  verbDraft("B2.2", "zugrunde liegen", "servir de base", "Dem Bericht liegt eine aktuelle Studie zugrunde.", "Un estudio reciente sirve de base al informe."),
  verbDraft("B2.2", "sich erschließen", "deducirse; entenderse", "Der Zusammenhang erschließt sich erst später.", "La relación solo se entiende más adelante."),
];

const connectorItems: VocabularyDraft[] = [
  connectorDraft("A1", "und", "y", "Anna lernt Deutsch, und Luis lernt Spanisch.", "Anna aprende alemán y Luis aprende español."),
  connectorDraft("A1", "aber", "pero", "Ich möchte joggen, aber es regnet.", "Quiero salir a correr, pero llueve."),
  connectorDraft("A1", "oder", "o", "Fährst du mit dem Bus oder nimmst du ein Taxi?", "¿Vas en autobús o coges un taxi?"),
  connectorDraft("A1", "denn", "porque", "Wir bleiben zu Hause, denn es regnet.", "Nos quedamos en casa porque llueve."),
  connectorDraft("A1", "sondern", "sino", "Er trinkt keinen Kaffee, sondern er bestellt Tee.", "No toma café, sino que pide té."),
  connectorDraft("A1", "dann", "luego", "Zuerst essen wir, dann gehen wir spazieren.", "Primero comemos y luego damos un paseo."),
  connectorDraft("A1", "zuerst", "primero", "Zuerst kaufe ich ein Ticket.", "Primero compro un billete."),
  connectorDraft("A1", "danach", "después", "Danach rufe ich meine Mutter an.", "Después llamo a mi madre."),
  connectorDraft("A1", "später", "más tarde", "Später besuchen wir unsere Freunde.", "Más tarde visitamos a nuestros amigos."),
  connectorDraft("A1", "also", "así que", "Es ist schon spät, also nehmen wir ein Taxi.", "Ya es tarde, así que cogemos un taxi."),
  connectorDraft("A2", "weil", "porque", "Ich bleibe zu Hause, weil ich krank bin.", "Me quedo en casa porque estoy enfermo."),
  connectorDraft("A2", "dass", "que", "Ich glaube, dass der Bus pünktlich kommt.", "Creo que el autobús llegará puntual."),
  connectorDraft("A2", "wenn", "si; cuando", "Wenn du Zeit hast, besuchen wir das Museum.", "Si tienes tiempo, visitamos el museo."),
  connectorDraft("A2", "deshalb", "por eso", "Der Zug hat Verspätung, deshalb warten wir auf dem Bahnsteig.", "El tren lleva retraso, por eso esperamos en el andén."),
  connectorDraft("A2", "trotzdem", "aun así", "Es regnet stark, trotzdem gehen wir spazieren.", "Llueve mucho; aun así, salimos a pasear."),
  connectorDraft("A2", "darum", "por eso", "Ich habe morgen frei, darum kann ich dich besuchen.", "Mañana tengo el día libre, por eso puedo visitarte."),
  connectorDraft("A2", "deswegen", "por ese motivo", "Der Laden ist geschlossen, deswegen kaufen wir später ein.", "La tienda está cerrada, por ese motivo compraremos más tarde."),
  connectorDraft("A2", "bevor", "antes de que", "Bevor wir essen, waschen wir uns die Hände.", "Antes de comer, nos lavamos las manos."),
  connectorDraft("A2", "nachdem", "después de que", "Nachdem er gegessen hat, geht er spazieren.", "Después de comer, sale a pasear."),
  connectorDraft("A2", "sonst", "si no; de lo contrario", "Beeil dich, sonst verpasst du den Bus.", "Date prisa; si no, perderás el autobús."),
  connectorDraft("B1.1", "obwohl", "aunque", "Obwohl es regnet, gehen wir zu Fuß nach Hause.", "Aunque llueve, volvemos a casa andando."),
  connectorDraft("B1.1", "damit", "para que", "Ich spreche langsam, damit alle mich verstehen.", "Hablo despacio para que todos me entiendan."),
  connectorDraft("B1.1", "während", "mientras", "Während ich koche, deckt mein Bruder den Tisch.", "Mientras cocino, mi hermano pone la mesa."),
  connectorDraft("B1.1", "außerdem", "además", "Die Wohnung liegt zentral; außerdem ist sie günstig.", "El piso está en el centro; además, es barato."),
  connectorDraft("B1.1", "sowohl … als auch", "tanto … como", "Sowohl Anna als auch Luis lernen Deutsch.", "Tanto Anna como Luis aprenden alemán."),
  connectorDraft("B1.1", "entweder … oder", "o … o", "Entweder fahren wir mit dem Zug oder wir nehmen den Bus.", "O vamos en tren o cogemos el autobús."),
  connectorDraft("B1.1", "weder … noch", "ni … ni", "Weder Mia noch Paul haben heute Zeit.", "Ni Mia ni Paul tienen tiempo hoy."),
  connectorDraft("B1.1", "falls", "en caso de que", "Falls du Hilfe brauchst, ruf mich bitte an.", "Si necesitas ayuda, llámame, por favor."),
  connectorDraft("B1.1", "sobald", "en cuanto", "Sobald der Kurs endet, gehen wir nach Hause.", "En cuanto termine el curso, nos vamos a casa."),
  connectorDraft("B1.1", "solange", "mientras; siempre que", "Solange das Wetter gut bleibt, essen wir draußen.", "Mientras haga buen tiempo, comeremos fuera."),
  connectorDraft("B1.2", "seitdem", "desde que", "Seitdem er in Berlin wohnt, fährt er mit dem Rad zur Arbeit.", "Desde que vive en Berlín, va al trabajo en bicicleta."),
  connectorDraft("B1.2", "hingegen", "en cambio", "Im Norden regnet es; im Süden hingegen scheint die Sonne.", "En el norte llueve; en cambio, en el sur hace sol."),
  connectorDraft("B1.2", "stattdessen", "en su lugar", "Der Zug fiel aus; stattdessen nahmen wir den Bus.", "Se canceló el tren; en su lugar, cogimos el autobús."),
  connectorDraft("B1.2", "sodass", "de modo que", "Der Bus kam zu spät, sodass wir den Anschluss verpassten.", "El autobús llegó tarde, de modo que perdimos el enlace."),
  connectorDraft("B1.2", "somit", "por consiguiente", "Die Frist ist abgelaufen; somit können wir den Antrag nicht ändern.", "El plazo ha vencido; por consiguiente, no podemos modificar la solicitud."),
  connectorDraft("B1.2", "währenddessen", "mientras tanto", "Sie kocht; währenddessen decke ich den Tisch.", "Ella cocina; mientras tanto, yo pongo la mesa."),
  connectorDraft("B1.2", "nicht nur … sondern auch", "no solo … sino también", "Sie spricht nicht nur Deutsch, sondern auch Französisch.", "Habla no solo alemán, sino también francés."),
  connectorDraft("B1.2", "geschweige denn", "y mucho menos", "Er hat keine Zeit, geschweige denn Geld.", "No tiene tiempo, y mucho menos dinero."),
  connectorDraft("B1.2", "andernfalls", "de lo contrario", "Bitte speichere die Datei, andernfalls gehen deine Änderungen verloren.", "Guarda el archivo, por favor; de lo contrario, perderás los cambios."),
  connectorDraft("B1.2", "sogar", "incluso", "Der Kurs ist anspruchsvoll; sogar erfahrene Lernende machen Fehler.", "El curso es exigente; incluso los estudiantes con experiencia cometen errores."),
  connectorDraft("B2.1", "gleichwohl", "no obstante", "Die Daten sind unvollständig; gleichwohl können wir eine erste Einschätzung geben.", "Los datos están incompletos; no obstante, podemos hacer una primera valoración."),
  connectorDraft("B2.1", "insofern … als", "en la medida en que", "Der Vorschlag ist insofern sinnvoll, als er beide Seiten berücksichtigt.", "La propuesta es útil en la medida en que tiene en cuenta a ambas partes."),
  connectorDraft("B2.1", "demzufolge", "por consiguiente", "Die Nachfrage ist gesunken; demzufolge werden weniger Waren bestellt.", "La demanda ha disminuido; por consiguiente, se encargan menos productos."),
  connectorDraft("B2.1", "zudem", "además", "Der Vertrag ist transparent; zudem schützt er beide Parteien.", "El contrato es transparente; además, protege a ambas partes."),
  connectorDraft("B2.1", "nichtsdestotrotz", "a pesar de ello", "Die Lage ist schwierig; nichtsdestotrotz setzen wir das Projekt fort.", "La situación es difícil; a pesar de ello, continuamos el proyecto."),
  connectorDraft("B2.1", "indes", "sin embargo", "Der Plan ist überzeugend; indes fehlen noch genaue Kosten.", "El plan es convincente; sin embargo, aún faltan los costes exactos."),
  connectorDraft("B2.1", "wohingegen", "mientras que", "Die erste Lösung spart Zeit, wohingegen die zweite günstiger ist.", "La primera solución ahorra tiempo, mientras que la segunda es más barata."),
  connectorDraft("B2.1", "zum einen … zum anderen", "por una parte … por otra", "Zum einen ist die Wohnung günstig, zum anderen liegt sie zentral.", "Por una parte, el piso es barato; por otra, está en el centro."),
  connectorDraft("B2.1", "angesichts dessen", "ante ello", "Die Nachfrage steigt; angesichts dessen erweitert die Firma ihre Produktion.", "La demanda aumenta; ante ello, la empresa amplía su producción."),
  connectorDraft("B2.1", "dagegen", "en cambio", "Die erste Methode spart Zeit; dagegen ist die zweite leichter umzusetzen.", "El primer método ahorra tiempo; en cambio, el segundo es más fácil de aplicar."),
  connectorDraft("B2.2", "dennoch", "sin embargo", "Die Preise steigen; dennoch kaufen viele Menschen das Produkt.", "Los precios suben; sin embargo, mucha gente compra el producto."),
  connectorDraft("B2.2", "folglich", "por consiguiente", "Der Vertrag wurde nicht unterschrieben; folglich kommt er nicht zustande.", "El contrato no se firmó; por consiguiente, no llega a formalizarse."),
  connectorDraft("B2.2", "indem", "al; mediante", "Indem wir die Abläufe vereinfachen, sparen wir Zeit.", "Al simplificar los procesos, ahorramos tiempo."),
  connectorDraft("B2.2", "sofern", "siempre que", "Sofern alle Unterlagen vorliegen, können wir den Antrag bearbeiten.", "Siempre que estén todos los documentos, podremos tramitar la solicitud."),
  connectorDraft("B2.2", "zumal", "máxime cuando", "Wir sollten den Plan ändern, zumal die Kosten stärker gestiegen sind.", "Deberíamos cambiar el plan, máxime cuando los costes han aumentado más."),
  connectorDraft("B2.2", "je … desto", "cuanto más … más", "Je länger die Verhandlung dauert, desto schwieriger wird eine Einigung.", "Cuanto más dura la negociación, más difícil resulta llegar a un acuerdo."),
  connectorDraft("B2.2", "infolgedessen", "como consecuencia", "Der Lieferant fiel aus; infolgedessen verzögerte sich die Produktion.", "El proveedor falló; como consecuencia, se retrasó la producción."),
  connectorDraft("B2.2", "einerseits … andererseits", "por un lado … por otro", "Einerseits senkt die Maßnahme die Kosten, andererseits erhöht sie den Aufwand.", "Por un lado, la medida reduce los costes; por otro, aumenta el esfuerzo."),
  connectorDraft("B2.2", "nichtsdestoweniger", "no obstante", "Nichtsdestoweniger bleibt die Entscheidung umstritten.", "No obstante, la decisión sigue siendo polémica."),
  connectorDraft("B2.2", "nicht zuletzt weil", "sobre todo porque", "Die Lage ist schwierig, nicht zuletzt weil die Frist knapp ist.", "La situación es difícil, sobre todo porque el plazo es ajustado."),
];

const additionalNouns: Array<{ topic: string; items: VocabularyDraft[] }> = [
  {
    topic: "saludos",
    items: [
      nounDraft("A2", "Vorstellung", "die", "Vorstellungen", "presentación"),
      nounDraft("A2", "Einladung", "die", "Einladungen", "invitación"),
      nounDraft("B1.1", "Mitteilung", "die", "Mitteilungen", "comunicación"),
      nounDraft("B1.1", "Eindruck", "der", "Eindrücke", "impresión"),
      nounDraft("B1.2", "Aussage", "die", "Aussagen", "declaración"),
      nounDraft("B1.2", "Behauptung", "die", "Behauptungen", "afirmación"),
      nounDraft("B2.1", "Rückmeldung", "die", "Rückmeldungen", "comentario; respuesta"),
      nounDraft("B2.1", "Missverständnis", "das", "Missverständnisse", "malentendido"),
      nounDraft("B2.2", "Stellungnahme", "die", "Stellungnahmen", "declaración; postura"),
      nounDraft("B2.2", "Wortmeldung", "die", "Wortmeldungen", "intervención"),
    ],
  },
  {
    topic: "numeros",
    items: [
      nounDraft("A2", "Dauer", "die", "Dauern", "duración"),
      nounDraft("A2", "Zeitraum", "der", "Zeiträume", "periodo"),
      nounDraft("B1.1", "Frist", "die", "Fristen", "plazo"),
      nounDraft("B1.1", "Zeitabschnitt", "der", "Zeitabschnitte", "periodo de tiempo"),
      nounDraft("B1.2", "Verzögerung", "die", "Verzögerungen", "retraso"),
      nounDraft("B1.2", "Vorsprung", "der", "Vorsprünge", "ventaja"),
      nounDraft("B2.1", "Abweichung", "die", "Abweichungen", "desviación"),
      nounDraft("B2.1", "Schwankung", "die", "Schwankungen", "fluctuación"),
      nounDraft("B2.2", "Zeitersparnis", "die", "Zeitersparnisse", "ahorro de tiempo"),
      nounDraft("B2.2", "Schätzung", "die", "Schätzungen", "estimación"),
    ],
  },
  {
    topic: "familia",
    items: [
      nounDraft("A2", "Verwandte", "der", "Verwandten", "pariente"),
      nounDraft("A2", "Enkel", "der", "Enkel", "nieto"),
      nounDraft("B1.1", "Verhältnis", "das", "Verhältnisse", "relación"),
      nounDraft("B1.1", "Nachkomme", "der", "Nachkommen", "descendiente"),
      nounDraft("B1.2", "Generation", "die", "Generationen", "generación"),
      nounDraft("B1.2", "Stiefmutter", "die", "Stiefmütter", "madrastra"),
      nounDraft("B2.1", "Bezugsperson", "die", "Bezugspersonen", "persona de referencia"),
      nounDraft("B2.1", "Adoption", "die", "Adoptionen", "adopción"),
      nounDraft("B2.2", "Lebensgemeinschaft", "die", "Lebensgemeinschaften", "convivencia; pareja de hecho"),
      nounDraft("B2.2", "Familiengründung", "die", "Familiengründungen", "formación de una familia"),
    ],
  },
  {
    topic: "comida",
    items: [
      nounDraft("A2", "Zutat", "die", "Zutaten", "ingrediente"),
      nounDraft("A2", "Geschmack", "der", "Geschmäcker", "sabor"),
      nounDraft("B1.1", "Ernährungsweise", "die", "Ernährungsweisen", "forma de alimentarse"),
      nounDraft("B1.1", "Nährstoff", "der", "Nährstoffe", "nutriente"),
      nounDraft("B1.2", "Mahlzeit", "die", "Mahlzeiten", "comida"),
      nounDraft("B1.2", "Portion", "die", "Portionen", "ración"),
      nounDraft("B2.1", "Zusatzstoff", "der", "Zusatzstoffe", "aditivo"),
      nounDraft("B2.1", "Unverträglichkeit", "die", "Unverträglichkeiten", "intolerancia"),
      nounDraft("B2.2", "Verpackung", "die", "Verpackungen", "envase"),
      nounDraft("B2.2", "Haltbarkeitsdatum", "das", "Haltbarkeitsdaten", "fecha de caducidad"),
    ],
  },
  {
    topic: "casa",
    items: [
      nounDraft("A2", "Möbelstück", "das", "Möbelstücke", "mueble"),
      nounDraft("A2", "Schublade", "die", "Schubladen", "cajón"),
      nounDraft("B1.1", "Haushalt", "der", "Haushalte", "hogar"),
      nounDraft("B1.1", "Eigentümer", "der", "Eigentümer", "propietario"),
      nounDraft("B1.2", "Instandhaltung", "die", "Instandhaltungen", "mantenimiento"),
      nounDraft("B1.2", "Renovierung", "die", "Renovierungen", "reforma"),
      nounDraft("B2.1", "Sanierung", "die", "Sanierungen", "rehabilitación"),
      nounDraft("B2.1", "Versorgung", "die", "Versorgungen", "suministro"),
      nounDraft("B2.2", "Gebäudesanierung", "die", "Gebäudesanierungen", "rehabilitación de edificios"),
      nounDraft("B2.2", "Nutzungsdauer", "die", "Nutzungsdauern", "vida útil"),
    ],
  },
  {
    topic: "ciudad",
    items: [
      nounDraft("A2", "Kreuzung", "die", "Kreuzungen", "cruce"),
      nounDraft("A2", "Verkehrsmittel", "das", "Verkehrsmittel", "medio de transporte"),
      nounDraft("B1.1", "Umgebung", "die", "Umgebungen", "entorno"),
      nounDraft("B1.1", "Einwohner", "der", "Einwohner", "habitante"),
      nounDraft("B1.2", "Infrastruktur", "die", "Infrastrukturen", "infraestructura"),
      nounDraft("B1.2", "Einrichtung", "die", "Einrichtungen", "instalación"),
      nounDraft("B2.1", "Wohnraum", "der", "Wohnräume", "vivienda"),
      nounDraft("B2.1", "Pendler", "der", "Pendler", "persona que se desplaza a diario"),
      nounDraft("B2.2", "Bebauungsplan", "der", "Bebauungspläne", "plan urbanístico"),
      nounDraft("B2.2", "Stadtentwicklung", "die", "Stadtentwicklungen", "desarrollo urbano"),
    ],
  },
  {
    topic: "tiempo",
    items: [
      nounDraft("A2", "Jahreszeit", "die", "Jahreszeiten", "estación del año"),
      nounDraft("A2", "Gewitter", "das", "Gewitter", "tormenta"),
      nounDraft("B1.1", "Zeitpunkt", "der", "Zeitpunkte", "momento"),
      nounDraft("B1.1", "Zeitplan", "der", "Zeitpläne", "planificación"),
      nounDraft("B1.2", "Terminänderung", "die", "Terminänderungen", "cambio de fecha"),
      nounDraft("B1.2", "Verschiebung", "die", "Verschiebungen", "aplazamiento"),
      nounDraft("B2.1", "Zeitspanne", "die", "Zeitspannen", "periodo de tiempo"),
      nounDraft("B2.1", "Zeitfenster", "das", "Zeitfenster", "franja horaria"),
      nounDraft("B2.2", "Zeitvorgabe", "die", "Zeitvorgaben", "plazo establecido"),
      nounDraft("B2.2", "Fristverlängerung", "die", "Fristverlängerungen", "prórroga"),
    ],
  },
  {
    topic: "ropa",
    items: [
      nounDraft("A2", "Stoff", "der", "Stoffe", "tejido"),
      nounDraft("A2", "Muster", "das", "Muster", "estampado"),
      nounDraft("B1.1", "Material", "das", "Materialien", "material"),
      nounDraft("B1.1", "Faser", "die", "Fasern", "fibra"),
      nounDraft("B1.2", "Pflegehinweis", "der", "Pflegehinweise", "instrucción de cuidado"),
      nounDraft("B1.2", "Umweltbelastung", "die", "Umweltbelastungen", "impacto ambiental"),
      nounDraft("B2.1", "Maßanfertigung", "die", "Maßanfertigungen", "confección a medida"),
      nounDraft("B2.1", "Färbung", "die", "Färbungen", "tinte"),
      nounDraft("B2.2", "Fertigung", "die", "Fertigungen", "fabricación"),
      nounDraft("B2.2", "Konsument", "der", "Konsumenten", "consumidor"),
    ],
  },
  {
    topic: "trabajo",
    items: [
      nounDraft("A2", "Bewerbung", "die", "Bewerbungen", "solicitud de empleo"),
      nounDraft("A2", "Erfahrung", "die", "Erfahrungen", "experiencia"),
      nounDraft("B1.1", "Bewerbungsgespräch", "das", "Bewerbungsgespräche", "entrevista de trabajo"),
      nounDraft("B1.1", "Tätigkeit", "die", "Tätigkeiten", "actividad"),
      nounDraft("B1.2", "Beförderung", "die", "Beförderungen", "ascenso"),
      nounDraft("B1.2", "Arbeitsbedingung", "die", "Arbeitsbedingungen", "condición laboral"),
      nounDraft("B2.1", "Zuständigkeit", "die", "Zuständigkeiten", "competencia; responsabilidad"),
      nounDraft("B2.1", "Abteilung", "die", "Abteilungen", "departamento"),
      nounDraft("B2.2", "Arbeitsmarkt", "der", "Arbeitsmärkte", "mercado laboral"),
      nounDraft("B2.2", "Leistungsbewertung", "die", "Leistungsbewertungen", "evaluación del rendimiento"),
    ],
  },
  {
    topic: "ocio",
    items: [
      nounDraft("A2", "Veranstaltung", "die", "Veranstaltungen", "evento"),
      nounDraft("A2", "Ausflug", "der", "Ausflüge", "excursión"),
      nounDraft("B1.1", "Aufführung", "die", "Aufführungen", "representación"),
      nounDraft("B1.1", "Ausstellung", "die", "Ausstellungen", "exposición"),
      nounDraft("B1.2", "Wettbewerb", "der", "Wettbewerbe", "concurso"),
      nounDraft("B1.2", "Auseinandersetzung", "die", "Auseinandersetzungen", "debate"),
      nounDraft("B2.1", "Darbietung", "die", "Darbietungen", "actuación"),
      nounDraft("B2.1", "Veranstalter", "der", "Veranstalter", "organizador"),
      nounDraft("B2.2", "Inszenierung", "die", "Inszenierungen", "puesta en escena"),
      nounDraft("B2.2", "Zuschauer", "der", "Zuschauer", "espectador"),
    ],
  },
];

function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replaceAll("ß", "ss")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

export const vocabulary = [
  ...topics,
  { topic: "verbos", items: verbItems },
  { topic: "conectores", items: connectorItems },
  ...additionalNouns,
].flatMap(({ topic, items }) =>
  items.map((item) => ({
    id: `v-${topic}-${slugify(item.german)}`,
    topic,
    ...item,
    cefrLevel: item.cefrLevel ?? "A1",
    article: item.article ?? null,
    plural: item.plural ?? null,
  })),
);
