type VocabularyDraft = {
  german: string;
  spanish: string;
  article: "der" | "die" | "das";
  plural: string;
  exampleDe?: string;
  exampleEs?: string;
};

const topics: Array<{ topic: string; items: VocabularyDraft[] }> = [
  {
    topic: "saludos",
    items: [
      { german: "Name", article: "der", plural: "Namen", spanish: "nombre" },
      { german: "Gruß", article: "der", plural: "Grüße", spanish: "saludo", exampleDe: "Viele Grüße aus Berlin.", exampleEs: "Muchos saludos desde Berlín." },
      { german: "Frage", article: "die", plural: "Fragen", spanish: "pregunta", exampleDe: "Die Frage ist einfach.", exampleEs: "La pregunta es fácil." },
      { german: "Antwort", article: "die", plural: "Antworten", spanish: "respuesta" },
      { german: "Morgen", article: "der", plural: "Morgen", spanish: "mañana", exampleDe: "Der Morgen ist ruhig.", exampleEs: "La mañana está tranquila." },
      { german: "Tag", article: "der", plural: "Tage", spanish: "día", exampleDe: "Der Tag ist schön.", exampleEs: "El día es bonito." },
      { german: "Abend", article: "der", plural: "Abende", spanish: "tarde; noche" },
      { german: "Nacht", article: "die", plural: "Nächte", spanish: "noche" },
      { german: "Freund", article: "der", plural: "Freunde", spanish: "amigo", exampleDe: "Mein Freund heißt Pablo.", exampleEs: "Mi amigo se llama Pablo." },
      { german: "Freundin", article: "die", plural: "Freundinnen", spanish: "amiga" },
      { german: "Gespräch", article: "das", plural: "Gespräche", spanish: "conversación" },
      { german: "Sprache", article: "die", plural: "Sprachen", spanish: "idioma" },
      { german: "Wort", article: "das", plural: "Wörter", spanish: "palabra", exampleDe: "Das Wort ist neu.", exampleEs: "La palabra es nueva." },
      { german: "Satz", article: "der", plural: "Sätze", spanish: "frase" },
      { german: "Beispiel", article: "das", plural: "Beispiele", spanish: "ejemplo" },
      { german: "Person", article: "die", plural: "Personen", spanish: "persona" },
      { german: "Herr", article: "der", plural: "Herren", spanish: "señor" },
      { german: "Frau", article: "die", plural: "Frauen", spanish: "mujer; señora", exampleDe: "Die Frau kommt aus Spanien.", exampleEs: "La mujer es de España." },
      { german: "Land", article: "das", plural: "Länder", spanish: "país" },
      { german: "Stadt", article: "die", plural: "Städte", spanish: "ciudad" },
      { german: "Abschied", article: "der", plural: "Abschiede", spanish: "despedida" },
    ],
  },
  {
    topic: "numeros",
    items: [
      { german: "Zahl", article: "die", plural: "Zahlen", spanish: "número", exampleDe: "Die Zahl ist sieben.", exampleEs: "El número es siete." },
      { german: "Nummer", article: "die", plural: "Nummern", spanish: "número; cifra" },
      { german: "Alter", article: "das", plural: "—", spanish: "edad" },
      { german: "Jahr", article: "das", plural: "Jahre", spanish: "año", exampleDe: "Das Jahr hat zwölf Monate.", exampleEs: "El año tiene doce meses." },
      { german: "Woche", article: "die", plural: "Wochen", spanish: "semana" },
      { german: "Monat", article: "der", plural: "Monate", spanish: "mes" },
      { german: "Stunde", article: "die", plural: "Stunden", spanish: "hora" },
      { german: "Minute", article: "die", plural: "Minuten", spanish: "minuto" },
      { german: "Sekunde", article: "die", plural: "Sekunden", spanish: "segundo" },
      { german: "Geburtstag", article: "der", plural: "Geburtstage", spanish: "cumpleaños" },
      { german: "Euro", article: "der", plural: "Euro", spanish: "euro" },
      { german: "Cent", article: "der", plural: "Cent", spanish: "céntimo" },
      { german: "Preis", article: "der", plural: "Preise", spanish: "precio", exampleDe: "Der Preis ist niedrig.", exampleEs: "El precio es bajo." },
      { german: "Rechnung", article: "die", plural: "Rechnungen", spanish: "cuenta; factura" },
      { german: "Menge", article: "die", plural: "Mengen", spanish: "cantidad" },
      { german: "Hälfte", article: "die", plural: "Hälften", spanish: "mitad" },
      { german: "Paar", article: "das", plural: "Paare", spanish: "par" },
      { german: "Summe", article: "die", plural: "Summen", spanish: "suma" },
      { german: "Zeit", article: "die", plural: "Zeiten", spanish: "tiempo" },
      { german: "Million", article: "die", plural: "Millionen", spanish: "millón" },
      { german: "Ziffer", article: "die", plural: "Ziffern", spanish: "dígito" },
    ],
  },
  {
    topic: "familia",
    items: [
      { german: "Mutter", article: "die", plural: "Mütter", spanish: "madre", exampleDe: "Meine Mutter kocht gern.", exampleEs: "A mi madre le gusta cocinar." },
      { german: "Vater", article: "der", plural: "Väter", spanish: "padre" },
      { german: "Eltern", article: "die", plural: "Eltern", spanish: "padres" },
      { german: "Bruder", article: "der", plural: "Brüder", spanish: "hermano", exampleDe: "Mein Bruder wohnt in Madrid.", exampleEs: "Mi hermano vive en Madrid." },
      { german: "Schwester", article: "die", plural: "Schwestern", spanish: "hermana" },
      { german: "Sohn", article: "der", plural: "Söhne", spanish: "hijo" },
      { german: "Tochter", article: "die", plural: "Töchter", spanish: "hija" },
      { german: "Kind", article: "das", plural: "Kinder", spanish: "niño; hijo", exampleDe: "Das Kind spielt im Garten.", exampleEs: "El niño juega en el jardín." },
      { german: "Familie", article: "die", plural: "Familien", spanish: "familia" },
      { german: "Großmutter", article: "die", plural: "Großmütter", spanish: "abuela" },
      { german: "Großvater", article: "der", plural: "Großväter", spanish: "abuelo" },
      { german: "Großeltern", article: "die", plural: "Großeltern", spanish: "abuelos" },
      { german: "Onkel", article: "der", plural: "Onkel", spanish: "tío" },
      { german: "Tante", article: "die", plural: "Tanten", spanish: "tía" },
      { german: "Cousin", article: "der", plural: "Cousins", spanish: "primo" },
      { german: "Cousine", article: "die", plural: "Cousinen", spanish: "prima" },
      { german: "Mann", article: "der", plural: "Männer", spanish: "hombre; marido" },
      { german: "Frau", article: "die", plural: "Frauen", spanish: "mujer; esposa" },
      { german: "Partner", article: "der", plural: "Partner", spanish: "pareja" },
      { german: "Partnerin", article: "die", plural: "Partnerinnen", spanish: "pareja" },
      { german: "Geschwister", article: "das", plural: "Geschwister", spanish: "hermano o hermana" },
    ],
  },
  {
    topic: "comida",
    items: [
      { german: "Essen", article: "das", plural: "—", spanish: "comida" },
      { german: "Apfel", article: "der", plural: "Äpfel", spanish: "manzana", exampleDe: "Der Apfel ist rot.", exampleEs: "La manzana es roja." },
      { german: "Banane", article: "die", plural: "Bananen", spanish: "plátano; banana" },
      { german: "Brot", article: "das", plural: "Brote", spanish: "pan", exampleDe: "Das Brot ist frisch.", exampleEs: "El pan está fresco." },
      { german: "Käse", article: "der", plural: "Käse", spanish: "queso" },
      { german: "Milch", article: "die", plural: "—", spanish: "leche", exampleDe: "Die Milch ist kalt.", exampleEs: "La leche está fría." },
      { german: "Wasser", article: "das", plural: "—", spanish: "agua" },
      { german: "Kaffee", article: "der", plural: "Kaffees", spanish: "café" },
      { german: "Tee", article: "der", plural: "Tees", spanish: "té" },
      { german: "Ei", article: "das", plural: "Eier", spanish: "huevo" },
      { german: "Fleisch", article: "das", plural: "—", spanish: "carne" },
      { german: "Fisch", article: "der", plural: "Fische", spanish: "pescado; pez" },
      { german: "Kartoffel", article: "die", plural: "Kartoffeln", spanish: "patata" },
      { german: "Tomate", article: "die", plural: "Tomaten", spanish: "tomate" },
      { german: "Suppe", article: "die", plural: "Suppen", spanish: "sopa" },
      { german: "Salat", article: "der", plural: "Salate", spanish: "ensalada" },
      { german: "Zucker", article: "der", plural: "—", spanish: "azúcar" },
      { german: "Salz", article: "das", plural: "—", spanish: "sal" },
      { german: "Butter", article: "die", plural: "—", spanish: "mantequilla" },
      { german: "Orange", article: "die", plural: "Orangen", spanish: "naranja" },
      { german: "Saft", article: "der", plural: "Säfte", spanish: "zumo", exampleDe: "Der Saft ist frisch.", exampleEs: "El zumo está fresco." },
      { german: "Erdbeere", article: "die", plural: "Erdbeeren", spanish: "fresa" },
    ],
  },
  {
    topic: "casa",
    items: [
      { german: "Haus", article: "das", plural: "Häuser", spanish: "casa", exampleDe: "Das Haus ist groß.", exampleEs: "La casa es grande." },
      { german: "Wohnung", article: "die", plural: "Wohnungen", spanish: "piso; apartamento", exampleDe: "Die Wohnung hat zwei Zimmer.", exampleEs: "El piso tiene dos habitaciones." },
      { german: "Zimmer", article: "das", plural: "Zimmer", spanish: "habitación" },
      { german: "Küche", article: "die", plural: "Küchen", spanish: "cocina", exampleDe: "Die Küche ist hell.", exampleEs: "La cocina es luminosa." },
      { german: "Bad", article: "das", plural: "Bäder", spanish: "baño" },
      { german: "Schlafzimmer", article: "das", plural: "Schlafzimmer", spanish: "dormitorio" },
      { german: "Wohnzimmer", article: "das", plural: "Wohnzimmer", spanish: "salón" },
      { german: "Bett", article: "das", plural: "Betten", spanish: "cama", exampleDe: "Das Bett ist bequem.", exampleEs: "La cama es cómoda." },
      { german: "Tisch", article: "der", plural: "Tische", spanish: "mesa", exampleDe: "Der Tisch steht im Zimmer.", exampleEs: "La mesa está en la habitación." },
      { german: "Stuhl", article: "der", plural: "Stühle", spanish: "silla" },
      { german: "Tür", article: "die", plural: "Türen", spanish: "puerta" },
      { german: "Fenster", article: "das", plural: "Fenster", spanish: "ventana", exampleDe: "Das Fenster ist offen.", exampleEs: "La ventana está abierta." },
      { german: "Lampe", article: "die", plural: "Lampen", spanish: "lámpara" },
      { german: "Schrank", article: "der", plural: "Schränke", spanish: "armario" },
      { german: "Sofa", article: "das", plural: "Sofas", spanish: "sofá" },
      { german: "Schlüssel", article: "der", plural: "Schlüssel", spanish: "llave" },
      { german: "Wand", article: "die", plural: "Wände", spanish: "pared" },
      { german: "Boden", article: "der", plural: "Böden", spanish: "suelo" },
      { german: "Teppich", article: "der", plural: "Teppiche", spanish: "alfombra" },
      { german: "Treppe", article: "die", plural: "Treppen", spanish: "escalera" },
      { german: "Garten", article: "der", plural: "Gärten", spanish: "jardín" },
    ],
  },
  {
    topic: "ciudad",
    items: [
      { german: "Stadt", article: "die", plural: "Städte", spanish: "ciudad" },
      { german: "Straße", article: "die", plural: "Straßen", spanish: "calle", exampleDe: "Die Straße ist lang.", exampleEs: "La calle es larga." },
      { german: "Bahnhof", article: "der", plural: "Bahnhöfe", spanish: "estación de tren", exampleDe: "Der Bahnhof ist hier.", exampleEs: "La estación está aquí." },
      { german: "Bus", article: "der", plural: "Busse", spanish: "autobús", exampleDe: "Der Bus kommt gleich.", exampleEs: "El autobús llega enseguida." },
      { german: "Zug", article: "der", plural: "Züge", spanish: "tren" },
      { german: "Auto", article: "das", plural: "Autos", spanish: "coche" },
      { german: "Fahrrad", article: "das", plural: "Fahrräder", spanish: "bicicleta", exampleDe: "Das Fahrrad steht draußen.", exampleEs: "La bicicleta está fuera." },
      { german: "Haltestelle", article: "die", plural: "Haltestellen", spanish: "parada" },
      { german: "U-Bahn", article: "die", plural: "U-Bahnen", spanish: "metro" },
      { german: "S-Bahn", article: "die", plural: "S-Bahnen", spanish: "tren de cercanías" },
      { german: "Flughafen", article: "der", plural: "Flughäfen", spanish: "aeropuerto" },
      { german: "Ticket", article: "das", plural: "Tickets", spanish: "billete" },
      { german: "Karte", article: "die", plural: "Karten", spanish: "mapa; tarjeta" },
      { german: "Schule", article: "die", plural: "Schulen", spanish: "escuela", exampleDe: "Die Schule ist in der Stadt.", exampleEs: "La escuela está en la ciudad." },
      { german: "Universität", article: "die", plural: "Universitäten", spanish: "universidad" },
      { german: "Geschäft", article: "das", plural: "Geschäfte", spanish: "tienda" },
      { german: "Supermarkt", article: "der", plural: "Supermärkte", spanish: "supermercado" },
      { german: "Apotheke", article: "die", plural: "Apotheken", spanish: "farmacia", exampleDe: "Die Apotheke ist geöffnet.", exampleEs: "La farmacia está abierta." },
      { german: "Krankenhaus", article: "das", plural: "Krankenhäuser", spanish: "hospital" },
      { german: "Brücke", article: "die", plural: "Brücken", spanish: "puente" },
      { german: "Park", article: "der", plural: "Parks", spanish: "parque" },
    ],
  },
  {
    topic: "tiempo",
    items: [
      { german: "Uhr", article: "die", plural: "Uhren", spanish: "reloj; hora", exampleDe: "Es ist sieben Uhr.", exampleEs: "Son las siete." },
      { german: "Wecker", article: "der", plural: "Wecker", spanish: "despertador" },
      { german: "Vormittag", article: "der", plural: "Vormittage", spanish: "mañana (antes del mediodía)" },
      { german: "Mittag", article: "der", plural: "Mittage", spanish: "mediodía" },
      { german: "Nachmittag", article: "der", plural: "Nachmittage", spanish: "tarde" },
      { german: "Morgen", article: "der", plural: "Morgen", spanish: "mañana" },
      { german: "Abend", article: "der", plural: "Abende", spanish: "tarde; noche" },
      { german: "Nacht", article: "die", plural: "Nächte", spanish: "noche" },
      { german: "Termin", article: "der", plural: "Termine", spanish: "cita" },
      { german: "Arbeit", article: "die", plural: "Arbeiten", spanish: "trabajo" },
      { german: "Beruf", article: "der", plural: "Berufe", spanish: "profesión" },
      { german: "Pause", article: "die", plural: "Pausen", spanish: "pausa", exampleDe: "Die Pause ist kurz.", exampleEs: "La pausa es corta." },
      { german: "Alltag", article: "der", plural: "Alltage", spanish: "vida cotidiana" },
      { german: "Frühstück", article: "das", plural: "Frühstücke", spanish: "desayuno", exampleDe: "Das Frühstück ist fertig.", exampleEs: "El desayuno está listo." },
      { german: "Mittagessen", article: "das", plural: "Mittagessen", spanish: "comida; almuerzo" },
      { german: "Abendessen", article: "das", plural: "Abendessen", spanish: "cena" },
      { german: "Schlaf", article: "der", plural: "—", spanish: "sueño" },
      { german: "Sport", article: "der", plural: "—", spanish: "deporte" },
      { german: "Kalender", article: "der", plural: "Kalender", spanish: "calendario" },
      { german: "Woche", article: "die", plural: "Wochen", spanish: "semana" },
      { german: "Wochenende", article: "das", plural: "Wochenenden", spanish: "fin de semana", exampleDe: "Am Wochenende haben wir frei.", exampleEs: "El fin de semana tenemos libre." },
    ],
  },
  {
    topic: "ropa",
    items: [
      { german: "Kleidung", article: "die", plural: "—", spanish: "ropa" },
      { german: "Hemd", article: "das", plural: "Hemden", spanish: "camisa", exampleDe: "Das Hemd ist blau.", exampleEs: "La camisa es azul." },
      { german: "Bluse", article: "die", plural: "Blusen", spanish: "blusa", exampleDe: "Die Bluse ist schön.", exampleEs: "La blusa es bonita." },
      { german: "Hose", article: "die", plural: "Hosen", spanish: "pantalón", exampleDe: "Die Hose ist neu.", exampleEs: "El pantalón es nuevo." },
      { german: "Kleid", article: "das", plural: "Kleider", spanish: "vestido" },
      { german: "Pullover", article: "der", plural: "Pullover", spanish: "jersey" },
      { german: "Jacke", article: "die", plural: "Jacken", spanish: "chaqueta" },
      { german: "Mantel", article: "der", plural: "Mäntel", spanish: "abrigo", exampleDe: "Der Mantel ist warm.", exampleEs: "El abrigo es abrigado." },
      { german: "Schuh", article: "der", plural: "Schuhe", spanish: "zapato", exampleDe: "Die Schuhe sind bequem.", exampleEs: "Los zapatos son cómodos." },
      { german: "Socke", article: "die", plural: "Socken", spanish: "calcetín" },
      { german: "Rock", article: "der", plural: "Röcke", spanish: "falda" },
      { german: "Mütze", article: "die", plural: "Mützen", spanish: "gorro" },
      { german: "Hut", article: "der", plural: "Hüte", spanish: "sombrero" },
      { german: "Tasche", article: "die", plural: "Taschen", spanish: "bolso; bolsa" },
      { german: "Größe", article: "die", plural: "Größen", spanish: "talla; tamaño" },
      { german: "Farbe", article: "die", plural: "Farben", spanish: "color" },
      { german: "Preis", article: "der", plural: "Preise", spanish: "precio" },
      { german: "Geld", article: "das", plural: "—", spanish: "dinero" },
      { german: "Kasse", article: "die", plural: "Kassen", spanish: "caja" },
      { german: "Geschäft", article: "das", plural: "Geschäfte", spanish: "tienda" },
      { german: "Umkleidekabine", article: "die", plural: "Umkleidekabinen", spanish: "probador" },
    ],
  },
  {
    topic: "trabajo",
    items: [
      { german: "Arbeit", article: "die", plural: "Arbeiten", spanish: "trabajo", exampleDe: "Die Arbeit beginnt um neun Uhr.", exampleEs: "El trabajo empieza a las nueve." },
      { german: "Arbeitsplatz", article: "der", plural: "Arbeitsplätze", spanish: "puesto de trabajo" },
      { german: "Büro", article: "das", plural: "Büros", spanish: "oficina", exampleDe: "Das Büro ist hell.", exampleEs: "La oficina es luminosa." },
      { german: "Kollege", article: "der", plural: "Kollegen", spanish: "compañero de trabajo" },
      { german: "Kollegin", article: "die", plural: "Kolleginnen", spanish: "compañera de trabajo" },
      { german: "Chef", article: "der", plural: "Chefs", spanish: "jefe" },
      { german: "Chefin", article: "die", plural: "Chefinnen", spanish: "jefa" },
      { german: "Lehrer", article: "der", plural: "Lehrer", spanish: "profesor" },
      { german: "Lehrerin", article: "die", plural: "Lehrerinnen", spanish: "profesora", exampleDe: "Die Lehrerin erklärt die Aufgabe.", exampleEs: "La profesora explica el ejercicio." },
      { german: "Student", article: "der", plural: "Studenten", spanish: "estudiante" },
      { german: "Studentin", article: "die", plural: "Studentinnen", spanish: "estudiante" },
      { german: "Schule", article: "die", plural: "Schulen", spanish: "escuela" },
      { german: "Universität", article: "die", plural: "Universitäten", spanish: "universidad" },
      { german: "Unterricht", article: "der", plural: "—", spanish: "clase; enseñanza" },
      { german: "Buch", article: "das", plural: "Bücher", spanish: "libro", exampleDe: "Das Buch liegt auf dem Tisch.", exampleEs: "El libro está sobre la mesa." },
      { german: "Stift", article: "der", plural: "Stifte", spanish: "bolígrafo" },
      { german: "Heft", article: "das", plural: "Hefte", spanish: "cuaderno" },
      { german: "Aufgabe", article: "die", plural: "Aufgaben", spanish: "tarea; ejercicio" },
      { german: "Prüfung", article: "die", plural: "Prüfungen", spanish: "examen" },
      { german: "Sprache", article: "die", plural: "Sprachen", spanish: "idioma" },
      { german: "E-Mail", article: "die", plural: "E-Mails", spanish: "correo electrónico" },
      { german: "Computer", article: "der", plural: "Computer", spanish: "ordenador" },
      { german: "Kurs", article: "der", plural: "Kurse", spanish: "curso", exampleDe: "Der Kurs beginnt um neun Uhr.", exampleEs: "El curso empieza a las nueve." },
    ],
  },
  {
    topic: "ocio",
    items: [
      { german: "Hobby", article: "das", plural: "Hobbys", spanish: "afición", exampleDe: "Mein Hobby macht Spaß.", exampleEs: "Mi afición es divertida." },
      { german: "Musik", article: "die", plural: "—", spanish: "música", exampleDe: "Die Musik ist schön.", exampleEs: "La música es bonita." },
      { german: "Sport", article: "der", plural: "Sportarten", spanish: "deporte" },
      { german: "Fußballspiel", article: "das", plural: "Fußballspiele", spanish: "partido de fútbol" },
      { german: "Ball", article: "der", plural: "Bälle", spanish: "pelota" },
      { german: "Kino", article: "das", plural: "Kinos", spanish: "cine" },
      { german: "Film", article: "der", plural: "Filme", spanish: "película", exampleDe: "Der Film beginnt um acht Uhr.", exampleEs: "La película empieza a las ocho." },
      { german: "Buch", article: "das", plural: "Bücher", spanish: "libro" },
      { german: "Zeitung", article: "die", plural: "Zeitungen", spanish: "periódico" },
      { german: "Lied", article: "das", plural: "Lieder", spanish: "canción" },
      { german: "Instrument", article: "das", plural: "Instrumente", spanish: "instrumento" },
      { german: "Gitarre", article: "die", plural: "Gitarren", spanish: "guitarra" },
      { german: "Konzert", article: "das", plural: "Konzerte", spanish: "concierto" },
      { german: "Freund", article: "der", plural: "Freunde", spanish: "amigo" },
      { german: "Freundin", article: "die", plural: "Freundinnen", spanish: "amiga" },
      { german: "Park", article: "der", plural: "Parks", spanish: "parque" },
      { german: "Wochenende", article: "das", plural: "Wochenenden", spanish: "fin de semana" },
      { german: "Reise", article: "die", plural: "Reisen", spanish: "viaje", exampleDe: "Die Reise ist sehr schön.", exampleEs: "El viaje es muy bonito." },
      { german: "Urlaub", article: "der", plural: "Urlaube", spanish: "vacaciones" },
      { german: "Schwimmbad", article: "das", plural: "Schwimmbäder", spanish: "piscina" },
      { german: "Foto", article: "das", plural: "Fotos", spanish: "foto" },
      { german: "Spiel", article: "das", plural: "Spiele", spanish: "juego" },
    ],
  },
];

function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replaceAll("ß", "ss")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

export const vocabulary = topics.flatMap(({ topic, items }) =>
  items.map((item) => ({
    id: `v-${topic}-${slugify(item.german)}`,
    topic,
    ...item,
  })),
);
